### ISSUE TITLE
Player skin overlay layer will disappear after infected plague

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Rats#107]
I played with slimmer skin

**Comment by BlueWither** [comment]
![2019-10-29_20 32 36](https://user-images.githubusercontent.com/34153394/67763649-8927dd00-fa8b-11e9-8468-f16e0813e7ec.png)
before infected plague
![2019-10-29_20 32 48](https://user-images.githubusercontent.com/34153394/67763660-91801800-fa8b-11e9-98f0-3a27a9b489c0.png)
after infected plague
![2019-10-29_20 32 59](https://user-images.githubusercontent.com/34153394/67763683-98a72600-fa8b-11e9-8823-ac54de766c40.png)
after recovered plague

I used More player Models to take screenshots, but this happened without MPM

**Comment by lag42** [comment]
this seems to happen on both player models, not just the slimmer one

**Comment by BlueWither** [comment]
Oh ok
