### ISSUE TITLE
Crash on startup when using mod on a dedicated server

### ISSUE THREAD

**Issue by erics465** [Alex-the-666/Rats#109]
Hi,
I'm trying to use the mod on a dedicated server. However, I always get a crash when starting the server with the mod enabled.

https://pastebin.com/6QfcEHAK

On a normal minecraft client, it is working fine. I'm using the most recent version from curseforge (3.1.0)

**Comment by erics465** [comment]
It could be easy to fix, just a `@SideOnly(Side.CLIENT)` is missing in https://github.com/Alex-the-666/Rats/blob/master/src/main/java/com/github/alexthe666/rats/client/event/ClientEvents.java#L59 between line 59/60.

**Comment by Alex-the-666** [comment]
have you tried re downloading the mod? i believe i patched this one

**Comment by erics465** [comment]
Oh, wow. It actually worked. I didn't expect that. Nice, thank you. :)
