### ISSUE TITLE
A crash with about 300 mods

### ISSUE THREAD

**Issue by Zack7292** [Alex-the-666/Rats#118]
Hey, i encounter a crash during the lunching of my minecraft game, idk of exacly what its caused but i think you might find it.

it was already there at 3.1.0 but i forgot to report it

Crash log: https://paste.dimdev.org/mirekupiqa.mccrash

there a mediafire link with the mods (there is not ratsin it) (some mods you'll find in the crahs log would'nt be there since it was already doign it and before and since im still modifying the pack but im sure tath the crash log dosn't change): http://www.mediafire.com/file/q113nb6p6eytd04/Big_Ol%2527pack_update.zip/file

don't mind of the changelog, its for the original modpack creator, bcs id on't want to copy his work but i still want ppl to be able to have it so i ask him if he'll like to update it but he didn't answer.

have a nice day and the pirates one are beuties :)

**Comment by Alex-the-666** [comment]
dupe #15

**Comment by Zack7292** [comment]
didn't knew it was already reported, srry tho :)
