### ISSUE TITLE
Ver. 3.2 - Rat eating habbit's cause crazy error floods

### ISSUE THREAD

**Issue by bbbower** [Alex-the-666/Rats#126]
So I couldn't link it to the rat's at first as I was in a dungeon when the error floods started, but it seemed to be when rats began attacking mobs or mobs got near me. Later i noticed rat's on both hunt, and follow would randomly pick up dungeon loot that was edible and eat it.  The errors do not specify it is the rat's mod simply pointing to unknown, then I verified it was to eating habbits by throwing a bunch of cheese in with 6 untame and one already tamed rat(s) in a corner, the flood started again.  Here are some screen shots to show, please let me know if there is any other info that will help, it is in the Seablock: Rustic Waters pack that I'm having the issue but I can not be sure it is limited to it.
![2019-11-14_23 09 24](https://user-images.githubusercontent.com/15827105/68921287-3ebe8580-0746-11ea-90bb-cafaa526be5c.png)
![2019-11-15_01 11 10](https://user-images.githubusercontent.com/15827105/68921295-4847ed80-0746-11ea-8ba1-d6c9310f9857.png)

**Comment by Alex-the-666** [comment]
could you show me what "unknown errror" is being thrown? I'm having trouble reproducing this issue.
