### ISSUE TITLE
Strange crash with rats mod and some living entity tick with a piper near it

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Rats#138]
here is the log hope that helps as it simply crashed near a piper.
https://pastebin.com/ZGCyM3WD
minecraft: 1.12.2 
Forge 14.23.5.2847

**Comment by Alex-the-666** [comment]
>GenLayerBiomeBOP.getInts(GenLayerBiomeBOP.java:64

Biomes o Plenty Crash
