### ISSUE TITLE
Rats are untameable in servers

### ISSUE THREAD

**Issue by Ithidel** [Alex-the-666/Rats#150]
Hello there... I came to realize this issue alongside some others, I don't know the reason why it works this way, but rats in my server don't actually flee from players and a messege appears in screen when you feed them cheese saying they cannot be tamed. If anyone has a solution for this, it would be greatly appreciated.

**Comment by killslash** [comment]
Yes I am having the same issue as well. The rats I am seeing spawn in the Crackpack 3 server I am running are untamable and do not wander. They do respond if attacked, though.

**Comment by killslash** [comment]
![2019-12-10_02 49 19](https://user-images.githubusercontent.com/25662355/70520036-e7c08c00-1b0a-11ea-991d-d50a88dcd5a9.png)

![2019-12-10_02 57 28](https://user-images.githubusercontent.com/25662355/70520089-0030a680-1b0b-11ea-9d5b-f2cfd8ffa897.png)

**Comment by Alex-the-666** [comment]
If you get the message "This rat cannot be tamed" That means its already tamed by another entity.

Usually this means this rat was summoned by a pied piper, and the pied piper died.

These rats can be freely killed

**Comment by killslash** [comment]
Hmm. I never killed a pied piper. Do other things kill them or do they despawn, leaving the rats?

**Comment by blisterfingers** [comment]
Having similar related issues in CrackPack 3.
Killed a Piper early on and haven't seen a single rat since until found one of these near my base, thousands of blocks away from where I killed that Piper. Gives the can not be tamed message though I am the only player on the server. 
Tried increasing the spawnrates back to the defaults but still not seeing any rats.
Rats spawned using Spawn Eggs appear to act correctly.

**Comment by killslash** [comment]
Yes crackpack 3 seems to have an extreme lack of untamed rats. To get one "legit" you need to create a spawner for it using another mod.

Pipers spawn and despawn leaving their rats. They should despawn too.

**Comment by renzhentaxi** [comment]
I think what happens is that rats are considered passive mobs(like cows) and thus they dont despawn.
whereas the piper is a hostile mob (like zombies) and do despawn.

**Comment by killslash** [comment]
Yeah there are tons of tamed rats in caves that don't seem to despawn, or despawn infrequently.

**Comment by Alex-the-666** [comment]
should be fixed in 3.2.5
