### ISSUE TITLE
Cannot find any Rat

### ISSUE THREAD

**Issue by donkaike** [Alex-the-666/Rats#153]
Hello!
I'm playing rats but I cannot find any rat in any place.
I found a petshop but none rat!

**Comment by renzhentaxi** [comment]
try using /tp @e[name=Rat,c=1]
this will teleport u to the closest rat.
if the rat is already tamed, then kill the rat with a lava bucket and run the command again until you see a rat that runs away from you

**Comment by Alex-the-666** [comment]
should be fixed
