### ISSUE TITLE
Blacklist Unaccessible After Combined

### ISSUE THREAD

**Issue by reikonyx** [Alex-the-666/Rats#156]
I see there is an older closed issue but I'm still experiencing this with the latest version of Rats (3.2.4) Unable to edit blacklist upgrade once it is combined with others. The combined upgrade is not "useable" as in i cannot bring up the blacklist menu/inventory. Perhaps it is something i am doing wrong? Current combined item: Speed+Platter+Blacklist

**Comment by Alex-the-666** [comment]
Create the rat upgrade seperator
