### ISSUE TITLE
Rats spawn as tamed/do not correctly despawn, cause major lag

### ISSUE THREAD

**Issue by katubug** [Alex-the-666/Rats#157]
Hello! I'm running the MC. Eternal modpack, version 1.2, on my server currently.

We keep having instances of TPS dropping from 20 to about 5, and each time, I've run a `/forge entity list` and found over 3200 rats were in the world. They seem to be congregating under someone's base - I'm suspecting a Roguelike Dungeon may be in those chunks.

I found this issue: https://github.com/Alex-the-666/Rats/issues/146 but they said it was resolved with the update. Ours is with 3.2.4.

There's also this issue on the modpack's github: https://github.com/adam9899/Issues/issues/93 where I'd initially reported it. Another user suggests that it may be due to rats spawning as tamed. I have not been able to investigate due to irl busyness.

As a workaround, I've added the rats to our server's bi-hourly hostiles cull, and that seems to have made a difference.

Minecraft: 1.12.2
Forge: 2847
Rats: 3.2.4
Llibrary: 1.7.19

**Comment by AndyHobi** [comment]
Can verify this issue on MC. Eternal version 1.2. There are 1700 rats in one player's range and they all seem to have the tamed attribute. they seem to coat deep caves such as dragon lairs.

![image](https://user-images.githubusercontent.com/44441124/72774564-5cf3a680-3c0b-11ea-9b4f-380aa48c2d63.png)

Versions are identical to OP

**Comment by Alex-the-666** [comment]
fixed
