### ISSUE TITLE
Strange compat issue between this mod and Climatic Biomes

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Rats#158]
[latest.log](https://github.com/Alex-the-666/Rats/files/4050752/latest.log)

Look at the last lines. Something really weird is happening between the two.

**Comment by BlackJar72** [comment]
I'll look at my own code to make sure this isn't a really bizarre coincidence -- though I thought rivers going out of bounds was already tested for.

**Comment by Sunconure11** [comment]
@BlackJar72 Of note is that this issue also caused my rats to despawn.

**Comment by BlackJar72** [comment]
Now that is strange ... nothing in my mod should affect this either, or despwn any mob.  I am uploading a new Climatic Biomes version with the extra test that should stop the crash, but something very strange is going on I can't explain.

**Comment by Sunconure11** [comment]
@Alex-the-666

**Comment by Alex-the-666** [comment]
The server side getting the tile entity through 

> at net.minecraft.world.World.getTileEntity(World.java:2399)

should not cause a crash, this is a problem with the "MapMaker" mod.
