### ISSUE TITLE
Wild Rats not taking damage from player

### ISSUE THREAD

**Issue by srwaggon** [Alex-the-666/Rats#163]
I've encountered rats which become aggressive when struck by the player, but do not lose any HP (observable via NEAT mod). However, when lit on fire, they take fire damage.

I wish I had more insight. Any additional information I could provide?

**Comment by DoomSquirter** [comment]
same here
rats-3.2.4

**Comment by srwaggon** [comment]
I looked into this more and something else  is going on. I encountered another invincible rat, which had glowing green eyes even in the light. I had to kill it through fire as my sword continued to do no damage. 

I then jumped into creative mode and spawned some rats using the spawn egg for rats. Each one had black eyes, and were receptive to taking damage from my sword.

**Comment by Alex-the-666** [comment]
That rat has a legendary upgrade... someone is messing with you

**Comment by cenodis** [comment]
Singleplayer world, got attacked by rats from a Piper and attacking them with a sword did no damage. Lighting them on fire worked but is very frustrating. Killing the Piper made no difference and the rats stayed invincible.
Rats 3.2.5

**Comment by srwaggon** [comment]
@Alex-the-666 This seems unlikely. I'm playing single player (albeit on a multiplayer server that no one else has access to).

**Comment by CelestialSkies95** [comment]
I'm seeing this as well. On a single player server as part of MC Eternal, rats version is 3.2.6. The Pied Piper spawned some rats and none of them take damage from me

**Comment by SandwichHorror** [comment]
Rebirth of the Night v 3.2.7 - I can't consistently replicate this but we've had about a dozen reports of players not being able to damage wild rats.

**Comment by Garfink** [comment]
Happened to me as well, the "Piper" spawned and I killed a few of the rats, was getting low on health and could get close to the "Piper" to kill it because of his summoned rats.  So I ran.  I jumped in an ocean and noticed these 2 rats still chasing me.  The piper seemed to have lost interest, so I turned around to deal with the rats....  They were immortal, could not be killed.  I ran from them till they despawned.  

I am on the latest version of rats (as of 20/April/2020).  It has only happened once since in my game the piper only appeared once so far.  Could happen everytime for all I know.  I too am using the Rebirth of the Night Modpack.

**Comment by Randonx** [comment]
Every interaction I've had with the Pied Piper has left me dead, as the Rats are always invulnerable to weapons.  I don't have a portable fire source yet for dealing with them, as some have stated here.

They are insanely fast as well, even sprinting with no debuffs I can't outrun them, and they end up killing me eventually.  The only escape has been to pillar, which I did once.

Playing Rebirth of the Night 2.77.1  Rats 3.2.6

**Comment by BTOptimizer** [comment]
I have this issue too but it's slightly different. We get a message like this in a multiplayer server running MC Eternal 1.3.5.3, Rats 3.2.8:

![image](https://user-images.githubusercontent.com/62932802/80428376-af51fc80-88b7-11ea-98a0-96bbc43fa0b4.png)

**Comment by Alex-the-666** [comment]
So its another mod making it impossible to hurt rats. great. If you can help me find out what mod causes that @BTOptimizer that would be helpful

**Comment by BTOptimizer** [comment]
It may also be a plugin, I play MC Eternal on a multiplayer server. On the server, I know there's a claim plugin but I don't know if it covers ownership of animals but I will test this and get back to you as soon as I can.

**Comment by SandwichHorror** [comment]
Is it possible it's due to Charm's friendly fire option? Ideally this option would not apply to rats the player has not interacted with, but perhaps the rats are registered as "tamed" by the Piper and so are mistakenly invincible

`# Tamed animals no longer take direct damage from players.
    # They still suffer secondary effects, such as burning from a Fire Aspect sword.
    B:TamedAnimalsNoDamage=true`

**Comment by Alex-the-666** [comment]
fixed
