### ISSUE TITLE
[Suggestion] Work area

### ISSUE THREAD

**Issue by Baughn** [Alex-the-666/Rats#165]
I love my lumberat, but sometimes he runs off to collect dropped items from inside my base, or to chop down my (wooden) bridge, and this is a bummer. It's especially a bummer given the pathfinding issues; rats usually get stuck if they have to navigate anything more complex than a 2D plane.

It would be great if we could set a limit on where they can operate. Not only would it limit the usage of server CPU and reduce the number of pathfinding fails, but also it might keep my bridges unmolested. What say you?

**Comment by Baughn** [comment]
Speaking of pathfinding issues, I suspect that right now it's trying to path to a tree that's floating in mid-air, since it wasn't able to fully chop it down previously.

**Comment by Alex-the-666** [comment]
implemented in 2.3.6
