### ISSUE TITLE
Rats version 1.12.2 (3.2.6) [Energy transfer does not work with Mekanism & Mekanism Generators]

### ISSUE THREAD

**Issue by TheGiantBean** [Alex-the-666/Rats#175]
So I tried using a tamed rat with energy transfer upgrades (all types(not at the same time though)) to take energy from the wind generator and deposit it into an energy reservoir such as the energy cube or any machine and it does not work no matter how long I wait. It is on transport items mode as well. I was planning to use this mod with Mekanism, Applied Energistics, and Ender io. Looking forward to a patch!

**Comment by Alex-the-666** [comment]
make sure the windmill/whatever generator's settings are to have extract from the side the rat is taking energy from.
