### ISSUE TITLE
[4.0.2] Rat crafting crashes

### ISSUE THREAD

**Issue by Aivilo222** [Alex-the-666/Rats#193]
The rats either won't deposit items in the crafting table when set to gather resources, or the game crashes when they try to put them in the crafting table

**Comment by Slither88** [comment]
[crash-2020-04-05_22.10.52-server.txt](https://github.com/Alex-the-666/Rats/files/4434768/crash-2020-04-05_22.10.52-server.txt)
Same issue her. Crash log attached

**Comment by Slither88** [comment]
Also all rats involved get reset and loose all of their upgrades when the game recovers.
