### ISSUE TITLE
[Bug] Rat Crafting Table Cosumes Bucket

### ISSUE THREAD

**Issue by Areorah** [Alex-the-666/Rats#195]
Rats Version: 3.2.4

If I craft something that requires a bucket of liquid, it consumes the bucket as well. I'm trying to craft treated wood planks (from Immersive Engineering), and it consumes the bucket and it shouldn't. If I normally craft via a crafting table, it won't consume the bucket only the liquid.

**Comment by Alex-the-666** [comment]
not able to replacate in 3.2.6
