### ISSUE TITLE
1.14 Rat Miner doesn't work serverside

### ISSUE THREAD

**Issue by SebaSphere** [Alex-the-666/Rats#199]
The miner looks like so on servers. Rat won't mine.
![image](https://user-images.githubusercontent.com/27737877/76709834-5009a580-66d8-11ea-99b5-da80df7e1860.png)

In singleplayer, you are able to add items without it not letting you add em. I haven't tested rats actually mining tho but the miner seems to work correctly whitelisting items compared to serverside.

**Comment by SebaSphere** [comment]
rats-4.0.2-1.14.4.jar

**Comment by Alex-the-666** [comment]
fixed
