### ISSUE TITLE
Suffocation makes Rats unfavorable to use without access to the combiner.  Rats v.3.2.6 for MC 1.12.2

### ISSUE THREAD

**Issue by Aedict** [Alex-the-666/Rats#201]
The upgrade combiner is a very late game block to acquire making it impossible to use rats early game for tree automation without rats dying frequently.  For early game feasibility, it would be great to have a config option to prevent suffocation damage without the need for an upgrade.  I'm currently building a progression modpack highlighting rats as the first stage of automation and would like to keep most of the features gated in line with the mods defaults.  Sorry if this is not posted in the correct area, I did not see any separate locations for feature requests.

**Comment by Alex-the-666** [comment]
will be fixed in 2.3.7
