### ISSUE TITLE
[1.14.4] Server crashed when accessing inventories of TileEntityRatCraftingTable

### ISSUE THREAD

**Issue by Prunoideae** [Alex-the-666/Rats#204]
Crash report:
https://paste.ubuntu.com/p/8dmJjxpcjx/ (Using Create's Deployer)
https://paste.ubuntu.com/p/F9dYSzq6m8/ (Using Vanilla Hopper)

How to reproduce:
Place a deployer or something that will access the table's side inventory. At least which will trigger [this](https://github.com/Alex-the-666/Rats/blob/cbbe0d69018047eb299cd42533f44a91f155aaa9/src/main/java/com/github/alexthe666/rats/server/entity/tile/TileEntityRatCraftingTable.java#L481). 

It seems that the code of the mod create is just fine, the ArrayIndexOutOfBoundsException is because the initialized list is of length 2(0,1). This is a quite severe crash since it's happened whenever a tile tries to access the side inventory.

**Comment by Alex-the-666** [comment]
fixed
