### ISSUE TITLE
Rats not spawning correctly in preexisting world  (1.14)

### ISSUE THREAD

**Issue by lindykamm** [Alex-the-666/Rats#210]
I recently downloaded the Rats mod to a preexisting modded world (no MAJOR mods other than maybe lycanites) and I've noticed that rats aren't spawning into any preexisting chunks around my base at night. I've set out traps, crops, a chest of cheese, with no results. I have even tried spawning in rats by giving myself spawn eggs, in attempt for them to breed, but they despawned. However, rats are spawning in newly loaded chunks whenever I am exploring, but I've only seen them spawn in through the piper illager (i think thats what it's called haha). I haven't seen any naturally spawned rats otherwise.

**Comment by Froosty11** [comment]
Same issue.

**Comment by BoshaNova** [comment]
I am having this issue too, i don't think the config file is being read because i adjusted the spawns and the ability to craft cheese in the cauldron but i was still able to craft it after disabling that option.

**Comment by BoshaNova** [comment]
Thanks Alex!! looking forward to the next rats patch
