### ISSUE TITLE
Farmer Crash

### ISSUE THREAD

**Issue by phit** [Alex-the-666/Rats#213]
Sorry, dont have any additional info besides the crash report

rats 4.0.2-1.14.4
forge 28.2.3

https://gist.github.com/phit/297f330ea08dc5d959acc4cc8657b7f1

**Comment by UnstableCodeScarlet** [comment]
Did some testing with just rats alone, it's caused by planter rats attempting to place blocks from chests marked to take items from. IE Dirt or Diorite

Crash report (The same one basically) - https://pastebin.com/DerJJTCX
