### ISSUE TITLE
Rat Skull drops not configurable

### ISSUE THREAD

**Issue by X66Herobrine66X** [Alex-the-666/Rats#227]
So rat skulls don't drop at all. I checked the json loot tables and it looks like someone forgot to add the rat skull drop to em. This makes aristocrats, voodoo rats, beast mounts, undead rats, battle gods, and purifying liquid unobtainable.

**Comment by Alex-the-666** [comment]
they arent in the loot tables. theyre hardcoded. initially it was like this to be configurable but i guess i forgot to do the config.

**Comment by X66Herobrine66X** [comment]
Wouldn't them being in the loot table make them more configurable? You could override and change it with a simple data pack instead of having to mess with the code of the mod.
