### ISSUE TITLE
[Suggestion] Make tamed rats non hostile.

### ISSUE THREAD

**Issue by Yhuxz** [Alex-the-666/Rats#23]
After being tamed, make those rats non hostile so we can use extra utilities' golden lasso to pick em up instead of cursed lasso.

```
If incase the option is already presented

> **# True if rats should spawn like monsters. False if they should only spawn once per world, like pigs and sheep. [default: true]**

please have an option to make it per game restart not per world, so if we mistakenly set this to true and change it to false, those tamed rats would change to non hostile

(if this config is different to my suggestion please disregard)
```

**Comment by Alex-the-666** [comment]
not what the config means. the config has nothing to do with the behavior fo the rats, only that they should spawn **with hostile mobs at nighttime or in dark places** or like **pigs and sheep and only spawn when chunks are loaded on grass blocks**.

**Comment by Yhuxz** [comment]
Since the config is not case, the suggestion is still open on how rats should not be a hostile mob in the first place (except the plague rat) 

What I really ment is like the wolf, it is tameable but its character is not hostile after been attacked (sorry if im kinda misleading something Im not a coder nor in knowledgeable in minecraft terminologies)
