### ISSUE TITLE
Planting logs

### ISSUE THREAD

**Issue by Nuan07** [Alex-the-666/Rats#232]
I'm trying to automate a tree farm with Rats, for some reason the planter is identifying an oak log as an oak sapling?

**Comment by wrincewind** [comment]
The planter will place any blocks you give it, not just seeds or saplings. I suggest you either have him take items from a filtered chest that only has saplings in it. Maybe use another rat with the whitelist upgrade to put saplings in that chest?

**Comment by Alex-the-666** [comment]
^
