### ISSUE TITLE
[Feature Req.] Rat Mass Storage and other misc things.

### ISSUE THREAD

**Issue by ScorcherOfAwesomeness** [Alex-the-666/Rats#24]
Id love to see this added as it could make survival early game much easier. So there would be 6 blocks/items that would make it up

- Rat Terminal: The heart of the system that lets you access the rat storage system.
- Rat Terminal Slave: A rat terminal but multiple can be in one system
- Rat Interface: Rats can autocraft things. Even with things in other mods. Just stick in a Rat Pattern and request things. The rat would get items, go up to it, and stick it in.
- Rat Pattern: You "encode" something on it that rats can see, and they will get items and stick it in the interface.
- Rat Home. Rats go here when idle.
- Terminal Stick: Like the cheese stick, it will bind terminals to chests, and masters to slaves.

A couple of new mechanics
Mode "Terminal Worker" - A rat that would use and go with the Rat Terminal
Mode "Autocrafter" - A rat that would use the Rat Interface.
Upgrade "Transporter" - A rat with this can carry multiple stacks and multiple items. Appears as 3 platters, one in each hand and one on its head. Helmets will move that plater on the helmet.
Lazyomiter: Rats with very high lazyomiter can only wander, breed, follow you, and stay.

**Comment by Alex-the-666** [comment]
no. this is literally just AE2 but rats.

**Comment by ScorcherOfAwesomeness** [comment]
"No Technology" playthroughs. This will make it much easier.

**Comment by ScorcherOfAwesomeness** [comment]
But whatever you say.

**Comment by ScorcherOfAwesomeness** [comment]
Although its a little more like logistics pipes.
