### ISSUE TITLE
Crash when breaking garbage pile

### ISSUE THREAD

**Issue by GoldenZdude** [Alex-the-666/Rats#241]
Describe the crash
Game crashes when breaking certain variants of the rats "garbage pile" in survival
To Reproduce

break rats:garbage_pile in survival
certain variants of the block will drop a missing texture, crashing the game
Crash Log
https://pastebin.com/9nN0MHtV

Info (please complete the following information):

Modpack Version: 2.77.1
Server or Singleplayer: Singleplayer
Version the world was created on: 2.77.1
Additional context
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by GoldenZdude** [comment]
rats 3.2.6 minecraft 1.12.2

**Comment by democat3457** [comment]
bump
