### ISSUE TITLE
Ore Doubling not working on servers 

### ISSUE THREAD

**Issue by xanderhunter** [Alex-the-666/Rats#258]
Trying to get the ore doubling to work on the Kreation modpack and for some reason it isnt working on server mode but is working on single player.  Rat will take a Iron Ore and go through the animation of eating it and it will turn into the nuggets in his hand, but he wont drop it and when you check him with right click it is still a ore block.  Multiple blocks just cause him to continue the eating animation infinetly.

**Comment by Alex-the-666** [comment]
this was fixed a few hours ago. update the mod
