### ISSUE TITLE
crash in 1.15.2 / atm5 while breeding rats

### ISSUE THREAD

**Issue by MagieMalone** [Alex-the-666/Rats#259]
I assembled a cage, put the breeding light in, then clicked 1 male, 1 female rat inside which led to this crash.

https://pastebin.com/vajDZxsr

also, crashes again when entering the world, I had to delete the chunk

**Comment by DreiPixel** [comment]
i have the same problem
rendering crash as soon as it tries to render a rat fricking
https://pastebin.com/TMEB2Rsr

**Comment by Alex-the-666** [comment]
>        rats-5.0.1-1.15.2.jar Rats {rats@5.0.1 DONE}

bug has already been fixed
