### ISSUE TITLE
Rats w/ Pied Piper can not be attacked

### ISSUE THREAD

**Issue by felltablet** [Alex-the-666/Rats#260]
The rats that the PP commands can not be damaged with conventional attacks.  This make an otherwise amazing and unique mod unplayable, especially with mods that improve difficulty.   Cats and other damage not from the players will still effect these mobs.

**Comment by Alex-the-666** [comment]
what version of mod

**Comment by felltablet** [comment]
We are using:

rats-5.0.1-1.15.2
<https://www.curseforge.com/minecraft/mc-mods/rats/files/2938926>

**Comment by felltablet** [comment]
Thanks for the quick reply and fix!  My wife loves this mod.  It is one of
the few additions to the game that  adds something unique and helpful while
not overloading it with low quality nonsense.  Glad to see you have a
patreon, keep up the good work, and hope to see your own stand alone games
soon.
