### ISSUE TITLE
[1.12.2] Bug - Milkmaid upgrade stops once target container has filled up once.

### ISSUE THREAD

**Issue by Maxzilla60** [Alex-the-666/Rats#263]
A rat with the Milkmaid upgrade and set to "harvest" will continuously milk a cow and deposit that liquid into given liquid container (set with the Cheese Staff) - as expected.
Once the given container has no more room for liquid the rat will stop - also as expected.

But if after this container regains some room for liquid, the rat will not continue the process. This seems indefinite/permanent - the rat will never milk again.

Reassigning a different container, re-giving the rat the same upgrade, picking up the rat and placing back down (via shoulders or via Rat Sack), and switching the status of the rat all do not reset this bug.
It seems the only way to have a rat start milking again, is to spawn an entirely new rat and give it the upgrade etc..

Do note that the Bucket upgrade does not have this issue.

Containers tried with:
- OpenBlocks' Tanks
- Several of Immersive Engineering's blocks
- Rustic's Barrel
- Thermal Expansion's Portable Tanks
- EnderIO's Reservoirs
- Mekanism's Tanks

**Comment by Sluggasaurus** [comment]
We are also experiencing this issue on our server, but we have figured out that stacking the portable tanks from Thermal Expansion helps go around this bug as a temporary solution
[heres a pic of what we did](https://cdn.discordapp.com/attachments/568292318558289920/705156686893023242/unknown.png)

**Comment by xalixilax** [comment]
i'm actually using the version rats-7.0.0-1.16.3 in the modpack allthemods 6 and i'm getting the exact same issue. Didnt test with all the same container but replicated everytime i tested.
