### ISSUE TITLE
[1.15.2] [Bug] Pied Piper's rats are still unkillable

### ISSUE THREAD

**Issue by MariaTargaryen** [Alex-the-666/Rats#265]
I've created a custom modpack for the server, and the problem we are having is invincible rats after Pied Piper is dead. 
Here's the list of mods in the modpack:
![image](https://user-images.githubusercontent.com/28529698/80811075-d8cb9a80-8bcd-11ea-88b7-c920e393c99e.png)
Also tried to turn off the pied piper at all, but there is only the config for the client side, not the server side.
We are using the 5.1.0-1.15.2 version atm.

**Comment by lamoyrl90** [comment]
There's more config files in the serverconfig folder in your world save.

Still doesn't fix the issue though, I'm having the same problem. I can't hit the rats even though I'm swinging right at their hitbox.

**Comment by Alex-the-666** [comment]
fixed
