### ISSUE TITLE
1.15.2 crash

### ISSUE THREAD

**Issue by footwanterfin** [Alex-the-666/Rats#276]
After the 5.2.0 update everytime I try to create a world or go into an excisting world the game crashes.
[crash-2020-05-06_11.23.19-server.txt](https://github.com/Alex-the-666/Rats/files/4585591/crash-2020-05-06_11.23.19-server.txt)

**Comment by LordMadJack** [comment]
Same problem here, my server crash when I try to restart after an update  from 5.1.0 to 5.2.0.
Back to 5.1.0

**Comment by utcafiu** [comment]
single player crashing when loading the config, because it is trying to cast from Double to boolean. The reason is, two different parameter is referenced by the same name:
ServerConfig.java
        this.ratsDespawn = buildBoolean(builder, "Rat Immediate Despawn Distance", "all", true, "True if wild, untamed rats can despawn.");
        this.ratDespawnFarDistance = buildDouble(builder, "Rat Immediate Despawn Distance", "all", 144F, 0F, Float.MAX_VALUE, "Distance that untamed rats will immediately despawn. For Vanilla mobs, this is 128 blocks.");

**Comment by Alex-the-666** [comment]
fixed
