### ISSUE TITLE
Latest Update 1.15.2 Crash

### ISSUE THREAD

**Issue by Camawama** [Alex-the-666/Rats#278]
I updated from version 5.1.0 to 5.2.0 and now every time I try to create a world the whole game crashes. I am running Forge Version 31.1.74 and I have uploaded a crash report
[crash-2020-05-06_15.53.15-server.txt](https://github.com/Alex-the-666/Rats/files/4589432/crash-2020-05-06_15.53.15-server.txt)

**Comment by Alex-the-666** [comment]
fixd
