### ISSUE TITLE
[Mod Interaction] Cheese uncraftable with Inspirations installed

### ISSUE THREAD

**Issue by thephoenixlodge** [Alex-the-666/Rats#28]
As per the title, installing Rats alongside Inspirations (https://minecraft.curseforge.com/projects/inspirations?gameCategorySlug=mc-mods&projectID=284007) renders cheese uncraftable, due to it taking over the Cauldron to add a lot more functionality. Instead of getting the "Milk Cauldron" block, the cauldron is just outright filled with milk normally.

**Comment by Azmalent** [comment]
Well, it works if you shift-right click the cauldron with a vanilla milk bucket. 
Although it would be great to have special compatibility with Inspirations!
