### ISSUE TITLE
[Mod Incompatibility] [1.12.2] All tamed rats disappear when playing with Astral Sorcery mod

### ISSUE THREAD

**Issue by QuietAsAMouse** [Alex-the-666/Rats#283]
Minecraft Version:  1.12.2
Rats Mod Version:  3.2.11 for 1.12.2
Astral Sorcery Version:  1.10.23

Just as title says.  Was playing in a survival world, teleported using Celestial Gateway with Astral Sorcery mod while attuned to the star Vicio.  All of my tamed rats disappeared, including two sitting in my house and one on my head.  Tested a little in creative, and it only seemed to happen when I am attuned.  VanillaFix suggested that Rats was causing a problem.

**Comment by Platipucat** [comment]
i dont have Astral Sorcery but my tamed rats also disappeared

**Comment by Mnesikos** [comment]
Updated from Rats 3.2.9 to 3.2.11 for a server and all of our tamed rats were ganked too. This is the only evidence I found of it in our logs: https://gist.github.com/Mnesikos/d5555a5d2ca93dccf13310a2e529a328

Also in 1.12.2, forge 2847, sponge forge 7.1.7, various other mods and plugins I can supply a list of if needed.

**Comment by xMrCaosx** [comment]
My rats disappeared too and i dont hv astral sorcery, it seem to be a problem with the latest version. Because i was testing yesterday, playing on the previous versión all is normal, updating the mod still normal. But if i quit the game having the last version and i enter again on the game all my rats disappeared.

**Comment by Mnesikos** [comment]
I think it has to do with chunk loading, and even effects untamed rats- who despawn anyways, but the error occurring (via same stacktrace linked in my last post) with them too makes me believe any newly tamed rats are going to be effected as well.

**Comment by BenjaminLeSire** [comment]
It's not a specific incompatibility with AS, rather, the rats despawn whenever the dimension they're in unloads (quitting, changing dimensions, etc.). See #287 .

**Comment by QuietAsAMouse** [comment]
Ah, I see.  Thanks for the info!
