### ISSUE TITLE
[1.12.2] Crash when attemping to use Rat Bag on Rat Cage

### ISSUE THREAD

**Issue by Dulcissimus** [Alex-the-666/Rats#290]
Rats ver. 3.2.11
The crash happened while I was in a modded server with my custom modpack. The crash was client-side and did not affect the server.

Steps to Reproduce:
1. Obtain 3 rats in a Rat Bag.
2. Use the Rat Bag on a Rat Cage, For me, there were a baby rat in the cage I clicked, with Heart Lantern.

Crash Log:
[crash-2020-05-15_04.19.38-client.txt](https://github.com/Alex-the-666/Rats/files/4633204/crash-2020-05-15_04.19.38-client.txt)

The log stated that the crash is about **invalid UUID string**. I am unsure if this crash related to #287.

**Comment by BenjaminLeSire** [comment]
Yes, it's the same one. It gets reported a lot :) .
