### ISSUE TITLE
[1.12.2] Illager Piper spontaneous crash

### ISSUE THREAD

**Issue by TimeConqueror** [Alex-the-666/Rats#301]
Well, the game crashes sometimes, eventually, while I'm in the world. After crash I can't enter the world (only changing player pos in level.dat helps).

[crash-2020-05-27_00_17_51-server.txt](https://github.com/Alex-the-666/Rats/files/4685364/crash-2020-05-27_00_17_51-server.txt)

Similar crash, that was got by me one day before the first one: 
[crash-2020-05-25_20_59_46-server.txt](https://github.com/Alex-the-666/Rats/files/4685382/crash-2020-05-25_20_59_46-server.txt)

**Comment by Alex-the-666** [comment]
udate your mod

**Comment by TimeConqueror** [comment]
After updating to 3.2.11
[crash-2020-05-30_18_56_55-server.txt](https://github.com/Alex-the-666/Rats/files/4706436/crash-2020-05-30_18_56_55-server.txt)
