### ISSUE TITLE
Pied Piper Spawning in Caves

### ISSUE THREAD

**Issue by Dvoric** [Alex-the-666/Rats#31]
The Pied Piper is spawning in caves. I'm not sure if that's intended, but in your mod description it says, "All those who venture into roofed forests and other magical biomes should beware." 

I was just chillin' in my house when I started hearing him play. So I looked everywhere above ground, tearing my hair out trying to find him, because his flute started to get super annoying. Then I finally dug straight down and there he was hangin' out with skeletons & creepers in some dark cave way below ground. Seemed kind of odd, I mean, the pipe is pretty loud above ground.

I know there is an option to turn him completely off, but I'm not exactly sure if I want to do that yet. An option to control the height at which he spawns might be cool? Or maybe some way to control how loud the pipe sound is or something? idk

MOD: rats-1.1.0, LLibrary 1.7.19, BiomesOPlenty-1.12.2-7.0.1.2441
FORGE: 2836
OPTIFINE

This mod rocks, BTW I absolutely love it so far. Thank you! =)

**Comment by Alex-the-666** [comment]
intended. He will spawn like a normal monster, except more frequently in certain biomes.

**Comment by Dvoric** [comment]
OK, cool ... So there is absolutely no way to increase or decrease the distance at which we hear his pipe? Or no way to control the volume, or sound, of his pipe either?

Thank you for all your time & help, Alex-the-666!! (◣_◢)\,,/

**Comment by Dvoric** [comment]
> intended. He will spawn like a normal monster, except more frequently in certain biomes.

OK, cool ... So there is absolutely no way to increase or decrease the distance at which we hear his pipe? Or no way to control the volume, or sound, of his pipe either?

Thank you for all your time & help, Alex-the-666!! (◣_◢),,/

**Comment by Dvoric** [comment]
> intended. He will spawn like a normal monster, except more frequently in certain biomes.

OK, cool ... So there is absolutely no way to increase or decrease the distance at which we hear his pipe? Or no way to control the volume, or sound, of his pipe either?

Thank you for all your time & help, Alex-the-666!! (◣_◢) \,,/
