### ISSUE TITLE
[1.14.4] plague doctor hut and garbage pile generation

### ISSUE THREAD

**Issue by alpacaswillrule** [Alex-the-666/Rats#313]
I cannot find any plague huts or garbage piles in any villages, despite my config being set to allowing them to spawn. I originally encountered this issue while using other mods but then disabled those mods and generated a new world and used /locate plus random teleports to look for plague huts but I still could not find any. I have checked about 20 villages so far.

**Comment by alpacaswillrule** [comment]
Another addition: I encountered this issue in both survival and multiplayer

**Comment by Alex-the-666** [comment]
they were removed due to villages being redesigned
