### ISSUE TITLE
Intense Lag on Dedicated server

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Rats#32]
version of mod 1.1.1

Image of relevant data:
![screenshot-sparkprofiler github io-2019 06 22-10-41-32](https://user-images.githubusercontent.com/3880072/59965972-f83c6600-94da-11e9-892f-b059cb46f10b.png)

Estimated lag hit 6 tps, ie down to 14:
![image](https://user-images.githubusercontent.com/3880072/59965985-2c178b80-94db-11e9-8a16-92bd7b974445.png)

Number of players on server: 8
![image](https://user-images.githubusercontent.com/3880072/59966008-6e40cd00-94db-11e9-8638-1ec96b5c53c6.png)

Spark Profile: https://sparkprofiler.github.io/#BxyyfI3TVx

If it helps these logs from the server:

debug.log
http://paste.ubuntu.com/p/YtHQTN4JsM/

latest.log
http://paste.ubuntu.com/p/ZB7nZM47TS/

**Comment by Alex-the-666** [comment]
Alright so the issue appears to be located in RatAIEnterTrap.shouldExecute(), RatAIRaidChests.shouldExecute(), and RatAIRaidCrops.shouldExecute().

It seems the issue revolves around the resetTarget() method in all of these classes.

**Comment by kreezxil** [comment]
I'm glad the report was useful.

**Comment by Alex-the-666** [comment]
yeah, it actually really was. I'm still learning how to use spark, and I'll make sure i maximize the use of it for the next ice and fire update.

**Comment by Alex-the-666** [comment]
alright. asides from making the code more CPU friendly, I also added a config option, ratUpdateTick, which can be increased in order to delay how often rat AI updates.
