### ISSUE TITLE
Rat Dupe

### ISSUE THREAD

**Issue by Ashley123477** [Alex-the-666/Rats#321]
Spamming the rat bag with any rat in it so you drop and pickup the rat as quick as possible duplicates said rat.

Minecraft version 1.12.2
Rats version 3.2.12-1.12.2

**Comment by Ashley123477** [comment]
Was this fixed?

**Comment by Alex-the-666** [comment]
yes. https://github.com/Alex-the-666/Rats/commit/b24ebdd0fc0a7098060d6fefe6899cce337757a7
