### ISSUE TITLE
Rats pathing error causing crash. And rats not digging properly trough all blocks.

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Rats#323]
[crash-2020-06-21_10.13.34-server.txt](https://github.com/Alex-the-666/Rats/files/4809777/crash-2020-06-21_10.13.34-server.txt)

I noticed 2 things first soemtimes rats crash on pathing like linked in the crashlog here.

Second would be that rats dont seem to dig their way trough blocks into rooms with chests filled with food or indoor farms etc. cant tey go trough materials other than wood? or 2-3 thinck walls? i set their digging strenght to 50 they should even get trough obsidian.

**Comment by mr-poyo** [comment]
Also getting a similar crash
