### ISSUE TITLE
Crashed Client - Rats 1.16.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Alex-the-666/Rats#334]
I'm putting together a 1.16.1 mod pack and just added your Rats mod for 1.16.1 and it crashed the client

MultiMC version: 0.6.12-develop-1365
OS Linux Mint: 19.3
Java: 1.8.0_212, using 64-bit architecture
Minecraft: 1.16.1
Forge: 1.16.1-32.0.44
Rats: 6.0.0-1.16.1

https://pastebin.com/BgaARwip

**Comment by Alex-the-666** [comment]
Odd. in the meantime, disable the Experimental option in rats client config.

**Comment by ClaudiusMinimus** [comment]
I disabled the option and the world loaded fine.

**Comment by ClaudiusMinimus** [comment]
BTW: I love your mod!

**Comment by Alex-the-666** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/rats/files/2995826 .
