### ISSUE TITLE
"Exception in server tick loop" when placing Rat Cage, Rat Tube, or Rat Hole [1.16.1]

### ISSUE THREAD

**Issue by jabenc** [Alex-the-666/Rats#339]
Whenever I place down a Rat Cage or a Rat Tube, the game freezes and crashes.

[crash-2020-07-08_12.47.58-server.txt](https://github.com/Alex-the-666/Rats/files/4892094/crash-2020-07-08_12.47.58-server.txt)

**Comment by excinere** [comment]
Downgrading Forge version to 32.0.48 seems to fix it. Not sure what the maximum version is, though.

**Comment by ClaudiusMinimus** [comment]
I just tried to move a rat cage and it crashed my test server and client.

rats-6.0.2-1.16.1
forge 32.0.59

[crash-2020-07-10_02.51.23-server.txt](https://github.com/Alex-the-666/Rats/files/4900202/crash-2020-07-10_02.51.23-server.txt)
[crash-2020-07-09_18.51.30-client.txt](https://github.com/Alex-the-666/Rats/files/4900207/crash-2020-07-09_18.51.30-client.txt)

**Comment by ClaudiusMinimus** [comment]
And this log
[crash-2020-07-10_06.15.06-server.txt](https://github.com/Alex-the-666/Rats/files/4900761/crash-2020-07-10_06.15.06-server.txt)

**Comment by Alex-the-666** [comment]
fixed
