### ISSUE TITLE
Rat Cage crash upon placement

### ISSUE THREAD

**Issue by huntzilla360c** [Alex-the-666/Rats#344]
[crash-2020-07-10_21.02.42-server.txt](https://github.com/Alex-the-666/Rats/files/4906077/crash-2020-07-10_21.02.42-server.txt)
[HC_Client-crash-2020-07-10_20.53.34-client.txt](https://github.com/Alex-the-666/Rats/files/4906078/HC_Client-crash-2020-07-10_20.53.34-client.txt)

**Comment by Scapulaunit12** [comment]
This was fixed in the latest version of rats [6.0.3](https://www.curseforge.com/minecraft/mc-mods/rats/files). It looks like you have 6.0.2.
