### ISSUE TITLE
Mod dies when on Forge 32.0.66

### ISSUE THREAD

**Issue by seymourimadeit** [Alex-the-666/Rats#351]
when minecraft finishes loading, this mod creates an error, shown below.

https://cdn.discordapp.com/attachments/404671932072591380/732415597962330232/unknown.png

log here : 
https://pastebin.com/raw/zQsngapS

the reason seems to be that GetCollisonBoxesEvent was removed and this mod uses it in some type of way.

**Comment by Alex-the-666** [comment]
will be fixed in 6.0.4
