### ISSUE TITLE
When rats try open a Thaumatorium a dedicated server will crash

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Rats#36]
**I posted the following on thaumcraft but it's caused by rats**

6.1 beta 26 crashes dedicated server Forge 1.12.2 build 2838

Notes:
NPE when player tries to connect to the server, they said they used a warp crystal to go home from the end

crash report:
http://paste.ubuntu.com/p/XPBD6dbvz2/

fml server latest:
http://paste.ubuntu.com/p/2S76mQWVvt/

reference: https://github.com/Azanor/thaumcraft-beta/issues/1699

**Comment by kreezxil** [comment]
An easy fix and subsequently a mod enhancement would be provide a blacklist that rats would not be allowed to open.

**Comment by Alex-the-666** [comment]
This is mainly an issue with thaumcraft. No properly implemented call to `inventory.isEmpty()` should crash a server.

**Comment by kreezxil** [comment]
So can you add a blacklist feature so that we can blacklist the
thaumatorium then and other inventory mods.

**Comment by Alex-the-666** [comment]
yeah i'll look into it

**Comment by Alex-the-666** [comment]
added config

**Comment by kreezxil** [comment]
nice, while you're at it could it be possible to add another config that
could set a rat as hostile vs passive (default). Which would be
advantageous for when the mod is coupled with other mods whereby other mobs
or npcs are capable of targeting hostiles. Case in point, Toroquest, it has
village lords and guards. Since your rats spawn enough to remind people of
the plague, it would seem logical that citizens in this case village guards
would spend some time killing rats too.

**Comment by Alex-the-666** [comment]
hmm thats odd, rats are already defined as hostile mobs by default, hence why iron golems attack them. It seems that toroquest has probably whitelisted its own list of generic hostile vanilla mobs

**Comment by kreezxil** [comment]
interesting, I look into the Toroquest and see what is going on there. Btw, off topic, any eta on the new server fix for the Fossils and Archeology mod? I see that in the comments they said it was fixed but no eta on 8.0.2.

**Comment by Alex-the-666** [comment]
yeah were working on it

**Comment by kreezxil** [comment]
ok, cool.
