### ISSUE TITLE
Prugue needs nerf

### ISSUE THREAD

**Issue by BlueWither** [Alex-the-666/Rats#38]
It is too strong...

**Comment by DWX12** [comment]
I agree with this. Not only are the debuffs strong and long lasting, but players can hardly get away from plague rats due to their speed. I was on a horse and the rats were keeping up. They're too deadly for their default settings.

**Comment by Birgliss** [comment]
piggybacking off of this issue, is there any chance this could be solved with a couple of config options?

i would be happy with a "plague duration" and "spawn-rate" config, personally. 5 minutes is a *long* time to have plague on your first night.

**Comment by Alex-the-666** [comment]
plague changed in 3.0.0
