### ISSUE TITLE
Players seem to be unable to download or update modpacks because rats 1.12.2 seems to be gone from twitch/curseforge???

### ISSUE THREAD

**Issue by SirAron111** [Alex-the-666/Rats#394]
Players seem to be unable to download or update modpacks because rats 1.12.2 seems to be gone from twitch/curseforge???

![unknown](https://user-images.githubusercontent.com/39855956/90046322-99364380-dcd0-11ea-8fe9-44aa2963d14d.png)
![unknown2](https://user-images.githubusercontent.com/39855956/90046323-99ceda00-dcd0-11ea-9770-1a7057e4049c.png)

how can i fix this so palyers can play my pack again? it worked fine some days ago. 
I have this version in my modpack ( rats-3.2.13-1.12.2.jar ) but i cant even find rats anymore on the list

![Unbenannt3](https://user-images.githubusercontent.com/39855956/90046524-e2869300-dcd0-11ea-8240-c4ba1dde9d49.PNG)

**Comment by Alex-the-666** [comment]
Thats odd. the latest version should be available at https://www.curseforge.com/minecraft/mc-mods/rats/files/3028671 .

**Comment by SirAron111** [comment]
ye i see the file there, but i cant seem to use it. did you maybe upload it, it got denied or the like nad than had it reuploaded or fixed, i had the same issue once with a different mod and that was the reason. strange is i cant even find it in the app when i look for it only on the webpage.

**Comment by aaronhowser1** [comment]
Twitch was just broken for a couple days, try now
