### ISSUE TITLE
Unable to rejoin worlds

### ISSUE THREAD

**Issue by CosmicGlowsticks** [Alex-the-666/Rats#403]
Aside from one world, I am unable to join any worlds last joined/made before updating to 1.16. If I uninstall it, I can join them just fine. It gets stuck on the "Reading World Data" screen.
I can make a new world and join it just fine. 
I use 1.16 forge 32.0.108, as anything above instantly crashes for whatever reason.

**Comment by GizmoTheMoonPig** [comment]
gonna need a log or something. I cant do much with just this
