### ISSUE TITLE
Incompatibility with Enderite 

### ISSUE THREAD

**Issue by Inpaladin** [Alex-the-666/Rats#404]
Upon trying to load the game with the Enderite mod installed(https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge) I will receive the error "Rats (rats) has failed to load correctly" with no further information.  Version is latest 1.16.1 release.

**Comment by thelizardcode** [comment]
I am having the same issue, my log is posted below, it appears to have an issue with the bow specifically.

https://hastebin.com/sirisokiji.sql

**Comment by GizmoTheMoonPig** [comment]
according to https://github.com/Nic4Las/Minecraft-Enderite-Mod/issues/26, this shouldnt be a problem anymore
