### ISSUE TITLE
help with crash!!!

### ISSUE THREAD

**Issue by artzygal** [Alex-the-666/Rats#406]
this is the error log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.6-1.12.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/25/20 7:30 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Rats (rats)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id -8, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.github.alexthe666.rats.server.world.RatsWorldRegistry.register(RatsWorldRegistry.java:17)
	at com.github.alexthe666.rats.RatsMod.init(RatsMod.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1122921176 bytes (1070 MB) / 5033164800 bytes (4800 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 85 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                            | Signature                                |
	|:----- |:----------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft               | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCHI  | mcp                     | 9.42              | minecraft.jar                                     | None                                     |
	| LCHI  | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCHI  | forge                   | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCHI  | creativecoredummy       | 1.0.0             | minecraft.jar                                     | None                                     |
	| LCHI  | littletilescore         | 1.0.0             | minecraft.jar                                     | None                                     |
	| LCHI  | xaerominimap_core       | 1.12.2-1.0        | minecraft.jar                                     | None                                     |
	| LCHI  | advancedcombat          | 1.1.2             | advancedcombat-1.1.2-[1.12].jar                   | None                                     |
	| LCHI  | aquaculture             | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                      | None                                     |
	| LCHI  | architecturecraft       | @VERSION@         | ArchitectureCraft-ElytraDev-Mod-1.12.2.jar        | None                                     |
	| LCHI  | baubles                 | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCHI  | atum                    | 2.0.17            | Atum-1.12.2-2.0.17.jar                            | None                                     |
	| LCHI  | autoreglib              | 1.3-32            | AutoRegLib-1.3-32 (1).jar                         | None                                     |
	| LCHI  | bno                     | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                | None                                     |
	| LCHI  | bibliocraft             | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCHI  | biomesoplenty           | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar     | None                                     |
	| LCHI  | bloodmoon               | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                      | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHI  | bonsaitrees             | 1.1.4             | bonsaitrees-1.1.4-b170.jar                        | None                                     |
	| LCHI  | bookshelf               | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHI  | jei                     | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                         | None                                     |
	| LCHI  | botania                 | r1.10-361         | Botania+r1.10-361.jar                             | None                                     |
	| LCHI  | carryon                 | 1.12.1            | CarryOn MC1.12.2 v1.12.1.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHI  | chameleon               | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHI  | chickens                | 6.0.4             | chickens-6.0.4 (2).jar                            | None                                     |
	| LCHI  | chineseworkshop         | 1.2.6             | ChineseWorkshop-1.12.2_1.2.6.jar                  | None                                     |
	| LCHI  | ctm                     | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
	| LCHI  | chisel                  | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44 (1).jar                  | None                                     |
	| LCHI  | chiselsandbits          | 14.33             | chiselsandbits-14.33 (1).jar                      | None                                     |
	| LCHI  | chococraft              | 0.9.8.0           | chococraft_1.12.2-0.9.8.0.jar                     | None                                     |
	| LCHI  | comforts                | 1.4.1.3           | comforts-1.12.2-1.4.1.3.jar                       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHI  | cookingforblockheads    | 6.5.0             | CookingForBlockheads_1.12.2-6.5.0.jar             | None                                     |
	| LCHI  | opframe                 | 1.4.0             | OnlinePicFrame_v1.4.40_mc1.12.2.jar               | None                                     |
	| LCHI  | creativecore            | 1.10.0            | CreativeCore_v1.10.16_mc1.12.2.jar                | None                                     |
	| LCHI  | cucumber                | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LCHI  | customcraftingtables    | 1.0.0             | customcraftingtables-1.0.2-1.12.2.jar             | None                                     |
	| LCHI  | customspawner           | 3.11.4            | CustomMobSpawner-3.11.4.jar                       | None                                     |
	| LCHI  | cxlibrary               | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
	| LCHI  | ptrmodellib             | 1.0.4             | PTRLib-1.0.4.jar                                  | None                                     |
	| LCHI  | props                   | 2.6.3             | Decocraft-2.6.3_1.12.2 (1).jar                    | None                                     |
	| LCHI  | mocreatures             | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar               | None                                     |
	| LCHI  | golems                  | 7.1.8             | Extra-Golems-Mod-1.12.2.jar                       | None                                     |
	| LCHI  | fairylights             | 2.1.6             | fairylights-2.1.6-1.12.2.jar                      | None                                     |
	| LCHI  | familiarfauna           | 1.0.11            | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LCHI  | ferdinandsflowers       | 1.10.4.1          | Ferdinand's+Flowers-1.12.x-1.10.4.1.jar           | None                                     |
	| LCHI  | flatcoloredblocks       | mc1.12-6.8        | flatcoloredblocks-mc1.12-6.8.jar                  | None                                     |
	| LCHI  | flying_things           | 1.5.2             | flying_things-1.5.2-1.12.jar                      | None                                     |
	| LCHI  | forgeendertech          | 1.12.2-4.5.3.0    | ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar      | None                                     |
	| LCHI  | cfm                     | 6.3.1             | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LCHI  | gravestone              | 1.3.1             | GraveStone-1.12.2-Graves-1.3.1.jar                | None                                     |
	| LCHI  | gravestone-extended     | 1.3.5.1           | GraveStone-1.12.2-Extended-1.3.5.1.jar            | None                                     |
	| LCHI  | waila                   | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
	| LCHI  | llibrary                | 1.7.19            | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHI  | iceandfire              | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                       | None                                     |
	| LCHI  | ironchest               | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHI  | jeid                    | 1.0.3-48          | JustEnoughIDs-1.0.3-48.jar                        | None                                     |
	| LCHI  | littletiles             | 1.5.0             | LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar         | None                                     |
	| LCHI  | maidensmaterials        | 3.3               | Maiden's+Marvelous+Materials-3.3.jar              | None                                     |
	| LCHI  | moarmors                | 1.0.0             | Mo'Armors+V.1.6+[1.12.2].jar                      | None                                     |
	| LCHI  | mopickaxes              | 10.0: Final BETA  | Mo-Pickaxes-Mod-1.12.2.jar                        | None                                     |
	| LCHI  | morechickens            | 3.1.0             | morechickens-1.12.2-3.1.0 (1).jar                 | None                                     |
	| LCHI  | morefurnaces            | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
	| LCHI  | outfox                  | 0.1.4             | outfox-0.1.4-mc1.12.2.jar                         | None                                     |
	| LCHI  | patchouli               | 1.0-20            | Patchouli-1.0-20.jar                              | None                                     |
	| LCHI  | pattysmorestuff         | @VERSION@         | PattysMoreStuff-stable-1.1.8.jar                  | None                                     |
	| LCHI  | placeableitems          | 3.3               | placeableitems-3.3.jar                            | None                                     |
	| LCHE  | rats                    | 3.2.14            | rats-3.2.14-1.12.2.jar                            | None                                     |
	| LCH   | signpost                | 1.08.3            | signpost-1.12.2-1.08.3.jar                        | None                                     |
	| LCH   | storagedrawers          | 1.12.2-5.4.0      | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
	| LCH   | unlimitedchiselworks    | 0.3.4             | UnlimitedChiselWorks-0.3.4.jar                    | None                                     |
	| LCH   | storagedrawersunlimited | 1.12.2-1.3.0      | StorageDrawersUnlimited-1.12.2-1.3.0.jar          | None                                     |
	| LCH   | tinymobfarm             | 1.0.5             | TinyMobFarm-1.12.2-1.0.5.jar                      | None                                     |
	| LCH   | travellersbackpack      | 1.0.22.22         | TravellersBackpack-1.12.2-1.0.22.22.jar           | None                                     |
	| LCH   | treechopper             | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                      | None                                     |
	| LCH   | twilightforest          | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal (2).jar | None                                     |
	| LCH   | ultimate_unicorn_mod    | 1.5.16            | ultimate_unicorn_mod-1.12.2-1.5.16.jar            | None                                     |
	| LCH   | wallpapercraft          | 1.0.1-alpha       | wallpapercraft_1.12.2-1.0.2-beta.jar              | None                                     |
	| LCH   | waystones               | 4.1.0             | Waystones_1.12.2-4.1.0.jar                        | None                                     |
	| LCH   | wings                   | 1.1.6             | wings-1.1.6-1.12.2.jar                            | None                                     |
	| LCH   | bauble_wings            | 1.0.0             | wings-1.1.6-1.12.2.jar                            | None                                     |
	| LCH   | wolfarmor               | 3.4.1.1           | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar     | None                                     |
	| LCH   | xaerominimap            | 20.3.0            | Xaeros_Minimap_20.3.0_Forge_1.12.jar              | None                                     |
	| LCH   | betteranimalsplus       | 9.0.1             | betteranimalsplus-1.12.2-9.0.1.jar                | None                                     |
	| LCH   | mysticallib             | 1.12.2-1.3.1      | mysticallib-1.12.2-1.3.1.jar                      | None                                     |
	| UD    | mowzies_wings           | 1.0.0             | wings-1.1.6-1.12.2.jar                            | None                                     |
	| UD    | mobends_wings           | 1.0.0             | wings-1.1.6-1.12.2.jar                            | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
CorePlugin (ForgeEndertech-1.12.2-4.5.3.0-build.0528.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  
LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.5063' Renderer: 'Intel(R) HD Graphics 5500'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.5063
	OpenGlRenderer: Intel(R) HD Graphics 5500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by GizmoTheMoonPig** [comment]
dimensions are no longer numerical IDs in 1.16 onwards, rather, they use actual namespaces (such as rats:ratlantis) so this will no longer be an issue and will never again be an issue in any modern version
