### ISSUE TITLE
Rat deleting contents

### ISSUE THREAD

**Issue by Rithenar** [Alex-the-666/Rats#407]
I gave a Block Placer upgrade to rat and set the home place to a grass block where I wanted logs to be placed. The rat had a chest as a point to take the logs from. First it didn't work, but when I reset the action to Harvest it started taking the blocks from the chest and placing, however it never stopped. It kept placing all the logs until the whole stack was gone, but since there is a block where the rat was trying to place the next blocks they just disappeared.

Using Rats 5.3.2
Forge 31.2.36
MC 1.15

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
