### ISSUE TITLE
Dragon Rats Rampage

### ISSUE THREAD

**Issue by Raycoms** [Alex-the-666/Rats#409]
Hi,

By chance I play on a server with a bunch of people where one of them created a bunch of those dragon rats. Now, those then ended up rampaging all over the world setting everything on fire.

Now, one could think that with a OP vanilla bow you could handle them. But with the amount of armour and health they had I would've needed 50 arrows per rat to take them down. Which ended up requiring an admin to run repeated kill commands to take of the rats.

It would probably be wise to scale back their armour significantly to allow other players to handle them. The fire they spread is bad enough already...

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e. Fire shouldnt spread nearly as far, but if its still an issue theres now a config option to disable placing fire blocks completely
