### ISSUE TITLE
Issue with Rats 3.2.14 for 1.12

### ISSUE THREAD

**Issue by Arantima** [Alex-the-666/Rats#412]
[crash-2020-08-31_14.56.29-server.txt](https://github.com/Alex-the-666/Rats/files/5152497/crash-2020-08-31_14.56.29-server.txt)

I am not the best at figuring out exactly what is going on here.. but I do know that it seems to be primarily mentioning that it is one of the Rats that is causing this error. I can still load the world. but if I even move All of my rats freeze and suddenly I cant do anything but it only happens if I move.

Full crash report posted below incase its easier for you to look at here. But also provided above.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  AALoadingPlugin (arcanearchives-0.2.0.22-mixins7.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.10.26.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/31/20 2:56 PM
Description: Checking entity block collision

java.lang.OutOfMemoryError: Java heap space

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:969)

-- Entity being checked for collision --
Details:
	Entity Type: rats:rat (com.github.alexthe666.rats.server.entity.EntityRat)
	Entity ID: 366
	Entity Name: Rat
	Entity's Exact location: -8234778850037189600.00, 44.92, -112.96
	Entity's Block location: World: (2147483647,44,-113), Chunk: (at 15,2,15 in 134217727,-8; contains blocks 2147483632,0,-128 to 2147483647,255,-113), Region: (4194303,-1; contains chunks 134217696,-32 to 134217727,-1, blocks 2147483136,0,-512 to 2147483647,255,-1)
	Entity's Momentum: -8234778850037189600.00, -0.08, 0.09
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:969)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at com.github.alexthe666.rats.server.entity.EntityRat.func_191986_a(EntityRat.java:1851)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at com.github.alexthe666.rats.server.entity.EntityRat.func_70636_d(EntityRat.java:884)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: rats:rat (com.github.alexthe666.rats.server.entity.EntityRat)
	Entity ID: 366
	Entity Name: Rat
	Entity's Exact location: -8234778850037189600.00, 44.92, -112.96
	Entity's Block location: World: (2147483647,44,-113), Chunk: (at 15,2,15 in 134217727,-8; contains blocks 2147483632,0,-128 to 2147483647,255,-113), Region: (4194303,-1; contains chunks 134217696,-32 to 134217727,-1, blocks 2147483136,0,-512 to 2147483647,255,-1)
	Entity's Momentum: -8234778850037189600.00, -0.08, 0.09
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: Wavermoth
	All players: 1 total; [EntityPlayerMP['Arantima'/411, l='Wavermoth', x=178.98, y=64.00, z=-148.91]]
	Chunk stats: ServerChunkCache: 166524 Drop: 0
	Level seed: 1172000278
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (183,64,-131), Chunk: (at 7,4,13 in 11,-9; contains blocks 176,0,-144 to 191,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3227354 game time, 4784645 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 134530 (now: false), thunder time: 88076 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 86281712 bytes (82 MB) / 11274289152 bytes (10752 MB) up to 11274289152 bytes (10752 MB)
	JVM Flags: 10 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx10752M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 29, allocated: 11, tallocated: 64
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version              | Source                                           | Signature                                |
	|:------ |:---------------------- |:-------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2               | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                    | 9.42                 | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                    | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                  | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | smoothfontcore         | mc1.12.2-2.1.2       | minecraft.jar                                    | None                                     |
	| LCHIJA | smoothfont             | mc1.12.2-2.1.2       | SmoothFont-mc1.12.2-2.1.2.jar                    | None                                     |
	| LCHIJA | akashictome            | 1.2-12               | AkashicTome-1.2-12.jar                           | None                                     |
	| LCHIJA | antiqueatlas           | 4.6.3                | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | antiqueatlasoverlay    | 1.2                  | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | applecore              | 3.4.0                | AppleCore-mc1.12.2-3.4.0.jar                     | None                                     |
	| LCHIJA | jei                    | 4.15.0.296           | jei_1.12.2-4.15.0.296.jar                        | None                                     |
	| LCHIJA | appleskin              | 1.0.14               | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCHIJA | baubles                | 1.5.2                | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | gbook_snapshot         | 2.9.1.s5             | Guidebook-1.12.2-2.9.1.s5.jar                    | None                                     |
	| LCHIJA | thaumcraft             | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
	| LCHIJA | arcanearchives         | 0.2.0.22-mixins7     | arcanearchives-0.2.0.22-mixins7.jar              | None                                     |
	| LCHIJA | astralsorcery          | 1.10.26              | astralsorcery-1.12.2-1.10.26.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | autoreglib             | 1.3-32               | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCHIJA | betteradvancements     | 0.1.0.77             | BetterAdvancements-1.12.2-0.1.0.77.jar           | None                                     |
	| LCHIJA | betteranimals          | 5.3.0                | betteranimals-1.12.2-5.3.0.jar                   | None                                     |
	| LCHIJA | betterbedrock          | 5.1                  | BetterBedrock-1.12.2-5.1.11.jar                  | None                                     |
	| LCHIJA | forgelin               | 1.8.4                | Forgelin-1.8.4.jar                               | None                                     |
	| LCHIJA | betterfoliage          | 2.3.1                | BetterFoliage-MC1.12-2.3.1.jar                   | None                                     |
	| LCHIJA | bonsaitrees            | 1.1.4                | bonsaitrees-1.1.4-b170.jar                       | None                                     |
	| LCHIJA | botania                | r1.10-363            | Botania r1.10-363.jar                            | None                                     |
	| LCHIJA | carryon                | 1.12.3               | carryon-1.12.2-1.12.3.15.jar                     | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chattweaks             | 5.1.25               | ChatTweaks_1.12.2-5.1.25.jar                     | None                                     |
	| LCHIJA | chickens               | 6.1.0                | chickens-6.1.0.jar                               | None                                     |
	| LCHIJA | ctm                    | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCHIJA | chisel                 | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
	| LCHIJA | chunkanimator          | 1.2                  | ChunkAnimator-MC1.12-1.2.jar                     | None                                     |
	| LCHIJA | mantle                 | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | twilightforest         | 3.11.1020            | twilightforest-1.12.2-3.11.1020-universal[1].jar | None                                     |
	| LCHIJA | tconstruct             | 1.12.2-2.13.0.183    | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LCHIJA | conarm                 | 1.2.5.9              | conarm-1.12.2-1.2.5.9.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | controlling            | 3.0.10               | Controlling-3.0.10.jar                           | None                                     |
	| LCHIJA | cosmeticarmorreworked  | 1.12.2-v5a           | CosmeticArmorReworked-1.12.2-v5a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | craftingtweaks         | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                  | None                                     |
	| LCHIJA | ding                   | 1.0.2                | Ding-1.12.2-1.0.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | display                | 1.2.4                | Display-1.2.4.jar                                | None                                     |
	| LCHIJA | dynamictrees           | 1.12.2-0.9.8         | DynamicTrees-1.12.2-0.9.8.jar                    | None                                     |
	| LCHIJA | harvestcraft           | 1.12.2zb             | Pam's HarvestCraft 1.12.2zg.jar                  | None                                     |
	| LCHIJA | dynamictreesphc        | 1.12.2-1.4.2         | DynamicTreesPHC-1.12.2-1.4.2.jar                 | None                                     |
	| LCHIJA | rustic                 | 1.1.5                | rustic-1.1.5.jar                                 | None                                     |
	| LCHIJA | dynamictreestc         | 1.12.2-1.4.1e        | DynamicTreesTC-1.12.2-1.4.1e.jar                 | None                                     |
	| LCHIJA | dynamictreestconstruct | 1.12.2-1.2.0         | dynamictreesTConstruct-1.12.2-1.2.0.jar          | None                                     |
	| LCHIJA | dynamictreesttf        | 1.12.2-1.1.4         | dynamictreesTheTwilightForest-1.12.2-1.1.4.jar   | None                                     |
	| LCHIJA | waila                  | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | llibrary               | 1.7.19               | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire             | 1.9.1                | iceandfire-1.9.1-1.12.2.jar                      | None                                     |
	| LCHIJA | inventorytweaks        | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | morechickens           | 3.2.0                | morechickens-1.12.2-3.2.0.jar                    | None                                     |
	| LCHIJA | moreoverlays           | 1.15.1               | moreoverlays-1.15.1-mc1.12.2.jar                 | None                                     |
	| LCHIJA | mysticalwildlife       | 1.3.0.1              | mysticalwildlife-1.12.2-1.3.0.1.jar              | None                                     |
	| LCHIJA | newwalls               | 1.0.0                | NewWalls-1.12.2-1.0.0.jar                        | None                                     |
	| LCHIJA | patchouli              | 1.0-21               | Patchouli-1.0-21.jar                             | None                                     |
	| LCHIJA | rats                   | 3.2.14               | rats-3.2.14-1.12.2.jar                           | None                                     |
	| LCHIJA | roost                  | 2.0.10               | roost-1.12.2-2.0.10.jar                          | None                                     |
	| LCHIJA | soundfilters           | 0.12.1_for_1.12      | SoundFilters-0.12.1_for_1.12.jar                 | None                                     |
	| LCHIJA | spiceoflife            | 1.3.12               | SpiceOfLife-mc1.12-1.3.12.jar                    | None                                     |
	| LCHIJA | tcinventoryscan        | 2.0.10               | ThaumicInventoryScanning_1.12.2-2.0.10.jar       | None                                     |
	| LCHIJA | thaumicjei             | 1.6.0                | ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
	| LCHIJA | thaumicwaila           | 1.12.2-0.0.2         | ThaumicWaila-1.12.2-0.0.2.jar                    | None                                     |
	| LCHIJA | tombstone              | 4.0.0                | tombstone-4.0.0-1.12.2.jar                       | None                                     |
	| LCHIJA | twitchintegration      | 4.1.16               | TwitchIntegration_1.12.2-4.1.16.jar              | None                                     |
	| LCHIJA | wailaharvestability    | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| LCHIJA | waterstrainer          | 3.2.0                | WaterStrainer-1.12-3.2.0.jar                     | None                                     |
	| LCHIJA | wawla                  | 2.6.275              | Wawla-1.12.2-2.6.275.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | betteranimalsplus      | 9.0.1                | betteranimalsplus-1.12.2-9.0.1.jar               | None                                     |
	| LCHIJA | mysticallib            | 1.12.2-1.9.0         | mysticallib-1.12.2-1.9.0.jar                     | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AALoadingPlugin (arcanearchives-0.2.0.22-mixins7.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
  bre.smoothfont.asm.Transformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.10.26.jar)
  
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Arantima'/411, l='Wavermoth', x=178.98, y=64.00, z=-148.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.19 Medium.zip
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce RTX 2060 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e. I wasnt able to reproduce so I assume its fine now
