### ISSUE TITLE
Rats not dropping held items with durability correctly (Rats 5.3.2 for 1.15.2)

### ISSUE THREAD

**Issue by TehTemmie** [Alex-the-666/Rats#415]
When killing a tamed rat that is holding an item with durability (such as weapons, tools, shields, and armor), the rat drops its held item with a random durability instead of what the item had before the rat was killed. This applies to all slots in a rat's inventory (Hats, Upgrades, and Hand).

**Comment by AlexModGuy** [comment]
fixed
