### ISSUE TITLE
Ratlantis Bow not working correctly/"as advertised" (Rats 5.3.2 for 1.15.2)

### ISSUE THREAD

**Issue by TehTemmie** [Alex-the-666/Rats#416]
The description of the Ratlantis Bow says that it "Fires stronger arrows twice as fast". However, it does not seem to live up to either claim, as will be described below:
1) The Ratlantis Bow does not deal more damage than a normal bow. I have tested by shooting two creepers with extremely high health 30 times each, one with a Ratlantis Bow, and one with a normal bow. The Ratlantis Bow dealt 246 damage, while the normal bow dealt 254 damage, for an average damage per arrow of 8.2 and 8.467 respectively. Using the `/data get` command on the arrows fired from these two bows reveals that both arrows have the same damage value. I believe this is due to the use of `copyDataFromOld()` in the code for the Ratlantis Bow, which copies the damage of the original arrow to the damage of the Ratlantis Arrow, defeating the point of setting it to 4 when initializing it.

2) I am assuming that "twice as fast" means that the arrows either have twice the velocity of normal arrows or the Ratlantis Bow can be fully drawn in only half the time required to fully draw a normal bow. The Ratlantis Bow cannot be shooting arrows that travel twice as fast as arrows from a normal bow since that would result in it dealing approximately twice as much damage, which is not the case, as demonstrated above. Also, arrows shot from a Ratlantis Bow fall approximately the same distance as regular arrows, tested at a range of 40 blocks. However, the Ratlantis Bow does not seem to be fully charged twice as quickly as a normal bow. A normal bow takes 1 second to fully charge, therefore it would be expected that it only takes 0.5 seconds to fully charge a Ratlantis Bow. However, using a macro to charge a Ratlantis Bow for exactly 0.5 seconds does not fully charge it, and arrows fired from it have the same trajectory as arrows fired from a normal bow. 

I have not tested the damage, draw speed, or arrow velocity of a Ratlantis Bow in other versions, but I suspect that this bug exists in the 1.16 versions as well since the Ratlantis Bow has the same code in those versions.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
