### ISSUE TITLE
Rats not healing properly when eating food (Rats 5.3.2 for 1.15.2)

### ISSUE THREAD

**Issue by TehTemmie** [Alex-the-666/Rats#417]
When a rat has a single food item in its hand and eats it, it heals by 1 HP instead of the hunger value of the food. I believe this is because the food item check happens after the food is consumed (specifically `this.getHeldItem(Hand.MAIN_HAND).shrink(1);`), which is why it only occurs when there's only one item left.

I have not tested this bug in other versions, but I believe it still exists in the 1.16 versions due to the rat's eating/healing code being the same in those versions.

**Comment by GizmoTheMoonPig** [comment]
was fixed in PR linked above
