### ISSUE TITLE
[1.15.2] Rats stop carrying out commands

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Rats#418]
I'm using the 5.3.2 version of the mod. 
My rats with the farmer/planter upgrade completely stops harvesting vanilla wheat after they're done, and won't harvest more after the wheat grows back. They only continue if I remove the upgrade, put it back, and command them to do it again. If I restart again they'll immediately start harvesting the mature crops. This also happens with the 'gather items' command, they'll gather some things then stop or just hold on to the items forever.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
