### ISSUE TITLE
Rat Dragon griefing can't be disabled

### ISSUE THREAD

**Issue by oakenmoon** [Alex-the-666/Rats#422]
As far as I know, the world fire from the Dragon rat upgrade can't be disabled. It doesn't obey the dragon griefing disable in the Ice and Fire config, and I saw no option in the Rats config to disable it. 
Using Rats 3.2.14 for 1.12.2.

**Comment by BabblingFishes** [comment]
This is also true in Rats 7.1.1 for 1.16.5, but from what I can tell it doesn't always occur?

Steps to recreate:
1. Make a multiplayer server, disable mobGriefing.
2. Go to a forest or other particularly flammable area.
3. Have a dragon rat set to "Hunt Monsters". (I put the rat on my head to keep better track of it.)
4. Spawn in some zombies.
5. While fire particles are still mid-air, turn off the server.
6. Turn the server back on.
7. Observe multiple fires along the path of fire particles.

One unattended dragon rat has set so much of my server on fire that I have to reset it.

**Comment by GizmoTheMoonPig** [comment]
see #409
