### ISSUE TITLE
[1.16.1] Crash When miner is set to harvest

### ISSUE THREAD

**Issue by ChakaMoonga** [Alex-the-666/Rats#425]
Hello I was wondering if there will be any plans on fixing any issues with crashes, when it comes to setting your rats to harvest. Every time I am to make a miner rat, the game would crash when trying to pathfind the ores. Since I’m running this mod on a dedicated server I would love to update the mod for the server with a potential fix. If it means anything I’m running “limitless 3”  mod pack. I absolutely love this mod and enjoy all of its fun I can’t wait for your response, thank you so much for your time.

**Comment by GizmoTheMoonPig** [comment]
fixed already, see above
