### ISSUE TITLE
Rats wont attack/defend on my Server (1.15.2)

### ISSUE THREAD

**Issue by Sanyel2000** [Alex-the-666/Rats#427]
on my Server my Rats wont attack other mobs or passive creatures, wont defend me, and dont wander around when set on wander. But they still attack other players when I hit someone. I tried it in Singleplayer and everything worked. I got no idea what could be wrong :/ the mods cant be it if it works in Singleplayer
I figured out that with the Dragon upgrade, the rat attacks now, but all other rats wth or without upgrade still dont attack
When my rat is on "hunt monsters" she moves but only slow, like every second 1 move

**Comment by TheMilso** [comment]
Same issue on1.16.4 server running rats 7.0.4
Test in single player works fine. Rebooted server made no difference.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
