### ISSUE TITLE
Rats russian translation start 

### ISSUE THREAD

**Issue by ManedMorph0reload** [Alex-the-666/Rats#428]
I translated the mod using deepl.com
this could be the beginning of translation work
[ru.zip](https://github.com/Alex-the-666/Rats/files/5291013/ru.zip)

**Comment by ManedMorph0reload** [comment]
updated and now must work
[ru_ru.zip](https://github.com/Alex-the-666/Rats/files/5291761/ru_ru.zip)

**Comment by ghost** [comment]
Что ты там понаделал?! Разработчик не бери от него перевод.

**Comment by ManedMorph0reload** [comment]
@DrHesperus читать умеешь?
я "понаделал" машинный перевод.
пишу же, что это автоматический перевод нейросетевого-переводчика.
основа для работы над переводом.

**Comment by ManedMorph0reload** [comment]
@DrHesperus так как бы удобнее работать.
собственно, раз такой умный ты его и делай, модовестник.

**Comment by ManedMorph0reload** [comment]
@DrHesperus если есть желание, подключайся.
у тебя там паблос какой-то можешь там тоже кого-то позвать, переделаете машинный перевод в нормальный.
для этого даже переводчиком быть не нужно.

**Comment by ManedMorph0reload** [comment]
@DrHesperus я просто решила начать хоть какую-то работу над переводом, сделать машинный перевод.
еще я автозаменой "Рат" заменила на "Крыс" Крыслантис соотвественно.
Ратлантис можно переделать в Крыслантиду, если нормально адаптировать.

короче, есть над чем работать.
призываю работать над переводом вместо того чтоб недоумевать

**Comment by ManedMorph0reload** [comment]
@DrHesperus вижу ты как раз переводы и собрался делать
можешь заняться.
![изображение](https://user-images.githubusercontent.com/62159012/94504504-9906ee80-0211-11eb-84e2-a5758eb8ac8f.png)
![изображение](https://user-images.githubusercontent.com/62159012/94504599-d8353f80-0211-11eb-96e7-ef412fc181ae.png)
![изображение](https://user-images.githubusercontent.com/62159012/94504651-f307b400-0211-11eb-9d03-6c87379908f3.png)
и дальше построчно сверяешь всю непонятную хрень и ошибки.
там номера строчек идентичны.

**Comment by ghost** [comment]
Не трогай ничего, там и так нормально, я посмотрел архив, там хаос.

**Comment by ManedMorph0reload** [comment]
@DrHesperus 
где хаос? что нормально?
о чём ты?

ты перевод делать собираешься?

**Comment by ghost** [comment]
Проверь сообщение в вк и закрой здесь Проблему.
