### ISSUE TITLE
Rats with wings hover while standing still.

### ISSUE THREAD

**Issue by Scapulaunit12** [Alex-the-666/Rats#434]
If you set a rat with the wing upgrade to wander and then set it too stay here it will not stay still and hover while moving.

![ratglitch4](https://user-images.githubusercontent.com/56084328/95148868-749b9c80-0752-11eb-8bb9-607099102156.gif)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
