### ISSUE TITLE
Compatibility issues with Biomes O'Plenty for 1.16.3

### ISSUE THREAD

**Issue by Mysteriaa** [Alex-the-666/Rats#435]
Edit: Pressed enter by accident without adding any text here. Oops.

When I try to rejoin a world with the Rats/Ratlantis mod and BoP installed, it fails to load the save. Both occur in 1.16.3. I believe this is the culprit.
![image](https://user-images.githubusercontent.com/67705660/95223123-38eeea00-07c7-11eb-8307-7020197cb630.png)

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
