### ISSUE TITLE
Rats Relocate to inside of blocks when releasing off of shoulder

### ISSUE THREAD

**Issue by BlueDuckYT** [Alex-the-666/Rats#436]
When in an enclosed space and releasing a rat from shoulder/head, they will spawn in a block and suffocate to death.

**Comment by BlueDuckYT** [comment]
Forgot to mention, latest 1.15.2 version

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
