### ISSUE TITLE
Quarry rats get stuck under stair and are unable to deposit resources.

### ISSUE THREAD

**Issue by Scapulaunit12** [Alex-the-666/Rats#441]
Title
![ratglitch5](https://user-images.githubusercontent.com/56084328/95694788-d4d28880-0c01-11eb-8b5e-d72e213c57dd.gif)

**Comment by coolhead34** [comment]
did u ever find a fix because im tired of picking them up and bringing them and i cant use the miners bc they crash my game when at stone level so i can only use the qurray

**Comment by GizmoTheMoonPig** [comment]
rats dont use stairs anymore in the quarry, they make "quarry platforms" which they can jump through. Update the mod
