### ISSUE TITLE
1.16.3 Confit Byaldi

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Rats#442]
Hey, maybe you add inf config dissable Confit Byaldi? Or add ability to balance in configuration, because is very cheat, and very easy craft, i can kill dragon 5 lvl, hydra and all bosses from RATS mod almost unarmoured, i mean Confit Byaldi very cheat, 2 min Immortality, very easy craft. Golden apples are heavier to craft, but they are several times weaker.

**Comment by GizmoTheMoonPig** [comment]
i'll be balancing the special foods in 1.19. Leaving this open as I havent yet and I dont want to forget

**Comment by GizmoTheMoonPig** [comment]
Added in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
