### ISSUE TITLE
Ratlantis is empty in MC Eternal

### ISSUE THREAD

**Issue by shaye1444** [Alex-the-666/Rats#443]
There is nothing in Ratlantis in MC eternal. No mobs at all.

**Comment by jayschuster** [comment]
That's an MC eternal issue not a rats issue

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
