### ISSUE TITLE
Ratlantis addon doesnt work

### ISSUE THREAD

**Issue by Gunnarmeloenar** [Alex-the-666/Rats#444]
When I load up my game with the ratlantis addon, it works fine.
But when I load up a world, I get this message: Errors in currently selected datapacks prevented world from loading. You can either try to load only with vanilla datapack ("safe mode") or go back to title screen and fix it manually. I do not know how to fix it and I disabled ratlantis. i think this has to be fixed in an update.

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
