### ISSUE TITLE
there are no houses with plague doctors and zookeepers 1.14.4

### ISSUE THREAD

**Issue by Gamma1hell** [Alex-the-666/Rats#445]
![2020-10-18_18 07 39](https://user-images.githubusercontent.com/73063098/96366996-fafda880-116c-11eb-9b2e-5cd065786651.png)
![2020-10-18_18 08 43](https://user-images.githubusercontent.com/73063098/96366997-fb963f00-116c-11eb-836b-0a2e06b47aea.png)

**Comment by AlexModGuy** [comment]
intedned
