### ISSUE TITLE
Chunk gen errors?

### ISSUE THREAD

**Issue by Rocksnotch** [Alex-the-666/Rats#449]
Running a 7 gig dedicated server and the console keeps spouting out this message:

[FML]: Rats loaded a new chunk [215, -19] in dimension -8 (Ratlantis) while populating chunk [216, -18], causing cascading worldgen lag.

No idea how to fix it

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
