### ISSUE TITLE
Rats crashes on new 1.16.3 forge versions

### ISSUE THREAD

**Issue by BedrockLegends** [Alex-the-666/Rats#453]
As the title shows

**Comment by diesieben07** [comment]
This is caused by this line: https://github.com/Alex-the-666/Rats/blob/f3d41648a00c6d51a75ca0d6b0a79a35906b0900/src/main/java/com/github/alexthe666/rats/server/CommonProxy.java#L169
Do not use the vanilla registries.

**Comment by BedrockLegends** [comment]
@diesieben07 where's the Line for this same error https://github.com/Alex-the-666/Ice_and_Fire/issues/3070

**Comment by diesieben07** [comment]
You didn't even post a debug.log there. Also, you should let the repository owner figure that out, I am sure they know best where their dodgy registration code is.

**Comment by AlexModGuy** [comment]
fixed
