### ISSUE TITLE
Crash at startup (1.12.2)

### ISSUE THREAD

**Issue by LocalBoomer** [Alex-the-666/Rats#454]
Crashes before launching game window, no crash report generated so I have attached the [**log**](https://pastebin.com/R3JqEvZ7).

lines 59 & 65 mention:
`[13:27:21] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/misc/RatsRuntimePatcher`
and line 70 says:
`[13:27:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher`

So I'm guessing it's one of the two. If it's LLibrary let me know and I'll post the issue there 😄 

Versions:
MC 1.12.2
Forge 14.23.5.2854
Rats 3.2.14

**Comment by GizmoTheMoonPig** [comment]
we dont have this class anymore, nor do we use LLibrary in modern versions so this is no longer a problem
