### ISSUE TITLE
Mining rats dont work

### ISSUE THREAD

**Issue by Ryukossei** [Alex-the-666/Rats#456]
**Bad Mining Rat broke my game lol!!!**

So I am not sure what is causing this or if this is linked to a bigger issue. First I will say I am running windows Java with minecraft 1.16.1. Everyone on the server is playing at the same as well. The crash only effects everyone when i try to join the server after the initial crash that happens. Everyone else can still play the game with no issues as long as i dont connect in.

When I set my rat to mine with the advanced mining upgrade, he will go off and about a few seconds later my game will crash. This has happened both on single player and server. I have tried on single to see what exactly it is that I was doing that would cause it to crash and it didnt matter what since it always happened after about the third block was mined. The first time (I was on server then) i had five ores set for it to mine: Coal, Iron, Silver, copper and Platnum. I had the actual ore block in the upgrade as the directions said to. The second time on SP I only had Coal and Iron set and it crashed out.

**Comment by AlexModGuy** [comment]
fixed
