### ISSUE TITLE
mining rat drowned minutes after being set to harvest with an advanced mining upgrade 

### ISSUE THREAD

**Issue by OmenMachine** [Alex-the-666/Rats#457]
so I don't honestly know if this is a bug or not, but it seems a little irritating if it is not. I set a basic rat to mine a select set of a few ores, it gathered about 8 blocks then ran up out of the mine and less than five minutes later the rat drowned. I couldn't find anything about this, and I don't know if it is intentional, but it seems like it breaks the functionality of mining rats.  minecraft version 1.16.3

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
