### ISSUE TITLE
rats cause lag

### ISSUE THREAD

**Issue by kreezxil** [Alex-the-666/Rats#46]
# details
**MC**: 1.12.2
**FORGE**: 14.23.5.2838
**MOD**: 1.2.0

## spark data visual
![image](https://user-images.githubusercontent.com/3880072/61176741-d55a1a80-a58b-11e9-9646-63a28fc2a393.png)

## spark data raw
https://sparkprofiler.github.io/#KgS2Y6VcOO

**Comment by Alex-the-666** [comment]
ratUpdateTick in rats.config

**Comment by kreezxil** [comment]
Rats still causing lots of lag, I'm still on version 1.2.0. I'll update and see if it fixes it. I did do the config like you suggested.

![image](https://user-images.githubusercontent.com/3880072/61883427-0ad20280-aec0-11e9-9156-2635ecd83dec.png)

https://sparkprofiler.github.io/#tQPvvG2Afv
