### ISSUE TITLE
Rats doesnt load correctly

### ISSUE THREAD

**Issue by Gunnarmeloenar** [Alex-the-666/Rats#460]
When I load up my modpack rats doesn't load and I do not know why. I put the crash file in this post. 
[crash-2020-11-08_12.34.30-fml.txt](https://github.com/Alex-the-666/Rats/files/5506254/crash-2020-11-08_12.34.30-fml.txt)

**Comment by GizmoTheMoonPig** [comment]
duplicate of #404
