### ISSUE TITLE
Plague Doctor Render Issue

### ISSUE THREAD

**Issue by Mey-Ha-Zah** [Alex-the-666/Rats#461]
I doubt this is the fault of your mod, but I am posting this so you know about it and others can see if they experience it.

The Plague Doctor, picks up items like any villager. However, during one of my modded playthrough, I broke a crate with some Curios in it, and when he picked them up, my game crashed.

>  ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 11/8/20 11:22 AM
> Description: Rendering entity in world
> 
> java.lang.ClassCastException: com.github.alexthe666.rats.client.model.ModelPlagueDoctor cannot be cast to net.minecraft.client.renderer.entity.model.BipedModel
> 	at artifacts.common.item.UmbrellaItem$ClientEvents.onLivingRender(UmbrellaItem.java:88) ~[?:1.16.1-2.5.2] {re:classloading}

Basically, he picked up an Umbrella and when it tried to render it couldn't, causing the game to crash. I know this isn't your fault, but I felt it would be a good idea to inform you of it.

**Comment by AlexModGuy** [comment]
> at artifacts.common.item.UmbrellaItem

caused by artifacts mod
