### ISSUE TITLE
Rats don't spawn in version 7.0.0 on 1.16.3

### ISSUE THREAD

**Issue by Tymogekh** [Alex-the-666/Rats#462]
Rats, plague rats and pied pipers don't spawn. In general rats are spawning but there are extremally rare (on garbage blocks too).
I tried to decrese number of rat spawning decreser in the config - no results. I have got other mods on this world, but I don't know which mods are incompatible with this mod. Important things: I installed mod after creating a world and I there aren't ratlantis added. Is that changing anything? To this message I'm attaching my rats mod config (compessed in the folder).
. I don't speak english very well, so sorry for mistakes.
[rats_mod_config.zip](https://github.com/Alex-the-666/Rats/files/5507203/rats_mod_config.zip)

Please answer or let me know what I need to describe.

**Comment by mosharky** [comment]
They're whitelisted to vanilla biomes. Try removing the whitelist

**Comment by Tymogekh** [comment]
I'm not using any biome-adding mods. They don't spawn in vanilla biomes. I tried to install ratlantis and then rats spawns, but still rare and only underground. Other strage thing is fact, so ratlantis config don't appered after opening and closing minecraft with mod (game, not launcher). Sorry for this long time waiting for my answer, but one guy on discord told me, so I must wait long time for anyone's answer.

**Comment by Tymogekh** [comment]
Anyways, when I added ratlantis and made server which this mod everything works well. I don't need help, but make sure, so new versions with seperate ratlantis don't works 100% well.
