### ISSUE TITLE
TC6 Integration Aspects Register After the Mod Construction Phase

### ISSUE THREAD

**Issue by EnderofGames** [Alex-the-666/Rats#463]
Rattus and Mythus aspects, although the latter may be from ice and fire. 

Minecraft 1.12.2 (may affect later)
Forge 14.23.5.2847
Rats 3.2.14 (first seen in 3.2.10)

I was setting up a Thaumic Additions vis pod farm. Vis pods for every aspect are there, but the seeds for Rattus and Mythus do not work. Contacted the Thaumic Additions mod author, and the response I got was essentially the title. 

Since they are not registered until after the Mod Construction phase, they break items. However, if you don't plan on using them for 1.12.2 (these aspects exist, but aren't really used for anything) might I suggest removing them altogether? 

Thanks!

**Comment by GizmoTheMoonPig** [comment]
since 1.12 is no longer supported and thaumcraft wont be updated anytime soon im closing this for now. Whenever the thaumcraft port finishes i'll look into reintroducing the aspect (only rattus was used in this mod) properly
