### ISSUE TITLE
Unintended Interaction with Botania/Cyclic

### ISSUE THREAD

**Issue by 4emili4** [Alex-the-666/Rats#466]
Left a rat to gather crops and deposit them into a chest that uses a cyclic item cable to pump the crop into a bioreactor. The rat grabbed a botania flower, deposited it into the chest and off it went. Except that the flower didn't despawn, it was still where he took it from and he went back and took it again. 

I stopped him finally because he ran out of the fence, **the flower was still where I planted it.** Took apart that cyclic cable set up to correct that problem and out popped 12 of that same botania flower. 

So the rat intended to pick up the flower, it kept respawning where it was supposed to be. The rat then did what he thought he was supposed to do and deposited the flower over and over. Not sure how to even suggest to approach this.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
