### ISSUE TITLE
Rats Auto Crafting does not work

### ISSUE THREAD

**Issue by ShyNieke** [Alex-the-666/Rats#470]
## Client Info
* Minecraft Version: 1.16.4

* Forge Version: 35.0.7
* Mod Version: 7.0.1
* Java Version: 1.8.0_252

## Issue Description
Rat auto crafting does not seem to function for me at all on Forgecraft, it does the animation, it looks like it is crafting but it never crafts the items

## Reproduce Steps
Make a rat auto crafting table
make a rat auto crafting upgrade
put rat on table with upgrade
set recipe in table
provide table with items
wait
No items is crafted

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e. Rat crafting table was completely overhauled so it should work fine now
