### ISSUE TITLE
[1.16.4] lumberjacks dont chop bamboo

### ISSUE THREAD

**Issue by 1kili2** [Alex-the-666/Rats#474]
Getting rats to chop down bamboo doesn't seem to work, i've tried most farming and block breaking upgrades and teh only one i was able to get rats to harvest some bamboo with is the advanced mining upgrade, but it seems to try and got for the top bit so if the bamboo i tall it doesn't work either.

it seems to me that this would fall under the lumberjack upgrade but the lumberjack doesnt seem to interact with bamboo at all

**Comment by GizmoTheMoonPig** [comment]
Considering bamboo isnt exactly wood and needs a sword, not an axe, to be chopped down, I dont think this fits the lumberjack upgrade. I'll think about it though

**Comment by GizmoTheMoonPig** [comment]
1.20 making bamboo a wood type complicates things quite a bit for my point here, but the sword thing still stands. I'll probably allow them to collect bamboo with the normal harvest crops goal at some point, but im not gonna integrate it into the lumberjack
