### ISSUE TITLE
Can't Land On the Moon and I Don't Have The Regular Moon

### ISSUE THREAD

**Issue by HappySlapper053** [Alex-the-666/Rats#476]
I'm in MCEternal and each time I try to land on the moon the rocket (using Advanced Rocketry) it gives me the prompt to begin touchdown but it doesn't decline in elevation and keeps me hovering above the land at about Y 1000. I also can't exit the rocket, nor can I see the rocket. The only two solutions I found were teleporting down using cheats and using /kill. This happened 3 separate times, all on a solo server to test the rocket for a friend's server. It also replaces the Advanced Rocketry Moon with the Rats moon, which I would like to replace.

**Comment by AlexModGuy** [comment]
there is no rats moon in this mod.
