### ISSUE TITLE
Does rats use biome dictionary? Could explain mob/rat shortages in worlds

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Rats#479]
Title, I was poking around the source code I noticed that there are hard coded biome values for mobspawning, and mobs in the game rarely spawn

**Comment by GizmoTheMoonPig** [comment]
rat spawning has been moved to biome modifiers in 1.19, meaning it will be a lot easier to choose where they spawn. Same goes for pipers and demon rats
