### ISSUE TITLE
Chicken Mounted Rats will "Fall From High Place" when player leaves the area

### ISSUE THREAD

**Issue by GenreShinobi** [Alex-the-666/Rats#482]
**Steps to Repro:**

1. Equip a Rat with the Chicken Mount Upgrade
2. Ask the Rat to Stay Here
3. Walk until you leave the rats despawn radius
4. Note that the chicken dies and the message is "Rat fell from high place"

**Description:** 
If I walk beyond the despawn radius of a mounted chicken rat. They will fall from a high place and die. If I leave the despawn radius through other means, such as portals or wayshrines. The chicken survives. None of my other rats (so far) are having this issue.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
