### ISSUE TITLE
[7.0.1-1.16.3]Milkmaid rat not milking.

### ISSUE THREAD

**Issue by Raderg** [Alex-the-666/Rats#483]
Once the container is full, ,the rat goes to grab the next bucket of milk but gets stuck following the cow even if the container has space.
Tried to remove the upgrade and give it again and setting the rat to wait and harvest again but it keeps just following the cow.

Tested with the curdling station and the basic tank from mekanism on All The Mods 6 Pack.

![2020-12-08_20 27 02](https://user-images.githubusercontent.com/30061643/101531727-f21e9b80-3993-11eb-9c65-3f8ba14d5cf4.png)
![2020-12-08_20 26 47](https://user-images.githubusercontent.com/30061643/101531733-f34fc880-3993-11eb-8aac-8a7bfbc02f4c.png)

**Comment by ianwijma** [comment]
Can confirm, once the fluid container is full, the rat stops millking.

![image](https://user-images.githubusercontent.com/17692119/103477708-6e7e9000-4e15-11eb-8765-499cc1986e79.png)

**Comment by ianwijma** [comment]
I have a workaround for this, if you have a mod that adds massive liquid storage, you can use that to keep the rat busy. Personally I used QuantumStorage's Quantum Tank, which once full will run for days (if not months) until its empty.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
