### ISSUE TITLE
Rats with replant upgrade don't replant inferium seeds

### ISSUE THREAD

**Issue by darthvader45** [Alex-the-666/Rats#484]
Using Rats 7.0.1 for 1.16.4 and mysticalagriculture 4.1.3 for 1.16.4.  Not sure if intended or not, but I'm pretty sure the rats should not break inferium plants when harvesting them if they have the replanter upgrade.

**Comment by Quadae** [comment]
They also don't replant Pams Harvest Craft Plants

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e

**Comment by darthvader45** [comment]
Thank you.
