### ISSUE TITLE
Screen Flashes Instead of Turning Orange When Eating Confit Byaldi

### ISSUE THREAD

**Issue by MCFISHERMANPRO** [Alex-the-666/Rats#490]
Minecraft version 1.12.2 on a server with Rats 3.12.13 in the MC Eternal modpack.
When eating Confit Byaldi instead of the orange effect that the wiki says I should get my screen begins to flash and the severity of the flashing gets worse when I open a menu or any inventory. 
I'm not sure if this is a conflict or a bug but I'm just looking for a solution so that I can use it without injuring my eyes.

**Comment by GizmoTheMoonPig** [comment]
I wasnt able to reproduce this, but I changed how the effect shader is applied to you a bit (works just like vanilla shaders do when you spectate an entity like a creeper) so this shouldnt happen anymore.
