### ISSUE TITLE
Demon rats over abundent in warped forest biomes [1.16.4]

### ISSUE THREAD

**Issue by CacZarn** [Alex-the-666/Rats#493]
Something is causing Demon rats to spawn at increased rates in warped forest biomes and is making them incredibly dangerous to traverse. Probably something about them being able to spawn in any biome and the warped forest having more chances for them to spawn because of its generally lower amount of mobs.

**Comment by GizmoTheMoonPig** [comment]
yeah, that would do it. Im gonna prevent them from spawning in the warped forest in 1.19, as it honestly doesnt make sense to find them there.
