### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by WenXin20** [Alex-the-666/Rats#495]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Rats v7.0.1`

The Ratlantis Ghost Pirat Door is missing the block and item tag `minecraft:doors` & `minecraft:wooden_doors`. This would allow the doors to be opened by villagers and be used in recipes. The trapdoor also has tags that can be used. The ratglove could use the `minecraft:small_flowers` tag, which allows bees to pollinate it.

Also, the Ratglove doesn't have a flower pot block yet.

**Comment by GizmoTheMoonPig** [comment]
all tags have been added in the upcoming 1.19 update, as well as a potted ratglove
