### ISSUE TITLE
[1.16.4] Ratlantis addon issue

### ISSUE THREAD

**Issue by SSKirillSS** [Alex-the-666/Rats#497]
Pirate projectile impact on the 1.16.4 server simply crashes it. Log: https://pastebin.com/JznfJKD4

Steps to reproduce:
1. Install Rats and Ratlantis
2. Summon pirate and let it shoot any entity on the server
3. Watch how server dies.

Versions:
rats-7.0.1-1.16.3
ratlantis-1.0.0-1.16.3
citadel-1.5.3

Similar issue: https://github.com/Mohist-Community/Mohist/issues/700

**Comment by AlexModGuy** [comment]
fxed
