### ISSUE TITLE
Picking up rats crashes players in the server

### ISSUE THREAD

**Issue by PhuaJunLe** [Alex-the-666/Rats#499]
The Rat had a battle god upgrade and had a rat king crown.
[crash-2020-12-26_04.24.07-client.txt](https://github.com/Alex-the-666/Rats/files/5742371/crash-2020-12-26_04.24.07-client.txt)

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e. Picking up rats worked just fine in singleplayer and multiplayer, regardless of upgrades for me
