### ISSUE TITLE
[1.16.4] Ratlantis, possible biome issue

### ISSUE THREAD

**Issue by Terpo** [Alex-the-666/Rats#501]
Today I had a crash generating chunks on my server. I already opened an issue on Serene Seasons end but I think it might be related to ratlantis directly, as I can't really find it in the biome dictionary:

https://github.com/Glitchfiend/SereneSeasons/issues/279

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
