### ISSUE TITLE
[1.16.4] Undead Rat crashes server when defending its owner

### ISSUE THREAD

**Issue by Magiwarriorx** [Alex-the-666/Rats#502]
Giving a rat an Undead upgrade inconsistently leads to a crash when the rat attempts to defend its owner from hostile mobs. I believe the hostile mob AI occasionally tries to change targets from a player its attacking to the last thing that damaged it, ultimately trying to target an Undead rat and leading to a crash.

Log here: https://pastebin.com/7TVx6UTQ

Steps to replicate: 
1. Install Rats and Ratlantis for 1.16.4
2. Tame a rat
3. Give the tamed rat the Undead upgrade
4. Set the rat to Hunt Monsters
5. Take damage from a hostile mob while near the Undead rat
6. Wait for the Undead rat to damage the hostile mob
7. Repeat steps 5 and 6 until crash

**Comment by GizmoTheMoonPig** [comment]
duplicate #389
