### ISSUE TITLE
[1.12.2] Animania bug with Rats[cheese making]

### ISSUE THREAD

**Issue by flowerbeauty2** [Alex-the-666/Rats#505]
That's a way to make cheese is that you can put milk into a cauldron and wait a few seconds.
However, if you put other milks such as goat milk , they will not consume and therefore you can have **unlimited cheeses**.

**Comment by GizmoTheMoonPig** [comment]
as animania hasnt left 1.12, im gonna close issues regarding it as done. 1.12 is no longer supported
