### ISSUE TITLE
Where is the expansive in-game config?

### ISSUE THREAD

**Issue by StygianEmperor** [Alex-the-666/Rats#509]
> For those who are no fun at parties, many of the mod's more "out there" features can be configured in the expansive in-game config.

I'm no fun at parties and want to turn off most of this mod's features other than the rats themselves and some of the plague stuff, but I'm probably also an idiot because I can't find so much as a reference to this config other than that one line on the mod's Curseforge description. Is it part of an item or something?

**Version:** rats-7.0.2-1.16.3

**Comment by AlexModGuy** [comment]
that refers to the ratlantis feature which was moved to a serperate mod
