### ISSUE TITLE
[1.16.4] Rats ticking entity crashes the server

### ISSUE THREAD

**Issue by SpycrabSXL** [Alex-the-666/Rats#513]
Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.pathfinding.IStuckHandlerEntity

Seems to be that random rats that spawn in the world can randomly get stuck and cause the server to crash due to a ticking entity
error.

[crash-2021-01-04_11.32.57-server.txt](https://github.com/Alex-the-666/Rats/files/5766084/crash-2021-01-04_11.32.57-server.txt)
https://pastebin.com/MTg9g7qh

**Comment by ninjabunny66** [comment]
I had a similar problem, but based on the location, I think it might be a tamed rat in this case.

https://pastebin.com/Ea8jGSwb
