### ISSUE TITLE
1.16.4 RatsCustomEvents crashing server

### ISSUE THREAD

**Issue by Rithenar** [Alex-the-666/Rats#514]
My server just crashed after receiving the same error repeatedly. Not sure what could be causing that or how to fix it. Please let me know if you have any ideas on how to fix it as my players are getting annoyed.

https://gist.github.com/Rithenar/0b7f873e652b9eb1851bec4511cbc19f

**Comment by MypowerHD** [comment]
You properly missing the Mod.

**Comment by Rithenar** [comment]
Sorry, what does that even mean?

**Comment by MypowerHD** [comment]
had the same issue, after updating ATM to 1.3.8.
The exception means that the class could not found, thinking he isnt loading the mod.

**Comment by ghost** [comment]
I'm getting this same crash playing the Direwolf20 1.16.4 pack (pack version 1.3.0)

https://pastebin.com/8S0MqJTA
