### ISSUE TITLE
Rat's wont work in many ways.

### ISSUE THREAD

**Issue by jakelavaclaw** [Alex-the-666/Rats#516]
Alright, I can't seem to get my rat to milk anything, or mine anything, or really do much at all. When I tried taming it, it ran away and hit a wall, then just started spinning for a few seconds and then when it stops it just is braindead. Just sitting there, wont run, not even if I hit it. When I tamed one in creative mode it wont do anything, it'll hunt animals and enemies, but it wont gather items or do any sort of harvesting of any kind.\.

**Comment by jakelavaclaw** [comment]
I was able to get harvesting and gathering to work by using the radius staff, still no luck on taming.

**Comment by englens** [comment]
Is this on a server, or singleplayer? I'm pretty sure its the same issue I was having, #515. 
If so, a temporary solution until it gets fixed is to just restart the server. If this is singleplayer, then closing and reopening the world should fix it (untested).

**Comment by scotty9090** [comment]
Having the same issue (agree it is #515.  In single player, closing and re-opening the world seems to fix it as well.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
