### ISSUE TITLE
Small Parsing Errors with ice&fire mod installed

### ISSUE THREAD

**Issue by Freebi85** [Alex-the-666/Rats#517]
Hey there :) Just wanted to point out 2 minor parsing errors with ice&fire mod.
Minecraft 1.16.4
Rats.: 7.0.3

[WARN] Failed to parse recipe 'rats:dragon_wing_iaf[minecraft:crafting_shaped]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item tag 'iceandfire:dragon_bone'

[WARN] Failed to parse recipe rats:dragon_wing_iaf[minecraft:crafting_shaped]: com.google.gson.JsonSyntaxException: Unknown item tag 'iceandfire:dragon_bone'

Cheers 🍺

**Comment by ehertlein** [comment]
Is this a duplicate of https://github.com/Alex-the-666/Rats/issues/512 ?

**Comment by Freebi85** [comment]
Yes looks like it's the same issue. My bad. Gonna close this. Cheers 🍺
