### ISSUE TITLE
Pet Shops and Plague Doctor Huts don't spawn in villages

### ISSUE THREAD

**Issue by iloverats** [Alex-the-666/Rats#518]
I kept making worlds and I didn't get any pet shops or plague doctors, I had some mods on so I checked if there was a conflict and deleted everything but citadel and rats, but it still didn't work. I checked my config and it has pet stores enabled, so idk what's going on. Great mod btw I love rats

**Comment by ykvox** [comment]
encountered same issue here

**Comment by celophys** [comment]
same

**Comment by GizmoTheMoonPig** [comment]
they were removed from the mod in 1.14, but dont worry, I will reintroduce them in 1.19
