### ISSUE TITLE
Crash with Cubic Chunks

### ISSUE THREAD

**Issue by BaccarWozat** [Alex-the-666/Rats#52]
Crash seems to be related to the new Ratlantis dimension. The mod works without [Cubic Chunks](https://www.curseforge.com/minecraft/mc-mods/opencubicchunks?gameCategorySlug=mc-mods&projectID=292243#c35) but once CC is added it crashes:

Crash report: https://pastebin.com/PJXq95KF

The CC modmaker says the problem is with the line at
https://github.com/Alex-the-666/Rats/commit/f7f3a8163523c99e3c2f6f0f3063c435d590fe79#diff-456e7aa54db0b535ebea6626642eee7dR98
and said line
`BlockPos skyPos = new BlockPos(x, world.getHeight(), z);`
should read
`world.getHeight(new BlockPos(x, 0, z))`

Feel free to discuss on the CC Discord at https://discord.gg/kMfWg9m

**Comment by BaccarWozat** [comment]
There is a workaround for now-- in the CC config, exclude the Ratlantis dimension (-8).

**Comment by Barteks2x** [comment]
Note: A workaround is adding the dimension to excluded list. This will change the world height back to 256, so the code won't take forever to iterate from the top of the world down.
