### ISSUE TITLE
[1.16.4] [Direwolf20 1.16] Portal to Ratlantis does not take you to Ratlantis, teleports a few blocks away into the sky instead.

### ISSUE THREAD

**Issue by DizzyDJW** [Alex-the-666/Rats#525]
Title says it all.
I placed the portal but when I walk through it, it says "Joining World", then teleports me a few blocks away up in the sky.
Does NOT take me Ratlantis.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
