### ISSUE TITLE
Server Crash due to Server Tickloop in RatsCustomEvents

### ISSUE THREAD

**Issue by SpycrabSXL** [Alex-the-666/Rats#528]
Version: 1.16.4 MC, rats-7.0.4-1.16.3

Server crashed randomly while playing again. Thank you for the help 👍 

[crash-2021-01-12_18.03.04-server.txt](https://github.com/Alex-the-666/Rats/files/5803982/crash-2021-01-12_18.03.04-server.txt)
https://pastebin.com/9NvRQZW1

**Comment by AlexModGuy** [comment]
fixed
