### ISSUE TITLE
Exception In Server Tick Loop For Rats causing server to crash

### ISSUE THREAD

**Issue by SpycrabSXL** [Alex-the-666/Rats#535]
java.lang.NoClassDefFoundError in EntityRat$3
Friend right clicked a chef rat with an empty hand which caused the server to crash. Does not seem to occur 100% of the time

[crash-2021-01-19_18.45.08-server.txt](https://github.com/Alex-the-666/Rats/files/5838092/crash-2021-01-19_18.45.08-server.txt)
https://pastebin.com/3Vg9TuGE

**Comment by ghost** [comment]
Similar crash here. Rats v7.0.4 in the Direwolf20 pack v1.4.0

https://pastebin.com/2sWhpnj8

**Comment by BrockDierksen** [comment]
I'm also having the same issue. Currently on the latest version and it still crashes.
Right click any Rat period and the server shuts down.

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFound errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
