### ISSUE TITLE
[1.16.5] Rats pathfinding spams server console with messages

### ISSUE THREAD

**Issue by Elfinlocks** [Alex-the-666/Rats#537]
Minecraft Ver: 1.16.5
Forge Ver: 36.0.0
Rats Ver: 7.0.5

Issue:
Rat pathfinding process spams the server console with a ridiculous amount of messages, approximately 2 to 3 every second. See attached screenshot. 

![image](https://user-images.githubusercontent.com/43624750/105126532-f8348b80-5aac-11eb-8400-8851a78f0ad7.png)

**Comment by gazzack** [comment]
Having the same issue, what is your mod list?

**Comment by gazzack** [comment]
On further review, removing https://www.curseforge.com/minecraft/mc-mods/performant fixed this for me

**Comment by LilyArlatto** [comment]
I'm also having this issue right now, not sure what happened because it was working literally today, then I stopped and restarted the server and it was spamming messages.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
