### ISSUE TITLE
Starting advancements display in chat

### ISSUE THREAD

**Issue by Lykrast** [Alex-the-666/Rats#539]
The advancements Rats and Ratlantis that serve as first advancements in their categories do not have their notification hidden (like other first advancements). This means when making a new world you immediately get a notification for those 2 advancements.

Minecraft 1.16.5
Rats 7.1.0
Ratlantis 1.0.0

**Comment by GizmoTheMoonPig** [comment]
will no longer happen in the upcoming 1.19 version
