### ISSUE TITLE
Latest Build Causes Server Crash

### ISSUE THREAD

**Issue by zachsai** [Alex-the-666/Rats#540]
https://pastebin.com/duhWS2R7

**Comment by zachsai** [comment]
1.16.5

**Comment by arazadaz** [comment]
If you have performant installed. Disable multiEntities. This fixed it for me, but is very unfortunate seeing as that feature is godsend.

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFound errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
