### ISSUE TITLE
Recipe not working -> rat_upgrade_basic_mount.json 

### ISSUE THREAD

**Issue by tweakbsd** [Alex-the-666/Rats#542]
There is an extra key named **D** with a diamond in the recipe that is not used in the **pattern**.

This one here needs to be removed
`
    "D": {
      "tag": "forge:gems/diamond"
    }
`

Here is the corrected version and sorry for not makeing a PR out of it: 

`
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "RRR",
    "RSR",
    "RRR"
  ],
  "key": {
    "R": {
      "tag": "forge:cheese"
    },
    "S": {
      "item": "minecraft:saddle",
      "data": 0
    }
  },
  "result": {
    "item": "rats:rat_upgrade_basic_mount"
  }
}
`

**Comment by GizmoTheMoonPig** [comment]
recipe is fixed in the upcoming 1.19 version, you can make a datapack and fix it yourself in 1.16 if you still play that version
