### ISSUE TITLE
Can't change volume of rats sounds

### ISSUE THREAD

**Issue by XeruTec** [Alex-the-666/Rats#543]
I installed the rats 7.0.4-1.16.3 mod in forge 1.16.4-35.1.36 and every time a rat attacks the scream is extremely loud. Also the beast which is horrible to face. I tried to change the volume, but this scream isn't changeable.

It would be very nice if the sounds are changeable with hostile mobs or mobs in general

**Comment by xenoflot** [comment]
Came here to mention this. Running Rats 7.1.0-1.16.5, playing the Skyopolis4 skyblock. I have a darkroom/deadfall mob farm and the squeal of dying rats is much, much louder than the deaths of other mobs. It's be great if this could be normalised or configurable. Thanks!

**Comment by GizmoTheMoonPig** [comment]
check out #305 for an explanation as to why this is
