### ISSUE TITLE
"Rat Warrior Clan" advancement typo

### ISSUE THREAD

**Issue by MuricanSWAG** [Alex-the-666/Rats#546]
I was just playing and saw an error in the advancement description, I assumed it was meant to be "stronger" instead of "stringer".

![image](https://user-images.githubusercontent.com/11933787/105614062-c5341580-5d94-11eb-839d-8c0c345ad236.png)

**Comment by GizmoTheMoonPig** [comment]
lmao, will be fixed in the upcoming 1.19 version
