### ISSUE TITLE
Can't open my world after putting Mekanism tank inside curdling station

### ISSUE THREAD

**Issue by Grzesiu447** [Alex-the-666/Rats#547]
I had milk inside my Mekanism tank, and I tried putting it inside the curdling station. Immediate crash, and now I can't join that world.
[crash-2021-01-23_21.58.59-server.txt](https://github.com/Alex-the-666/Rats/files/5861234/crash-2021-01-23_21.58.59-server.txt)

**Comment by GizmoTheMoonPig** [comment]
cant reproduce, tanks work just fine in the curdler. I assume it was fixed at some point. Tested on 1.16
