### ISSUE TITLE
Miner rats prioritizing crops and not creating paths.

### ISSUE THREAD

**Issue by arazadaz** [Alex-the-666/Rats#548]
Versions 7.0.3 - 7.1.0 & others???

This is a problem that has affected me both on 7.0.3 and the latest version of Rats which is 7.1.0 as of the moment.

The first issue is that rats with the miner upgrade seem to prioritize mining crops over ores.

The second issue is that rats don't seem to be able to mine through stone, or anything to get to their destination. I even tried jacking the max block hardness way up in the config for rats, but they refuse to mine paths. Rat dig holes is also set to true.

Edit: I would like to add that they do however, mine ore when they are within range of it.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
