### ISSUE TITLE
Let me compost shit

### ISSUE THREAD

**Issue by JoshDangIt** [Alex-the-666/Rats#551]
I'm a bit disappointed nothing in this mod can be composted. Add composter recipes for raw rats, cheese, etc. Maybe if you want something possibly overpowered let us compost garbage piles.

**Comment by GizmoTheMoonPig** [comment]
I dont really see a point in making anything compostable, and nothing in the mod would exactly be fit to be compostable. Vanilla doesnt allow you to compost meat, and garbage makes no sense. I guess, if anything, I can add cheese in, but that really seems like a waste
