### ISSUE TITLE
Crash: Exception generating new chunk

### ISSUE THREAD

**Issue by 1nd1r4** [Alex-the-666/Rats#553]
Crash-report: https://pastebin.com/eEaw7i3Z

Rats-config: https://pastebin.com/waTLgCzD

**Comment by 1nd1r4** [comment]
I think that `"Rats Spawn Like Monsters" = false` causes this.

**Comment by GizmoTheMoonPig** [comment]
will no longer be a problem in the upcoming 1.19 version
