### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by mxnmnm** [Alex-the-666/Rats#56]
Ok so I've seen some of the previous posts here about lag issues and it is different here since 
1. changing the config does nothing
2. their might be an advanced rocketry aspect to it since this was discovered on a different planet
3. it seems to go down into com.github.alexthe666.rats.server.entity.ai.RatAIWander.func_75249_e() specifically rather than the RatAIEnterTrap.shouldExecute(), RatAIRaidChests.shouldExecute(), and RatAIRaidCrops.shouldExecute() that was the problem in the last few issues that were created.
4. the lag is under 1 tps so like I said in the title, extreme.

Visual
https://imgur.com/a/7lfNaBX

Spark Link
https://sparkprofiler.github.io/#iORjoWITgp

pls fix so I can be reunited with my brethren and if you need anymore info let me know

**Comment by mxnmnm** [comment]
yea ignore the advanced rocketry aspect since I did another thing in the over world and I got this

https://sparkprofiler.github.io/#HY7Nkrcuvd

**Comment by Sunconure11** [comment]
@Alex-the-666 Might want to look into this, and possibly see if it's affecting your other mods as well.

**Comment by docteurzoidberg** [comment]
can't wait to see this fixed so i can have my fav pets on my server! :p

**Comment by mxnmnm** [comment]
I forgot to mention that this ended up happening when I set the rats to spawn like passive mobs rather than monsters.

**Comment by Alex-the-666** [comment]
fixed, especially lag cuased by RatAIEnterTrap.shouldExecute(), RatAIRaidChests.shouldExecute(), and RatAIRaidCrops.shouldExecute() . their TPS has been brought down to below 0%.
