### ISSUE TITLE
Weird CraftTweaker incompatibility?

### ISSUE THREAD

**Issue by Pikabyte** [Alex-the-666/Rats#561]
(Tested both on both 1.16.5 and 1.16.4; Forge 36.0.13, and 35.1.37 respectively.)

When adding the forge:all_cheese tag to an item via CraftTweaker, Rats still wont accept it as a tame-able item. However, when adding the tag via a data pack, it works just fine. This doesn't appear to be a CraftTweaker issue, as the tag is definitely getting applied, as can be seen with "/tellme dump to-file ascii-table tags-item" when using the TellMe mod. Also, applying other tags like forge:cheese allows it to be used in this mod's recipes just fine. When CT is used to apply forge:all_cheese, Rats acts like it never happened. In short...

To recreate:
-Add Rats, Craft Tweaker, and TellMe (and optionally simple farming)
-Make a CraftTweaker script with <tag:items:forge:all_cheese>.add(<item:simplefarming:cheese_slice>); (or any other item).
[testscript.zip](https://github.com/Alex-the-666/Rats/files/5897644/testscript.zip)
-Load up a world, and attempt to tame a rat with the item used in the script. Notice you cannot tame a rat with the item (and that a /reload doesn't fix it.)
-Do "/tellme dump to-file ascii-table tags-item", and notice that the tag was indeed applied.
-Apply a datapack to the world that adds forge:all_cheese to the same item(the datapack I used is attached), and /reload.
[testdatapack.zip](https://github.com/Alex-the-666/Rats/files/5897643/testdatapack.zip)
-Attempt again to tame the rat with the same item. Notice everything is working as intended.

**Comment by GizmoTheMoonPig** [comment]
The rats cheese tag now follows the same convention other mods use for their cheese now, so this shouldnt be an issue anymore. All items tagged as `forge:cheeses` will work for taming rats. If you want to add more items to this tag I highly recommend using a datapack instead of crafttweaker, although using crafttweaker should be just fine
