### ISSUE TITLE
Plague Doctor trade replenish

### ISSUE THREAD

**Issue by Gamerbolts** [Alex-the-666/Rats#562]
Hi i am using the rats mod from the Direwolf 20 modpack. And I am trading with Plague Doctor's however they will not replenish their trades after trading with them. I know vanilla villagers need their job block in order to replenish the trade. Is there a job block for the Plague Doctor? Or am I doing something wrong? Thanks!

**Comment by GizmoTheMoonPig** [comment]
there is currently no job block, but I plan on adding something that counts as a job block for them. Either that, or i'll make them restock over time automatically. We'll see

**Comment by GizmoTheMoonPig** [comment]
Added in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
