### ISSUE TITLE
Rats and SereneSeasosn possible conflict

### ISSUE THREAD

**Issue by TheCoolestPaul** [Alex-the-666/Rats#563]
I can't really tell from this stacktrace what's going on, but it seems that Rats and Sereneseasons have conflicts that crash the server every 5-10 minutes.
[error here](https://pastebin.com/CqfY90KF)

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
