### ISSUE TITLE
Rats doesnt attack monsters while equipped with a sword.

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#566]
Probably intended for that slot to be filled with cheese but idk

**Comment by kihgy** [comment]
Well they attack animals with a weapon i  their mouth and the same goes for following rats after you punch something. Can rats in monster hunting mode auto attack with a weapon?

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
