### ISSUE TITLE
[Suggestion] Require rats to be fed in order to breed

### ISSUE THREAD

**Issue by WaterMonitor** [Alex-the-666/Rats#57]
Rat breeding becomes uncontrollable leading to hundreds of rats being bred and inbred over and over again especially in servers with chunk loaders. It leads to increased lag and frequent crashing. As soon as rat pups grow up they instantly breed if they are kept in the cage. The parents also breed over and over

**Comment by TheDeviantCrafter** [comment]
Don't rats in cages stop breeding when they have a certain number of rats in them?

**Comment by Alex-the-666** [comment]
fixed with rat breeding lanterns
