### ISSUE TITLE
Rats disappearing when inconsistency in player location

### ISSUE THREAD

**Issue by InCrIpTiOn** [Alex-the-666/Rats#573]
(Using modpack: All The Mods 6 version 1.5.0)
On a server, when the player teleports (Through either /tpa, /tpahere, /rtc) with a rat on their head (Through shift+rmb), the rat disappears. The rat only reappears if the user teleports back to the last location (with /back) and if the rat has not moved (stay here command). Otherwise, it dissapears.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
