### ISSUE TITLE
Crash on 1.16.5 server

### ISSUE THREAD

**Issue by Boymann** [Alex-the-666/Rats#578]
I'm not sure what to do with  the crashlog all I understand is that the rat entity crashed
[crash-2021-02-04_15.38.07-server.txt](https://github.com/Alex-the-666/Rats/files/5927852/crash-2021-02-04_15.38.07-server.txt)

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
