### ISSUE TITLE
[1.16.5] Rats failed to load correctly.

### ISSUE THREAD

**Issue by TheBadWolf331** [Alex-the-666/Rats#580]
I have absolutely no idea how to solve that problem
[crash-2021-02-06_09.36.58-fml.txt](https://github.com/Alex-the-666/Rats/files/5936503/crash-2021-02-06_09.36.58-fml.txt)

**Comment by tweakbsd** [comment]
It could be the Enderite Mod that doesn't work with Rats. I never got these 2 to work together  in medium to big-sized modpacks too.

**Comment by TheBadWolf331** [comment]
Yep. Double checked it. Entity enderite_bow is the trouble maker.

Now the mod works.
