### ISSUE TITLE
Miner rats crashing upon opening the game

### ISSUE THREAD

**Issue by ConfusedBumm** [Alex-the-666/Rats#581]
the game was working fine 2-3 hours ago but now it wint open
[crash-2021-02-07_00.38.40-client.txt](https://github.com/Alex-the-666/Rats/files/5937814/crash-2021-02-07_00.38.40-client.txt)

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
