### ISSUE TITLE
Performant and Rats gives errors in console 

### ISSUE THREAD

**Issue by TheCoolestPaul** [Alex-the-666/Rats#582]
**Describe the bug. 1.12 is no longer supported, do not make bug reports for it.**
Sometimes this error will be the last thing in console before a crash and sometimes the server will continue running and this error will pop into console a few times in a matter of minutes.

**To Reproduce**
1. Start a server with BOTH Performant and Rats mods installed.
2. Give it a few minutes
3. This error will be put into console
?. The server will crash or the server will stutter for a few seconds and continue as normal.

**Expected behavior**
No errors in console.

**Screenshots**

**Versions**
Performant 3.30m
Rats 7.1.0

**Logs**
[the error](https://pastebin.com/epzKysCu)
I have also reported the bug to [Performant](https://github.com/someaddons/performant_issues/issues/96)

**Comment by GizmoTheMoonPig** [comment]
according to performant, it should be fixed so im gonna close this
