### ISSUE TITLE
Inconsistent rat behavior.

### ISSUE THREAD

**Issue by Natey214** [Alex-the-666/Rats#584]
The first rat I had harvesting my crops would break the crop, place the main item into a container, then go and collect the other items dropped by the crop. He was so enthusiastic he would go gathering items that were just dropped and had nothing to do with the crops. The second rat I had assigned to harvesting crops, set up in the same way, breaks the crop and deposits the main item then leaves the rest. I've tried with several rats and still, none will do what the first rat did. 

A second issue is that sometimes rats just don't want to listen. This is mostly with hand tamed rats and I have yet to have the issue with a bred rat. They will just sit there and do nothing no matter what commands you give from either a flute or manually selecting them. 

I am using Rats version 7.1.1, Citadel 1.6.0, and Minecraft 1.16.5

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
