### ISSUE TITLE
Rat Radius Staff border effect not staying put

### ISSUE THREAD

**Issue by Natey214** [Alex-the-666/Rats#585]
When using the Rat Radius Staff the grid that shows where the rat's radius extends to does not stay where the rat's radius is but seems to be relative to the player. The staff still works and the radius is adjusted properly however the visual area doesn't line up with their effective area.

I am using Rats 7.1.1, Citadel 1.6.0, and Minecraft 1.6.5

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
