### ISSUE TITLE
Trash can stopped working 

### ISSUE THREAD

**Issue by Michael-McKinley** [Alex-the-666/Rats#587]
I am running the latest version of the Direwolf20 1.16 (version 1.6.1) modpack with rats (rats-7.1.1-1.16.5.jar).

I had the trashcan automated turning excess items into garbage using the "Item User" from "Cyclic" (ver 1.16.5-1.1.5) to right-click items into the trashcan, and hoppers to collect the garbage coming out. This worked for several game hours over 5 days. Today, it just stopped working.  The trash can is not accepting items.  I even pulled the trashcan out of my auto setup and tried to put items in by hand, and it won't take them.  I built another trashcan thinking maybe the timing of the Item User buggered it up and the new one won't take items either.

I can upload a zipped copy of my world, if that would help at all with troubleshooting. I have made no changes to the Direwolf20 modpack, so that can be retrieved from the FTB downloader, and my base is within sight of spawn.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
