### ISSUE TITLE
1.16.4 can’t open miner upgrade block selection GUI at all

### ISSUE THREAD

**Issue by ashtonxj** [Alex-the-666/Rats#589]

**Comment by deWaardt** [comment]
Same issue.

Minecraft version 1.16.5
Mod version rats-7.1.1-1.16.5


Right clicking with the miner upgrade doesn't do anything.
Rats don't do anything either... I can set them to transport or follow but they just sit still.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
