### ISSUE TITLE
Crash w/ InGameConfigManager

### ISSUE THREAD

**Issue by WenXin20** [Alex-the-666/Rats#59]
Minecraft 1.12.2
Forge v14.23.5.2838
[Creative Core](https://www.curseforge.com/minecraft/mc-mods/creativecore) v1.9.9
[IGCM](https://www.curseforge.com/minecraft/mc-mods/ingameconfigmanager) v1.2.2
Rats v2.0.0

After adding a custom recipe using IGCM, I got the following crash after pressing the add button. The recipe I created did not contain any blocks/items from this mod, but it does seem to be related to the Rat Crafting Table.
[Crash Report](https://gist.github.com/WenXin20/59efe24087d5e80ed8a13bb42534424c)

**Comment by Alex-the-666** [comment]
fixed
