### ISSUE TITLE
Miner not working

### ISSUE THREAD

**Issue by Prasence** [Alex-the-666/Rats#591]
So I set a Miner with the Miner upgrade to go and mine, but the rat just doesn't do anything? It just sitts there? Help please.
I am playing on 1.16.4

**Comment by ZJDavis** [comment]
Same issue. I checked [the wiki](https://rats-mod.fandom.com/wiki/Rat_Upgrade:_Miner) and it says to right-click the upgrade to open the GUI and assign blocks, but this does not open any GUI. I am using All The Mods 6 modpack, if that helps.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
