### ISSUE TITLE
Crash on entering Ratlantis Portal (Exception in server tick loop)

### ISSUE THREAD

**Issue by FreshlySqueezedOJ** [Alex-the-666/Rats#593]
Made the Ratlantis Portal and went in for the first time - server crashed

[crash-2021-02-14_02.10.26-server.txt](https://github.com/Alex-the-666/Rats/files/5977139/crash-2021-02-14_02.10.26-server.txt)

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
