### ISSUE TITLE
BUG: Rats wheel cage decoration generates RF but cannot be transfered or used

### ISSUE THREAD

**Issue by kristiandaugaard** [Alex-the-666/Rats#594]
Using the direwolf20 modpack version 1.6.1 the wheel appears to generate power, and a cable can be connected to it, but no power is transferred. Does not work with energy transfer rat upgrade either.

**Comment by abadger** [comment]
This seems to still occur with mods/rats-7.2.0-1.16.5.jar

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
