### ISSUE TITLE
Please add Tamed NBT

### ISSUE THREAD

**Issue by arazadaz** [Alex-the-666/Rats#596]
Due to the current nature of the mod. I'm unable to kill only untamed rats which is troublesome on a server when I am trying to debug. If you could simply add a tamed NBT tag, or set the owner NBT to nothing for untamed rats, that would be nice.

**Comment by GizmoTheMoonPig** [comment]
Tamed rats have been split off into their own entity now for performance reasons. Wild rats still fall under the namespace `rats:rat` and tamed rats use `rats:tamed_rat`
