### ISSUE TITLE
[Suggestion] Config for yellow screen

### ISSUE THREAD

**Issue by DedMaxim** [Alex-the-666/Rats#597]
Confit Byaldi and Potato Knishes give yellow screen effect when eaten. Looks cool! ...for the first time. After you ate it 500 times, this effect starts being annoying, rather than interesting. Would be nice, if config file had an option to turn this visual effect off

**Comment by GizmoTheMoonPig** [comment]
Added in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
