### ISSUE TITLE
Blacklist/whitelist upgrade item registering

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#608]
The upgrades should only allow 1 single type of item to be put in, right now if you put in a stack, the entire stack will go in but the upgrade will update and give you the excess items back. Furthermore, I see that if a stack is shift clicked, then only 1 item will go in the slots, but, all the remain slot will be filled with the same items. Imo the upgrades shouldnt even cost an item when registered, the ghost item will appear but the item never got consumed, this is good for items such as diamonds, as you dont have to waste one.

**Comment by GizmoTheMoonPig** [comment]
I changed this a while ago (I think in the port to 1.19.4?) but all interfaces that accept items as guides will now use ghost items instead of consuming the item. This includes whitelist/blacklist, miner (when it comes back), and the rat crafting table
