### ISSUE TITLE
Zombie villagers that got cured using purrifying liquid, doesnt give you discount on their trades

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#611]
Tradionally, after curing a zombie villager, it should give you permanent discount on its trades, but that isnt the case for this modded method, the trades are still the same.

https://minecraft.gamepedia.com/Trading

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
