### ISSUE TITLE
Rats 'harvest' Farmer's Delight seeds infinitely - item dupe

### ISSUE THREAD

**Issue by NolanSeryn** [Alex-the-666/Rats#612]
This was on Brass, version 0.5.0 (version 0.5.1 doesn't seem to have addressed this, either - both are running on Minecraft 1.16.5).

When setting a rat to re-plant seeds with the 'Harvest' command, and equipped with the re-planter upgrade, the Tomato seeds (I believe this would apply to various other FD plants as well) are 'harvested' regardless of growth stage, giving the rat a tomato seed while leaving the plant intact. Basically, this just dupes the seeds (and also messes with their harvesting routine, because they'll do this endlessly).

For anyone having a similar or identical issue: I've found a decent workaround using the blacklist upgrades, blacklisting tomato seeds (and wheat seeds, since Harvest rats have a habit of charging after tall grass in the middle of nowhere when they run out of crops to harvest), but all the same, I thought I should post this issue.

They're working so hard.

**Comment by NolanSeryn** [comment]
Additionally: a similar behavior happens with Immersive Engineering and Hemp - but in this cause they'll harvest/break the entire plant, regardless of growth stage, even with the re-planting upgrade.

_Additionally_, Farmer's Delight rice has... half of one issue, and half intended results - they harvest the rice panicles from the top, but then 'dupe' the seeds on the bottom, duplicating rice 'seeds'.

Same thing applies with the blacklist here - I imagine I can set them up to ignore rice, Farmer's Delight seeds, etc - and have a second farmhand rat gather the dropped seeds instead.

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
