### ISSUE TITLE
Rat crafting table crash

### ISSUE THREAD

**Issue by NullRien** [Alex-the-666/Rats#620]
mc 1.16.4
forge 35.1.36
when i put a item into the rat crafting table to craft it, it just crashes.
[crash-2021-02-23_00.41.09-server.txt](https://github.com/Alex-the-666/Rats/files/6026200/crash-2021-02-23_00.41.09-server.txt)

**Comment by GizmoTheMoonPig** [comment]
this was an issue with netherite plus, they marked a method as client only when they really shouldnt. Seems to have been fixed now
