### ISSUE TITLE
R-Clicking a Rat Crashes the Game

### ISSUE THREAD

**Issue by Stormchaser465** [Alex-the-666/Rats#621]
As the title states, my multiplayer server crashes any time I right click a rat. This started happening after I left the server this morning and came back after making food. I tried figuring it out on my own for a bit, but the crash report leaves me to believe the issue might not be client-side. I'll upload my last three crash reports, in case there's any important differences (I doubt it, but I'm not one to take chances).

[crash-2021-02-23_01.52.21-server.txt](https://github.com/Alex-the-666/Rats/files/6026392/crash-2021-02-23_01.52.21-server.txt)
[crash-2021-02-23_01.11.22-server.txt](https://github.com/Alex-the-666/Rats/files/6026377/crash-2021-02-23_01.11.22-server.txt)
[crash-2021-02-23_01.04.45-server.txt](https://github.com/Alex-the-666/Rats/files/6026378/crash-2021-02-23_01.04.45-server.txt)

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
