### ISSUE TITLE
Miner does not mine a path for itself

### ISSUE THREAD

**Issue by VitrexLIVE** [Alex-the-666/Rats#624]
When I use the regular miner upgrade, the rat tries to go to an ore, but can not mine a path for itself to get to the ore, so I have to make the path for it, which makes the rat useless because I might as well just mine the ore myself then. The Advanced miner upgrade does the same thing, a tried to get him to mine only redstone ore and he still could not break any blocks to get to the ore. I'm using rats-7.1.1-1.16.5.jar in a 1.16.4 server with other mods. 

**Mod list:**  

|Dungeons Mod                  |dungeonsmod                   |1.16.3-1.1.2       
 |Mining Helmet                 |mining_helmet                 |2.0.0              
 |Just Enough Items             |jei                           |7.6.1.65           
 |The Conjurer                  |conjurer_illager              |1.0.13          
 |ToroHealth                    |torohealth                    |NONE              
 |Wonderful Enchantments        |wonderful_enchantments        |1.0.3           
 |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1       
 |Create                        |create                        |mc1.16.3_v0.3e    
 |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1       
 |Waystones                     |waystones                     |7.3.1              
 |Citadel                       |citadel                       |1.5.3              
 |Alex's Mobs                   |alexsmobs                     |1.4.1            
 |Traveler's Backpack           |travelersbackpack             |5.3.8             
 |YUNG's API                    |yungsapi                      |1.16.4-Forge-4    
 |Good Night's Sleep            |good_nights_sleep             |1.2.10            
 |Dungeon Crawl                 |dungeoncrawl                  |2.2.2            
 |Advanced Tools                |advancedtools                 |1.16.4-1.0.2        
 |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4       
 |Useful Slime                  |usefulslime                   |1.0               
 |Paraglider                    |paraglider                    |1.3.1.0             
 |Forge                         |forge                         |35.1.37           
 |Structure Gel API             |structure_gel                 |1.7.5             
 |Minecraft                     |minecraft                     |1.16.4             
 |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.3       
 |MoreVanillaLib                |morevanillalib                |1.2.14              
 |MoreVanillaTools              |morevanillatools              |2.1.5              
|Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.428 
 |Valhelsia Structures          |valhelsia_structures          |16.0.5         
 |Dungeons Plus                 |dungeons_plus                 |1.1.0         
 |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1      
 |Storage Overhaul              |storage_overhaul              |1.16.4-1.0.3       
 |Majrusz Library               |majrusz_library               |1.3.0             
 |The Gaia Dimension            |gaiadimension                 |1.3.1              
 |Einstein's Library            |einsteins_library             |1.4               
 |Xaero's Minimap               |xaerominimap                  |21.2.0             
 |Leap                          |leap                          |1.0.1              
 |Rats                          |rats                          |7.1.1              
 |Lava Monster                  |lava_monster                  |1.0.9              
 |AutoRegLib                    |autoreglib                    |1.6-47            
 |Quark                         |quark                         |r2.4-306           
 |TheAbyss                      |theabyss                      |1.2.0            
|MoreVanillaArmor              |morevanillaarmor              |1.16.2-1.2        
|HunterIllager                 |hunterillager                 |1.16.4-1.2.0      
 |Reusable Rockets              |reusable_rockets              |1.16.4-1.0.1     
|The Undergarden               |undergarden                   |0.4.2              
|Aquaculture 2                 |aquaculture                   |1.16.4-2.1.11      
 |The Bumblezone                |the_bumblezone                |1.16.4-2.2.9    
|Switch-Bow                    |switchbow                     |1.7              
|FastLeafDecay                 |fastleafdecay                 |v25          
|YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1

**Comment by CorvidSpino** [comment]
Happens for me too, they just try to walk trough blocks

**Comment by callmejay758** [comment]
I tested this with just rats & jei. Still happens.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
