### ISSUE TITLE
Undead upgrade Server crash

### ISSUE THREAD

**Issue by KevinDaGame** [Alex-the-666/Rats#628]
I have encountered a crash where a rat with the undead upgrade set to hunt monsters crashes the server upon hitting a mob. I have originally encountered this issue in a nether fortress on an SMP with a lot of mods, but I have tried it on a local server with just the rats mod and it still crashed the server.

**Crash log:**
https://pastebin.com/3gG9VuvF

**Notes**
- The crash only seems to happen with the undead upgrade
- I have only confirmed it on zombified piglins and blazes
- I have tested it on forge 36.0.14
- Minecraft version 1.16.5
- Rats version 7.1.1
- Citadel version 1.5.3 (tried 1.6.1 too with the same result)
- It occurs regardless of what other mods are loaded
- this could be related to issue #502 

**How to reproduce:**

1. Set up a forge server version 36.0.14
2. add the rats mod and citadel to the server
3. spawn a rat and tame it
4. give the rat undead upgrade
5. put the rat in a sack and head to the nether
6. find a group of zombified piglins and release the rat near them
7. set the rat to hunt mosters.
8. watch as the rat crashes the server

**Suspicion**
I suspect that having the undead upgrade on your rat when it attacks the mob will cause the mob to try but fail to target the rat, resulting in an infinite loop until it reaches stackoverflow. I am not a java expert though so I am unsure

**Comment by kodragon7** [comment]
I am having the same issue while running **rats 7.2.0-1.16.5**. I have confirmed with several mob types. I do not experience a crash when passive mobs are targeted, only hostile or neutral mobs. The log below is from my current modpack, the issue occurs even when Rats and Citadel are the only mods installed.

**Crash Log:** [https://pastebin.com/Mz3HEG6C](url)

**Comment by GizmoTheMoonPig** [comment]
duplicate #389
