### ISSUE TITLE
Rats not spawning in preexisting world 1.16.4

### ISSUE THREAD

**Issue by lildrreth** [Alex-the-666/Rats#629]
so i added the necessary mods and when loading up my pre existing world the only thing that has spawned is one plague doctor and that was after 12 days ingame time otherwise nothing else has spawned including blocks

**Comment by KevinDaGame** [comment]
Use garbage to get rats, they spawn pretty rarely in my experience

**Comment by lildrreth** [comment]
i cant cause none of the items that the mod is supposed to add are appearing minus the plague doctor and cheese related items
