### ISSUE TITLE
[1.16.5] Ticking Entity RatAIHarvestMilk

### ISSUE THREAD

**Issue by ghost** [Alex-the-666/Rats#631]
Got this crash after restarting my Direwolf20 1.16 server this morning: https://pastebin.com/rT050jU2

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
