### ISSUE TITLE
Plague Doctor crashing server in mining dimension

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Alex-the-666/Rats#632]
It seems a plague doctor has been crashing our server in my modpack. We have had several crashes over the past three days and the only thing all the crashes have in common is that a plague doctor was present in the crash report. The doctor was in the JAMD mining dimension, and the strange thing is it took several attempts with the kill command to kill it according to Crash Utilities. 

- Minecraft 1.16.5
- Forge: 36.0.43
- Rats: 7.1.1-1.16.5
- JAMD: 1.1.9-beta+mc-1.16.5
- Mod pack: [99 Mods on the Wall](https://www.curseforge.com/minecraft/modpacks/ninety-nine-mods-on-the-wall/files/3218569)

[Crash report](https://pastebin.com/q3F52Juy)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
