### ISSUE TITLE
Rats just stop gather items

### ISSUE THREAD

**Issue by MrHoopsThe1** [Alex-the-666/Rats#635]
When I set rats to gather items they will for alittle while but then they just stop. I've tried swapping the a rat with another rat but then eventually that rat also just stops. Btw I'm playing 1.16.5 forge.

**Comment by Celophy** [comment]
every type of rat doesnt take items... they need to fix it

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
