### ISSUE TITLE
Item gathering with platter upgrade will take a little items and deposit

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#637]
With the platter upgrade, the rat can hold up to 64 items at a time. But when a gather rat is equipped with this upgrade, it will remain the previous habit of take 1 item and deposit, sometimes 3,4. The correct behavior would be for the rat to keep collecting items until they have a full stack.

Like Thaumcraft 4 Thaumium golems

**Comment by kihgy** [comment]
I even saw one gathering rat that was carrying some items and cant go back, when I switch out the items(for the same items) it work. 

Haha bad meme mod

**Comment by GizmoTheMoonPig** [comment]
see #198
