### ISSUE TITLE
(1.16.5) Rat with 'replanter' upgrade still destroys modded crops.

### ISSUE THREAD

**Issue by VENNTennison** [Alex-the-666/Rats#640]
I gave a rat the upgrade that supposedly means it destroys the crop then immediately replants it, however for Pam's Harvestcraft 2 crops it just destroys them. It could be because Pam's 2 crops drop no seeds and are planted by the product, but surely then potatoes and carrots wouldn't work with rats either? Considering this mod is often used in FTB modpacks with modded crops, it would be nice to be able to use rats with them. This could be an issue with Pam's though, which seems equally likely.
Thank You!

**Comment by KajesLorian** [comment]
We're having the same problem as well. Will not replant crops from Mystical Agriculture, Farmer's Delight, Simple farming, or Druidcraft.

Minecraft 1.16.4
Forge 35.1.36
Rats 7.1.1-1.16.5

**Comment by GizmoTheMoonPig** [comment]
fixed already, see linked commit
