### ISSUE TITLE
[1.16.5] Milkmaid Rat feeding into Curdling Station causing crashes on game boot

### ISSUE THREAD

**Issue by RaiFeren** [Alex-the-666/Rats#643]
Main exception: `java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.entity.ai.RatAIHarvestMilk$1`

Running Single player instance of All The Mods 6

Crash report attached
[crash-2021-03-05_19.42.54-server.txt](https://github.com/Alex-the-666/Rats/files/6094632/crash-2021-03-05_19.42.54-server.txt)

**Comment by Terell-Davis** [comment]
Same issue here
Running a Multiplayer Server
ModPack: Magica Infinitum III - 1.16.4 v3.2.0

Most Recent Crash Report
[crash-2021-05-20_16.40.24-server.txt](https://github.com/Alex-the-666/Rats/files/6518793/crash-2021-05-20_16.40.24-server.txt)

**Comment by AlexModGuy** [comment]
should be fixed soon
