### ISSUE TITLE
Rats work area 1.16.5

### ISSUE THREAD

**Issue by bogie1989** [Alex-the-666/Rats#646]
Set up a tree farm with rats and noticed the staff that allows you to setup your rats work area seems to only effect the radius centered on the rat and no the area you select only noticed it because after and hour of smooth operation my base turned into a forest even with too lumberjacks to one planter rat they seem to only work in the size area I told them too but centered on the rat and not the middle of the tree farm

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
