### ISSUE TITLE
Rat mounts unsync with rats

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#649]
While rats is equipped with the rat mount, a few problems occur:
Following mode: Rat mount wont teleport, furthermore, if you punch something, the rat mount wont attack it, combatable ones that is
Bow and crossbow upgrade: when equipped with rat mount, the mount will not attack, while it shound have both shoot from afar while closing to swipe, similar to thaumcraft golems with dart shooter :-).

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
