### ISSUE TITLE
Can put upgrades with GUI into itself

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#651]
Tested with white/black list, advanced mining uprade.

**Comment by warning-djkajslh** [comment]
Thr upgrade I am specifically talking about is the one that you are open in your hotbar, you can literally input the upgrade into itself.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
