### ISSUE TITLE
[1.16.5] Mod loading error has occurred on latest Forge. (java.lang.ArrayIndexOutOfBoundsException: 512)

### ISSUE THREAD

**Issue by Gbergz** [Alex-the-666/Rats#653]
Game shuts down while loading the game on newer forge versions (36.0.54)
"**java.lang.ArrayIndexOutOfBoundsException: 512**"

**Minecraft**: 1.16.5
**Forge**: 36.0.54
**Rats**: 7.1.1
**Citadel**: 1.6.2

**Crash Report**
https://gist.github.com/Gbergz/593b874ed93f9a85a080a67e4dac1a39

**- Gbergz**

**Comment by Gbergz** [comment]
Edit: Removing Ratlantis addon solved the problem. So it's something in there if I were to guess.

**Comment by Gbergz** [comment]
Update: Crashing issues seems to have solved themselves by just removing the mods (Rats & Ratlantis), launching the game then re-adding them.
Weird.

**Comment by GizmoTheMoonPig** [comment]
Gonna assume this was just a one-off issue then. Looks like it had something to do with the hat models, which I changed how that works anyway
