### ISSUE TITLE
Rats Server Crash 1.16

### ISSUE THREAD

**Issue by Chris3606** [Alex-the-666/Rats#656]
[crash-2021-03-14_14.23.49-server.txt](https://github.com/Alex-the-666/Rats/files/6137410/crash-2021-03-14_14.23.49-server.txt)

Get this crash related to the Rats mod when attempting to start minecraft server; after multiple restart attempts, it (usually) ends up working.

As per mod-list, this is with the Direwolf20 pack.

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
