### ISSUE TITLE
quarry rats pathfinding doesn't work

### ISSUE THREAD

**Issue by Paperweight82** [Alex-the-666/Rats#657]
my rats have mined 3-4 levels down and are now no longer able to find their way back to the quarry to deposit the blocks, and just run around in circles at the bottom of the hole, occasionally injuring each other
(started with one rat only, added 2 more when first got stuck, same result)

playing DW20 version 1.16-1.7.0
rats version 7.1.1
minecraft 1.16.5
forge 36.0.45

**Comment by Neposis** [comment]
Same issue here, the rat is stuck going back and fourth and when given flying upgrade it just cannot mine blocks

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
