### ISSUE TITLE
Crash upon startup trying to load mod.

### ISSUE THREAD

**Issue by TheLunarArtemis** [Alex-the-666/Rats#66]
I am using the latest release version of rats (according to curseforge) and have even downloaded three new separate versions of forge, thinking it was forge. None of the versions I tried worked. They either crashed, or I had to download a new version due to using too low of a version for some other mods i'm using.

This is the crash message I get from the launcher (that specifies its rats)
![image](https://user-images.githubusercontent.com/17260497/63218050-8e20f580-c106-11e9-94b5-8e1b2b19d913.png)

here is the crash report I was given https://pastebin.com/WyAz0mmX 

Idk if you need this, but here's all the mods within my folder: https://imgur.com/a/1QLYSZ2 

Edit: It has to be something with the latest version (2.0.0) as I downgrade back to 1.2.0 and it no longer crashes

**Comment by Compegen** [comment]
That crash is because you have another mod using dimension -8. You can either find that mod, or change Ratlantis's ID in the config

**Comment by Alex-the-666** [comment]
^
