### ISSUE TITLE
floating ratlantis portals drop you into the ocean

### ISSUE THREAD

**Issue by Winddbourne** [Alex-the-666/Rats#667]
This is a problem I'm having in my skyblock pack which starts the player at Y129 . . . if you create a Ratlantis portal at that height everything works fine EXCEPT that you spawn into Ratlantis floating in mid air and promptly fall into the ocean. So far I've never spawned over solid blocks and died from the fall but . . . it makes getting back rather inconvenient. 

It would be nice if I always just spawned on the Ratlantis portal platform rather than floating in the sky, or even far below on the ground or in the ocean itself. 

Edit - further testing shows this doesn't happen every time, just often enough to be noticeable, it can also happen the other way around on a return trip if my exit platform isn't big enough . . . it's just not checking to make sure I'm on a block when it decides where to place me. lol

**Comment by Winddbourne** [comment]
More testing shows it's not that the platform is too small, I'm actually glitching through the floor of the platform as I spawn . . . I tried to fix this by replacing the platform blocks with something else in case it was a problem with those blocks and found that the platform base actually gets rebuilt every time I enter the dimension, which means I'm probably sometimes falling through in the split second between when the original platform stops existing and the new one comes into being. 

It also means I can get an endless supply of cheese tiles without leaving the platform which I also don't really like. LOL

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
