### ISSUE TITLE
Demon Rat Freezing Nether - 1.16.5

### ISSUE THREAD

**Issue by leyxcx** [Alex-the-666/Rats#668]
When loading into the Nether the game freezes and this comes up in the log

[Server thread/WARN] [net.minecraft.world.server.ServerWorld/]: Trying to add entity with duplicated UUID 706b98e8-966c-464f-a724-0f650264a6c4. Existing rats:demon_rat#10, new: rats:demon_rat#10
[latest.log](https://github.com/Alex-the-666/Rats/files/6202435/latest.log)

I don't know if this is a mod interaction or not, but removing Rats fixes the issue

**Comment by GizmoTheMoonPig** [comment]
see #671
