### ISSUE TITLE
rats able to break block in block breaking protected areas

### ISSUE THREAD

**Issue by benbenlaw** [Alex-the-666/Rats#669]
dimensional dungeons disables the breaking of blocks in its dimension but rats can break them

![image](https://user-images.githubusercontent.com/42780877/112495317-b3162980-8d7b-11eb-9885-c051a81e44ad.png)

**Comment by GizmoTheMoonPig** [comment]
I think I covered every case in the 1.19 port (5e5583927d7cc0727b0c8dbb162f274c0380c77e) if you find anything I missed please let me know
