### ISSUE TITLE
[7.1.1-1.16.5] Demon Rats being spawned on Striders as part of world generation will deadlock the game

### ISSUE THREAD

**Issue by TelepathicGrunt** [Alex-the-666/Rats#671]
When helping out someone with figuring out why the Nether was deadlocking all the time, I decided to pull out VisualVM to get a thread dump of the issue. Here's the result of the server thread that is stuck:
https://paste.ee/p/UAXvN

So what this seemed to show is that Forbidden Arcanus was trying to spawn a mob but Rats hooked on with an event and then tried to do world.addEntity(...) and that's when the game locked up. This is the line in question 
https://github.com/Alex-the-666/Rats/blob/1.16.3/src/main/java/com/github/alexthe666/rats/server/events/CommonEvents.java#L238

So what was happening is as the game is creating chunks, Forbidden Arcanus tries to spawn a Strider as part of world generation. Then Rats, also hooked onto a mob spawn event, then tries to add a Demon Rat to spawn riding the Strider. Except, Rats called world.addEntity(...) which then will call world.getChunk on the currently generating chunk. That method will wait until the chunk is finished generating before retrieving the chunk. Hence why if this method is called during world generation, it causes the chunk to now wait on itself and then deadlocks forever.

The solution to this is to use world.spawnEntityAndPassengers(...) instead as that method is worldgen safe and will not deadlock. Hopefully this helps! The current workaround to prevent this is to disable spawnDemonRats config from Rats to stop the server thread from being deadlocked. This may be the cause of the freezing reported by this person as well: 
https://github.com/Alex-the-666/Rats/issues/668

**Comment by BlackInkBlood** [comment]
I ran into this same issue on a custom modpack. It's too bad I only found this thread after figuring out the hard way it had something to do with the rats mod. I'm glad that there is a solution and that this mod won't have to be completely removed. Thanks for reporting on this issue so thoroughly!

**Comment by CKY-** [comment]
we where having the same issue. thanks for pointing this out. how do we get the devs to take a closer look at this?

**Comment by GizmoTheMoonPig** [comment]
appreciate the help as always man. Will have this fixed for 1.19
