### ISSUE TITLE
Rat's layer helmet crash

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#673]
I tried to have load of rats to automate my stuff, and one day I open my world to these crashes. Literally that one world crashes.
https://pastebin.com/THjLuFVP
Not sure if any other mod is causing this, I am really frustrated with this, I cant utilize rats at all.

**Comment by kihgy** [comment]
Decided to give the mod another try, I replaced new rats, and this time I let them naked, with the exception of one, still crash upon re launch.
https://pastebin.com/ysui7gXU

**Comment by warning-djkajslh** [comment]
This is due to rats automating ans accessing ender chests from ender storage mod, I removed ender storage and the mod work.
https://github.com/TheCBProject/EnderStorage/issues/160

**Comment by kihgy** [comment]
Haha trash meme mod
https://pastebin.com/FNJfEvFE

**Comment by AlexModGuy** [comment]
update mod
