### ISSUE TITLE
Won't let me load my world

### ISSUE THREAD

**Issue by Crim-Crom** [Alex-the-666/Rats#675]
Set up some stuff in the create mod and then to gather wool for windmills, I set a rat up with a shearing upgrade, double chest and ~4 sheep.

I logged off and tried coming on the next day and it crashes all the way back to the launcher, giving: "error code 0".

https://pastebin.com/wVa2D1uR

Edit: I've now tried setting "removeErroringEntities" to true in the world's forge.toml file in the config folder and even that hasn't helped

**Comment by litjohn50** [comment]
I have a similar issue with my world.

Mod Version: 7.1.1
Forge: 36.1.4

Bug: I restarted my world after playing with rats and giving one a job. and on restart it crashes on load.

Crashlog: https://gist.github.com/litjohn50/314808fd15a879c29864059823db9a13

**Comment by AlexModGuy** [comment]
Shoudl be fixed in next release
