### ISSUE TITLE
Rats incorrect interaction with other modded plants

### ISSUE THREAD

**Issue by DivineVendetta** [Alex-the-666/Rats#676]
Replanter upgrades dont seem to work with modded plants from Pam's Harvestcraft or thermal series plants, they just get broken anyway.

**Comment by ghost** [comment]
As of today, my replanter rats will harvest Pam's Harvestcraft plants and other mods, but will not properly deposit them into chests. They hold the items in their mouths at the chest, but will not deposit like they do with vanilla crops. 
Case in question involves the replanter upgrade alone and attempting to deposit into a vanilla spruce chest.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
