### ISSUE TITLE
milkmaid rat doesn't work properly with the curdling station

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Rats#678]
when tested with a fluid tank it work, but not for when directly deposit fluid in the curdling station

**Comment by Firestorm357** [comment]
It seems to work for me, the issue I think is that the milk doesn't show up in the curdling station. it just looks like there's air in there. Even though there is milk, and it will produce cheese.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
