### ISSUE TITLE
Demon rats are spawning all over the surface world

### ISSUE THREAD

**Issue by FrogLock** [Alex-the-666/Rats#681]
Currently in our server Demon rats are spawning all over the surface world and we do not know what could be causing the issue however we use a lot of mods.
I'd gladly delete any mod other than Rats to fix this if needed
Version 1.16.5

Modlist:

Bookshelf (by DarkhaxDev)
ZeroCore 2 (by ZeroNoRyouki)
Mekanism Additions (by bradyaidanc)
Refined Storage Addons (by raoulvdberge)
MrCrayfish's Gun Mod (by MrCrayfish)
Adorn (Forge) (by Juicebus)
Inventory Pets (by Purplicious_Cow_)
Kotlin for Forge (by thedarkcolour)
Ender Storage 1.8.+ (by covers1624)
Storage Drawers (by Texelsaur)
MrCrayfish's Furniture Mod (by MrCrayfish)
Industrial Foregoing (by Buuz135)
Thermal Locomotion (by TeamCoFH)
ProjectExtended (by pupnewfster)
Just Another Rotten Flesh to Leather Mod (by alexdaum1)
Waystones (by BlayTheNinth)
Thermal Innovation (by TeamCoFH)
Rats (by alex1the1666)
Xaero's World Map (by xaero96)
Wawla - What Are We Looking At (by DarkhaxDev)
Cuneiform (by azmalent)
Renewed Animal (by BOTpapa)
Trash Cans (by SuperMartijn642)
Citadel (by alex1the1666)
Cat loading screen (by jjkay03)
Titanium (by hrznstudio)
SwingThroughGrass (by exidex)
Thermal Cultivation (by TeamCoFH)
Rats: Ratlantis (by alex1the1666)
ProjectE (by SinKillerJ)
Biomes O' Plenty (by Forstride)
Spare The Animals (by miraisoft)
Fairy Lights (by pau101)
Tinkers Construct (by mDiyo)
Macaw's Trapdoors (by sketch_macaw)
Uppers (by vadis365)
Apotheosis (by Shadows_of_Fire)
Patchouli (by Vazkii)
Mantle (by mDiyo)
Caelus API (Forge) (by TheIllusiveC4)
Building Gadgets (by Direwolf20)
Subterranean Wilderness (by Melonslise)
Blood Magic (by WayofTime)
Doggy Talents (by percivalalb)
Macaw's Windows (by sketch_macaw)
Extreme Reactors (by ZeroNoRyouki)
Refined Storage (by raoulvdberge)
OpenBlocks Elevator (by vsngarcia)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
ExtraSpace (by y4z0n)
Botania (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
Ender Crop (by DrManganese)
Thermal Foundation (by TeamCoFH)
Cutecore (by ed1c24)
Fantasy Mounts (by Bonfyre_)
Macaw's Paintings (by sketch_macaw)
Cooking for Blockheads (by BlayTheNinth)
CoFH Core (by TeamCoFH)
Mystic's Biomes (by jayhillyt)
Thermal Expansion (by TeamCoFH)
Obfuscate (by MrCrayfish)
Quark (by Vazkii)
Just Enough Resources (JER) (by way2muchnoise)
Craftable Horse Armour & Saddle [CHA&S] (by EwyBoy)
Aquaculture 2 (by Shadowclaimer)
Mushroom Golems (by TinyDaggsy)
Macaw's Fences and Walls (by sketch_macaw)
Ceramics (by KnightMiner)
Macaw's Bridges (by sketch_macaw)
Clumps (by Jaredlll08)
Croptopia [FABRIC/FORGE] (by thethonk)
Terra Incognita: The Unknown Land (by azmalent)
Reap Mod (by henkelmax)
Corail Tombstone (by Corail_31)
Dank Storage (by tfarecnim)
Better dogs (by mrblueyeti)
Iron Chests (by ProgWML6)
Mob Grinding Utils (by vadis365)
AutoRegLib (by Vazkii)
Fast Leaf Decay (by olafskiii)
Visual Enchantments (by cisculog)
Curios API (Forge) (by TheIllusiveC4)
Better Animals Plus (by cybercat5555)
Macaw's Roofs (by sketch_macaw)
Unity: Dark Edition (by theCyanideX)
Applied Energistics 2 (by AlgorithmX2)
Inventory Tweaks Renewed (by David1544)
Small Ships (by talhanation)
iChunUtil (by ohaiiChun)
Macaw's Doors (by sketch_macaw)
Xaero's Minimap (by xaero96)
Macaw's Furniture (by sketch_macaw)
Hats (by ohaiiChun)
Hwyla (by TehNut)
Placebo (by Shadows_of_Fire)
Curious Elytra (Forge) (by TheIllusiveC4)

**Comment by GizmoTheMoonPig** [comment]
I cant get this to happen for the life of me, but considering I redid how demon rat spawning, and spawning in general, is done internally this shouldnt be an issue anymore
