### ISSUE TITLE
[BUG] Rats AI doesn't work

### ISSUE THREAD

**Issue by Mrdestruch** [Alex-the-666/Rats#682]
Wild rats do not run away from the player. Tamed rats stand still and do not follow commands.
The problem with tamed rats is solved by restarting the world, but you need to restart it every time after taming new rats. The wild rats continue to fearlessly ignore the player.

Minecraft 1.16.5
Forge 36.1.4

My list of mods:
Rats 7.1.1 - 1.16.5
Ice and fire 2.1.6 - 1.16.4
Citadel 1.6.2 - 1.16.5

**Comment by Ghillied** [comment]
I'm getting the exact same problem in the atm6 modpack and when I'm playing on a server with people it makes it impossible to play around with this mod as it restarts every 24hrs, So after taming I have to wait for the next server restart before I can even use the rats.

**Comment by AlexModGuy** [comment]
in the next version the rat whistle can be used to reset rat ai 👍
