### ISSUE TITLE
Rats sometimes continue jobs even when set to stay or wander

### ISSUE THREAD

**Issue by iReveni** [Alex-the-666/Rats#687]
I have a rat that transports stuff from one chest to another. When the chest empties I set him to stay and take him back to where I keep him, He will then teleport (Slowly and short distances) toward the chest he was previously taking from, and if it was food he was transferring then he will eat it. The only fix I have found so far is to take his "Platter Upgrade" away from him and set him to stay.

Minecraft Version: 1.16.4
Rat Version: 7.1.1-1.16.5

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
