### ISSUE TITLE
Game crash when opening rat's inventory

### ISSUE THREAD

**Issue by PotatoFart** [Alex-the-666/Rats#689]
I tamed a rat and went to open it's inventory but the game crashed. It has done it several times. I've tried updating forge to the latest reccomended release and I've tried reinstalling the mod itself but neither of these have worked. 
Here's the crash report.

[crash-2021-05-04_23.11.03-client.txt](https://github.com/Alex-the-666/Rats/files/6425050/crash-2021-05-04_23.11.03-client.txt)

**Comment by GizmoTheMoonPig** [comment]
duplicate #703
