### ISSUE TITLE
Rats do not seem to consider Y-axis when harvesting.

### ISSUE THREAD

**Issue by PerfyNormal** [Alex-the-666/Rats#690]
Issue: When creating a multi-level wheat farm Rats get stuck.

It seems that the rats want to harvest resources from floors bellow them, but do not realize they have to move down the nearby stairs to get there. Thus they get stuck when in Harvesting mode, if there's a level bellow them with the desired resource.

Additional info: I created a 9x9 wheat farm and 5 blocks (Where the 6th block is floor), under it there's an identical 9x9 farm with a staircase leading down. The rats set to harvest will not go down the stairs to try and farm the other layer.

Minecraft: 1.16.5
Mod: 7.1.1

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
