### ISSUE TITLE
Server crash due to pathfinding

### ISSUE THREAD

**Issue by tedik123** [Alex-the-666/Rats#691]
[crash-2021-05-07_22.41.46-server.txt](https://github.com/Alex-the-666/Rats/files/6445224/crash-2021-05-07_22.41.46-server.txt)

I'm running a 1.16.5 All the Mods 6 server and as soon as the chunk is loaded with the rat, the server completely crashes. Is there a way to fix it on the server side without having to disable the mod?

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
