### ISSUE TITLE
[1.16.5] Unable to convert a villager into a Leather Worker with Rats and Inspirations' Cauldron Tweak activated

### ISSUE THREAD

**Issue by PokeMaserJ** [Alex-the-666/Rats#692]
Knightminer said when I asked about this in TiCon's discord, that I need to report this to you, said he's done all he can do. Said something about you apparently registering villager points of interest way to early.

**Comment by AlexModGuy** [comment]
rats doesn't register any PoI though.

**Comment by PokeMaserJ** [comment]
Many apologies. Turns out the bug I'm experiencing is NOT a Rats Bug. When I narrowed it down to either Rats or Inspirations, went into their discord, Knightminer said it was your end, but after trying a couple of days ago, had Rats and Inspirations together and had it working fine. inconsistent bug on KnightMiner's side.
