### ISSUE TITLE
Plague doctor error tick

### ISSUE THREAD

**Issue by ghiltonT** [Alex-the-666/Rats#693]
[crash-2021-05-08_19.22.23-server.txt](https://github.com/Alex-the-666/Rats/files/6455153/crash-2021-05-08_19.22.23-server.txt)
ayuda nose por que pasa esto

**Comment by pibblepower** [comment]
I have the same issue.

**Comment by AlexModGuy** [comment]
> com.nekomaster1000.infernalexp.events.MiscEvents.onLivingFinishUse

issue is with infernal exp mod. not rats.
