### ISSUE TITLE
Bounded rats disappear when placing a patrol node

### ISSUE THREAD

**Issue by thecatking9274** [Alex-the-666/Rats#696]
When i bound a rat with the patrol staff and placing a node the rat will disappear but i can still hear them

**Comment by chainloaded** [comment]
Same issue here

**Comment by Bunistalri** [comment]
Same here

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
