### ISSUE TITLE
Rats have issues harvesting crops from farmer's delight

### ISSUE THREAD

**Issue by RandalfTheRed** [Alex-the-666/Rats#697]
Setting a rat to harvest next to a tomato or rice farm, the rat will harvest said crops before they are fully grown, producing no products of the crops besides their seeds. They successfully replant them, and produce a seed, essential duping that seed. these issues can be mitigated by adding a whitelist to the rat with the intended product of the crop. 

Additionally, farmer's delight adds wild variants of all crops as a way for players to get any seeds they need, however rats are harvest and replant these wild crops without destroying them, allowing the player to get infinite of any crop from a single wild crop with no growth period in between each harvest. There is also no way to have the rats distinguish between the normal crops and their wild variants using blacklists or white lists. I would recommend removing these wild crops as a harvestable crop entirely.

**Comment by RandalfTheRed** [comment]
I forgot to mention that besides the tomato and rice crops, all other crops added by this mod seem to not have any issues.

Additionally, the mushroom colonies have the same issues as the wild crops

**Comment by GizmoTheMoonPig** [comment]
Should be fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
