### ISSUE TITLE
rats-7.2.0-1.16.5.jar breaks rat radius staff. 

### ISSUE THREAD

**Issue by CommieChan** [Alex-the-666/Rats#699]
upon upgrading to rats-7.2.0-1.16.5.jar,  we gain patrol staff.  But Radius staff now broken and act as a home point setting staff, similar to the cheese staff.  Patrol staff makes rats disappears, but returns if rolled back to 7.1.1
rolling back to rats-7.1.1-1.16.5.jar resolves the issue.

reproducible in both single player and SMP modes.

**Comment by Vanix24** [comment]
Yes i have this problem i can confirm this bug

**Comment by pkluver944** [comment]
This is still an issue, HOWEVER even 7.1.1 doesn't seem to want to make the staff work

**Comment by CommieChan** [comment]
> This is still an issue, HOWEVER even 7.1.1 doesn't seem to want to make the staff work

Radius staff does work under 7.1.1., but it can be tricky sometimes because it can be a bit quirky. 
Patrol staff does not work, period. 

Also this, and other issues will not likely to be fixed, as Alex had expressed that he would like to rewrite the mod from scratch as Rats2.

**Comment by pkluver944** [comment]
> > This is still an issue, HOWEVER even 7.1.1 doesn't seem to want to make the staff work
> 
> Radius staff does work under 7.1.1., but it can be tricky sometimes because it can be a bit quirky. Patrol staff does not work, period.
> 
> Also this, and other issues will not likely to be fixed, as Alex had expressed that he would like to rewrite the mod from scratch as Rats2.

It didn't work when my modpack server had the Rats mod downgraded, did the same broken "set home and nothing else" thing. Unsure why that happened when it worked for others here.

If he's going to rewrite the mod, great! It's just not very well-communicated what the heck the author's doing

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
