### ISSUE TITLE
"Transport Item" : Rats stay blocked front of obstacle

### ISSUE THREAD

**Issue by MamylaPuce** [Alex-the-666/Rats#7]
I have a little problem with "Transport item" for rats : if there is an obstacle on the route the rat remains blocked in front of this obstacle when transporting an item from one chest to another for example

Just a Dirt block is enough for example

**Comment by DWX12** [comment]
Had a similar problem with the rat being unable to get to the container when only one block to the side diagonally. All it did was just keep hopping while it was one block away. Also seems to get stuck behind blocks as well, as stated above.
