### ISSUE TITLE
How can i enter to ratatlantis ?

### ISSUE THREAD

**Issue by TheRedUcible** [Alex-the-666/Rats#700]
I dont know how can i enter to ratatlantis, i can´t use the "mysterious token chunk" to craft the token for the "ratatlantis portal". any  can help me pls ? 
https://user-images.githubusercontent.com/84894501/119773075-1dd40600-be8e-11eb-85fb-88066c4754ef.png

**Comment by joaquinfrago** [comment]
You must install the mod extenstion - Ratlantis. It is now a separate mod from Rats

**Comment by isochronous** [comment]
@TheRedUcible  This is not the place to ask questions about gameplay. This is for filing bugs.
