### ISSUE TITLE
Problem about pathfinding

### ISSUE THREAD

**Issue by BaldStudent106** [Alex-the-666/Rats#702]
Rats wont find their way to their job. I got a rat with advanced miner upgrade and a rat with warrior upgrade which i had set to hunt monsters. Both of them wont move to work they just run around doing nothing the warrior rat would just attack any mobs that comes to it but wont move to attack mobs

Playing on All The Mods 6 version 1.6.6

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
