### ISSUE TITLE
Right click rat and game crash

### ISSUE THREAD

**Issue by TheWookofWallST** [Alex-the-666/Rats#703]
Any time I try to interact with a tamed rat it just closed the game but doesn't create a crash report . I attached the modlist and my log.
[modlist.txt](https://github.com/Alex-the-666/Rats/files/6573465/modlist.txt)
[latest.log](https://github.com/Alex-the-666/Rats/files/6573489/latest.log)

**Comment by GizmoTheMoonPig** [comment]
looks like an issue with cpm (custom player model)
