### ISSUE TITLE
Problems with farming

### ISSUE THREAD

**Issue by Newkie162** [Alex-the-666/Rats#707]
Rats with replantear (I had platter as well) will only pick up one crop and put it away, instead of putting them all away. Same with lumberjack

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e. Rats need a platter upgrade to pick up more than 1 item at a time, and this now applies to items in the world as well instead of just between containers
