### ISSUE TITLE
Several features not working since 1.14.4

### ISSUE THREAD

**Issue by RyushoYosei** [Alex-the-666/Rats#709]
Rats no longer make rat holes.
Rats no longer pass under fences/gates.
Rats no longer bypass doors.
Rats no longer take any action properly when tamed unless put in a rat sack then  put back down, to restart them,  Or you restart the server/world.
Rat miners will go and dig a single block then just sit there.

.....These really need to be fixed, The issues are piling up the longer and longer they are left un-fixed, and  need to be fixed so we have these features working properly again.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
