### ISSUE TITLE
Ticking Error When Milking

### ISSUE THREAD

**Issue by Nexiimil** [Alex-the-666/Rats#712]
The Server i run with ATM6 1.6.9 appears to be crashing due to an error with rats, specifically the HarvestMilk AI, below is the crash report. I saw recently a fork of this mod with DamnRelentless, but they do not appear to have an issues page, so I'm putting it here. Seems pretty important given that i cannot open the server without this crash instantly ticking the rat to harvest, ergo crashing the server.
[crash-2021-06-18_14.55.15-server.txt](https://github.com/Alex-the-666/Rats/files/6677873/crash-2021-06-18_14.55.15-server.txt)

**Comment by PalisseVolia** [comment]
> The Server i run with ATM6 1.6.9 appears to be crashing due to an error with rats, specifically the HarvestMilk AI, below is the crash report. I saw recently a fork of this mod with DamnRelentless, but they do not appear to have an issues page, so I'm putting it here. Seems pretty important given that i cannot open the server without this crash instantly ticking the rat to harvest, ergo crashing the server. [crash-2021-06-18_14.55.15-server.txt](https://github.com/Alex-the-666/Rats/files/6677873/crash-2021-06-18_14.55.15-server.txt)

I have the same problem on Ragnamod VI, I had to manually remove the rat multiple times, it's pretty bad...

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
