### ISSUE TITLE
Demon Rats + Forbidden & Arcanus

### ISSUE THREAD

**Issue by brumoen** [Alex-the-666/Rats#713]
Hi, we're having issues with our modpack OverKill SMP, and it seems to be related to several other issues here as well.

#671 
#668 

We started seeing this issue after we updated Forbidden & Arcanus from 1.16.4-1.0.0 to 16.2.0-beta-4.

We reported the issue to the developer of Forbidden & Arcanus over here:
https://github.com/stal111/Forbidden-Arcanus/issues/172#issuecomment-864385777

Their answer is to disable the Demon Rats spawn to circumvent the issue, but that's not a reliabel solution as we won't be able to gather Nether Cheese and other items related to Demon Rats which is the reason for me coming into your forum asking for a solution which you hopefully can deliver.

**Comment by theCalcaholic** [comment]
See also: 

[Forbidden-Arcanus#186](https://github.com/stal111/Forbidden-Arcanus/issues/186#issuecomment-919206780)
[Tetra#488](https://github.com/mickelus/tetra/issues/488)

**Comment by n0itLT** [comment]
Has this been resolved by the creator?

**Comment by GizmoTheMoonPig** [comment]
see #671
