### ISSUE TITLE
Problem with replanter rat

### ISSUE THREAD

**Issue by DragonLayer101** [Alex-the-666/Rats#720]
My rat has the replanter, platter, and extra breath upgrades and is set to harvest. However, it doesn't break flowers or grass, when harvesting them but collects them as if it has (I now have over 64 flowers from one). Is it a bug, or is there a way to fix it without taking the replanter upgrade off?

![2021-07-06_12 30 20](https://user-images.githubusercontent.com/87031470/124636001-107b4580-de56-11eb-89f6-b7d46c5b16c0.png)
![2021-07-06_12 37 59](https://user-images.githubusercontent.com/87031470/124636871-086fd580-de57-11eb-94f6-6a1c2d74ab23.png)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
