### ISSUE TITLE
Rat with Animal Breeder Upgrade Feeds other Rats

### ISSUE THREAD

**Issue by BlackInkBlood** [Alex-the-666/Rats#721]
I'm making an automated farm utilizing the rat upgrade: animal breeder on a few rats. However, the rat being used to breed the sheep also feeds wheat to the other rats, and it does so about every 30 seconds or so. If the problem rat is denied access to the other rats, it still prioritizes trying to feed them over the sheep, even though the sheep are off of the breeding cooldown.

MC: 1.16.5
Forge: 36.1.23
Mod: 7.2.0-1.16.5

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77
