### ISSUE TITLE
Direwolf20 1.16 Rats won't interact with storage blocks

### ISSUE THREAD

**Issue by zevric** [Alex-the-666/Rats#723]
I use the cheese wand and tell the rats to retrieve items from a chest and deposit elsewhere and no matter what command they are set on, they just sit there. It's a huge problem for the chef rat because he can't get food from a chest to cook it, and he can't deposit it after it's cooked if you drop it for them which just locks them up.

**Comment by zevric** [comment]
After messing around some more I realized that you have to restart for the rats to accept the command to pull/deposit from chests. Very much a pain on servers not so much on singleplayer.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
