### ISSUE TITLE
(1.16.5) Rats and Performant interaction bug.

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Alex-the-666/Rats#724]
Hey, fan of your work out here but I ran into an issue: Some sort of miscommunication between the Rats mod and Performant.

Some interactions with rats seems to cause some sort of.. Desync? I'm not sure how to describe it. For instance, putting a rat on any mount makes the rat sit up right and twitch on the floor without its mount, when set to follow you can hear the rat still interacting with the world but visually not moving. You can remove and re-add the mount and the mount will show up... but now the issue is just transferred to the rat being unable to move (atleast visually) again.

I made a minimalist modpack to recreate the issue and found it remaining true.

Here is my game log, unfortunately I'm not sure it gives much to work with: [Game Log](https://github.com/Alex-the-666/Rats/files/6844944/latest.log)

On a side note: This issues section is a mess, I'm sorry you have to put up with so much noise. Keep being great out there!

**Comment by GizmoTheMoonPig** [comment]
this sounds similar to the rat mount desync bug (#649) that I fixed in 1.19. Hoping its not an issue here anymore
