### ISSUE TITLE
Player trapped in Ratlantis portal causing TPS to drop to 0 and crash the server.

### ISSUE THREAD

**Issue by Dandas52** [Alex-the-666/Rats#725]
I can't provide too many details, since this was reported to me by the trapped player and I was able to fix it by teleporting him out, but hopefully the crash logs can provide that information.

As far as I know, he entered the Ratlantis portal normally, and was stuck jumping between the Overworld and Ratlantis. During this time, the console was spamming the following message ""fetching packet for removed entity itemEntity[RatPelt] over and over until the server dropped to 0 TPS and crashed.

Crash log is linked below.
https://pastebin.com/HwjF8nMz

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
