### ISSUE TITLE
EntityPlagueBeast can#t be summoned because of NullPointerException

### ISSUE THREAD

**Issue by Budschie** [Alex-the-666/Rats#728]
Steps to reproduce:
1. Start minecraft with mod.
2. Execute the command "/summon rats:plague_beast"
3. Observe that the entity can't be summoned because of a NullPointerException.

This is likely due to the fact that the strings OwnerUUID and Owner are not present when summoning the entity.
You have to specify a OwnerUUID for it to work (e.g. with the command "/summon rats:plague_beast ~ ~ ~ {OwnerUUID:"0"}").

**Comment by GizmoTheMoonPig** [comment]
shouldnt be an issue in 1.16, definitely wont be an issue in 1.19
