### ISSUE TITLE
Mod generates visual artifacts with Optifine (shaders)

### ISSUE THREAD

**Issue by AngleWyrm10** [Alex-the-666/Rats#729]
Heads are often painted black, and items dropped into the world are frequently surrounded by a flat panel of backdrop color.

This has also been mentioned in issue #666, and issue #694, both which were closed with only the mention that one was a duplicate reference to the issue.

![screenshot](https://user-images.githubusercontent.com/55937426/128740620-eefc2ddd-ce1e-4503-81b2-d17f614f5ec0.png)

---
Minecraft 1.16.5
Rats 7.2.0-1.16.5
Citadel 1.7.3-1.16.5
Optifine HD U G8
Forge 36.2.0

**Comment by ravemaster99** [comment]
Why was this issue closed? There are no notes. Was the issue fixed? If so, can you post a link to the release of the newest version?
