### ISSUE TITLE
Rats are not defending their owners. 7.2.0 1.16.5 Forge 36.2.0

### ISSUE THREAD

**Issue by Nihilhalla** [Alex-the-666/Rats#730]
This issue is still present in 7.2.0-1.16.5. I've had two players complain of rats not even defending themselves for that matter.
Rats in the "Follow me" pattern don't seem to defend the player who tamed them. Rats in the "Hunt Monsters" pattern seem to work for a period of time then sit there and die to mobs. Let me know what information would help you best, or if there's a debug setting I can enable so I can get you the data you need in order to fix this.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
