### ISSUE TITLE
Request: Ratlantis upgrade: Golden rat

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Rats#733]
This upgrade will make the rat to adorn itself with a luxurious golden appearance similar to other ethereal golden rats running beside you while wearing the ratlantis armor.
Functionality: I don't even know man :), I will leave it for you to decide, close this if it is too lame.

**Comment by GizmoTheMoonPig** [comment]
8.1 will include a new upgrade called Rat Upgrade: Idol, which will make piglins not attack it or you if you hold it on your head/shoulder.
