### ISSUE TITLE
rats with combatable mounts shouldn't attack mobs without its mount.

### ISSUE THREAD

**Issue by warning-djkajslh** [Alex-the-666/Rats#739]
Issue:
From my testing with attacking mounts such as golem and beast mount, I can say that once the mount died, the rat itself will begin to attack on its own. The problem is that now this rat only has like 8hp and would definately die.
Solution:
Have the rat to not attack anything without its mount, only when another mount spawned, then it may proceed.
With the exception of other passive mount such as chicken and strider, since these do not attack.

**Comment by GizmoTheMoonPig** [comment]
Added in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
