### ISSUE TITLE
Yet Another Conflict

### ISSUE THREAD

**Issue by Youhadabadday** [Alex-the-666/Rats#74]
I already saw someone with the same issue, but I just want to know which one of MY mods is conflicting.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  FMLModule (mdxlib-3.0.0.12.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  FMLPlugin (albedo-1.12.2-1.1.0.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/9/19 8:17 PM
Description: Initializing game

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.rat
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.github.alexthe666.rats.server.CommonProxy.registerSpawnable(CommonProxy.java:149)
	at com.github.alexthe666.rats.server.CommonProxy.registerEntities(CommonProxy.java:139)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_400_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.github.alexthe666.rats.server.CommonProxy.registerSpawnable(CommonProxy.java:149)
	at com.github.alexthe666.rats.server.CommonProxy.registerEntities(CommonProxy.java:139)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_400_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 985022000 bytes (939 MB) / 2147483648 bytes (2048 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                           | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft           | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp                 | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge               | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | micdoodlecore       |                   | minecraft.jar                                    | None                                     |
	| LCH   | obfuscate           | 0.2.6             | minecraft.jar                                    | None                                     |
	| LCH   | albedocore          | 0.1               | minecraft.jar                                    | None                                     |
	| LCH   | securitycraft       | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar               | None                                     |
	| LCH   | damageindicatorsmod | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.0.jar            | None                                     |
	| LCH   | orbis-lib           | 0.2.0             | orbis-lib-1.12.2-0.2.0+build127.jar              | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | aether              | 0.2.6             | aether_ii-1.12.2-0.2.6+build127-universal.jar    | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCH   | albedo              | 1.0.0             | albedo-1.12.2-1.1.0.jar                          | None                                     |
	| LCH   | mdxlib              | 3.0.0.12          | mdxlib-3.0.0.12.jar                              | None                                     |
	| LCH   | avp                 | 6.0.0.27          | aliensvspredator-6.0.0.27.jar                    | None                                     |
	| LCH   | appliedenergistics2 | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | jei                 | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                        | None                                     |
	| LCH   | quark               | r1.6-177          | Quark-r1.6-177.jar                               | None                                     |
	| LCH   | autoreglib          | 1.3-32            | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | bibliocraft         | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCH   | sanlib              | 1.5.1             | SanLib-1.12.2-1.5.1.jar                          | df48348748b5e141b1d118e2302a8d5be930b708 |
	| LCH   | claysoldiers        | 3.0.0-beta.2      | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar          | None                                     |
	| LCH   | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux        | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore            | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar           | None                                     |
	| LCH   | cofhworld           | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | coloredlights       | ${version}        | ColoredLights-1.12.2-v1.2.0.jar                  | None                                     |
	| LCH   | mantle              | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                         | None                                     |
	| LCH   | thaumcraft          | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
	| LCH   | twilightforest      | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar      | None                                     |
	| LCH   | tconstruct          | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                 | None                                     |
	| LCH   | conarm              | 1.2.3             | conarm-1.12.2-1.2.3.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | customnpcs          | 1.12              | CustomNPCs_1.12.2(09jul18).jar                   | None                                     |
	| LCH   | doggytalents        | 1.15.0.6          | DoggyTalents-1.12.2-1.15.0.6-universal.jar       | None                                     |
	| LCH   | enderstorage        | 2.4.5.135         | EnderStorage-1.12.2-2.4.5.135-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | erebus              | 1.0.28            | Erebus-1.0.28.jar                                | None                                     |
	| LCH   | tschipplib          | 1.1.1             | TschippLib+MC1.12.2+v1.1.1.jar                   | None                                     |
	| LCH   | extraambiance       | 1.0.1             | ExtraAmbiance+MC1.12+v1.0.1.jar                  | None                                     |
	| LCH   | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCH   | galacticraftcore    | 4.0.2.190         | GalacticraftCore-1.12.2-4.0.2.190.jar            | None                                     |
	| LCH   | galacticraftplanets | 4.0.2.190         | Galacticraft-Planets-1.12.2-4.0.2.190.jar        | None                                     |
	| LCH   | cgm                 | 0.12.2            | guns-0.12.2-1.12.2.jar                           | None                                     |
	| LCH   | llibrary            | 1.7.19            | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire          | 1.8.1             | iceandfire-1.8.1.jar                             | None                                     |
	| LCH   | ichunutil           | 7.2.1             | iChunUtil-1.12.2-7.2.1.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | minetraps           | 1.0.3             | MineTraps-1.12.2-(v.1.0.3).jar                   | None                                     |
	| LCH   | multimob            | 1.0.5             | multimob-1.0.5.jar                               | None                                     |
	| LCH   | mystcraft           | 0.13.7.02         | mystcraft-1.12.2-0.13.7.02.jar                   | None                                     |
	| LCH   | nei                 | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | primitivemobs       | 1.2.3a            | primitivemobs-1.2.3a.jar                         | None                                     |
	| LCH   | quarkoddities       | 1                 | QuarkOddities-1.12.2.jar                         | None                                     |
	| LCH   | rats                | 2.0.0             | rats-2.0.0.jar                                   | None                                     |
	| LCH   | sanplayermodel      | 1.1.1             | SanLib-1.12.2-1.5.1.jar                          | None                                     |
	| LCH   | scp                 | 2.0.10            | SCP+Lockdown-1.12.2-2.0.10-beta.jar              | None                                     |
	| LCH   | tabula              | 7.0.1             | Tabula-1.12.2-7.0.1.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | thaumicenergistics  | 2.2.1             | thaumicenergistics-2.2.1.jar                     | None                                     |
	| LCH   | thermalfoundation   | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalexpansion    | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalcultivation  | 0.3.2             | ThermalCultivation-1.12.2-0.3.2.11-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermaldynamics     | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | xaerominimap        | 1.16.2            | Xaeros_Minimap_1.16.2_Forge_1.12.jar             | None                                     |
	| LCH   | phosphor-lighting   | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50.jar                | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
FMLModule (mdxlib-3.0.0.12.jar)
  com.asx.mdx.AccessTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (albedo-1.12.2-1.1.0.jar)
  elucent.albedo.asm.ASMTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/BareBones
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz

**Comment by Youhadabadday** [comment]
Can anyone please tell me what mods are conflicting?

**Comment by Youhadabadday** [comment]
Please, I need to know.

**Comment by Alex-the-666** [comment]
whichever other mod you have that adds rats.
