### ISSUE TITLE
Demon Rats break nether

### ISSUE THREAD

**Issue by Sleeclow** [Alex-the-666/Rats#744]
Having the Demon Rat be allowed to spawn in breaks the nether, it crashes the game every time. I know apparently there is some type of conflict between Valhelsia Structures and Rats, but I've removed Valhesia structures so I can turn on the Demon Rats, they still crash the nether

**Comment by Sleeclow** [comment]
Having looked around here I see this is a very old issue, and not due to Valhesia Structures.

**Comment by LunardH** [comment]
wish the author would at least have their spawn turned off by default so i didnt had to spend hours checking mod by mod what would crash my nether

**Comment by GizmoTheMoonPig** [comment]
see #671
