### ISSUE TITLE
[Simple Issue] Plauge doctor and Black Death mask are covered by by secondary skin layer

### ISSUE THREAD

**Issue by Shibva** [Alex-the-666/Rats#747]
![image](https://user-images.githubusercontent.com/38770780/142096151-0fd7e751-bcf4-40f9-9372-6e745634c25f.png)

it you can fix this minor oversight, it would be apreciated ^w^

love the mod btw

**Comment by GizmoTheMoonPig** [comment]
masks will unrender your hat layer in the upcoming 1.19 version. Should fix the issue without any additional problems
