### ISSUE TITLE
Crash when joining world : ClassDefNotFoundError ModelSantaHat

### ISSUE THREAD

**Issue by minibn** [Alex-the-666/Rats#752]
Hi,
Since yesterday (04/01/2022), i get most of the time a crash when i'm joining my world on the modpack Ragnamod VI : 

**Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/client/model/ModelSantaHat**

I was initialy in version 7.1.2-1.16.5 when i had the first crash.
I try to load multiple time my world but with no success (new or other world can be loaded)
I then try to upgrate to RATS 7.2.0-1.16.5 and i had the same (my world was crashing but other work)
I look to the config to find if i could disable the hat but i did not found any config and yesterday eveneing, i tried again and this time the world works without changing anything. I saw rats with the santa hat and got some in my storage.

Today, i tried to join and... crash again with the same message.

It seems to be a rat with the hat that cause the error. 
Thanks for your help

[crash-2022-01-05_14.05.08-client.txt](https://github.com/Alex-the-666/Rats/files/7815078/crash-2022-01-05_14.05.08-client.txt)

**Comment by minibn** [comment]
For unlocking the situation if it happens to someone, i manage to enter a kill entity command before the error trigger.
In the crash report, I have the information of the rat entity that was causing the problem so right at the join (i had about 0.5s to do it), i enter the command : 
_/kill @e[type=rats:rat,x=-211,y=116,z=1426,limit=1]_

**Comment by GizmoTheMoonPig** [comment]
NoSuchMethodError and ClassDefNotFoundError errors are something I havent been able to reproduce. These methods should exist, especially when it comes to AI tasks, so theres definitely something else going on here. Closing as this is something I cant exactly deal with without more context
