### ISSUE TITLE
crash when i join ratlantis NoClassDefFoundError RatlantisRuinsStructure$Start

### ISSUE THREAD

**Issue by Paozie83** [Alex-the-666/Rats#753]
When entering the atlantis dimension the server crashed and since then it crashes at each connection.

Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/world/structure/RatlantisRuinsStructure$Start

[crash-2022-01-19_17.43.17-server.txt](https://github.com/Alex-the-666/Rats/files/7898982/crash-2022-01-19_17.43.17-server.txt)

**Comment by GizmoTheMoonPig** [comment]
all issues regarding ratlantis are being closed as the dimension has been completely rewritten from the ground up and shouldnt have these issues anymore in 1.19 and beyond
