### ISSUE TITLE
Cauldron Error

### ISSUE THREAD

**Issue by Banavy** [Alex-the-666/Rats#758]
I have a custom modpack with rats in it, but when I put milk in the cauldron there is no achievement and even after 8 seconds it still stays as milk. It is probably a mod incompatibility, but im not sure what mod it is. Anyone know what i should do?

**Comment by ilyaskaragel** [comment]
well i had the same problem it looks like neapolitan's milk cauldron is incompatible with it you can disable from config if it's the case
