### ISSUE TITLE
Crash On Beast Mount Kill

### ISSUE THREAD

**Issue by N0tM3e** [Alex-the-666/Rats#761]
At first I thought it had to do with the hats mod I had installed but when I took off the mod I still had the same problem of game crashing on beast mount kill/damage (If it matters the other two upgrades on rat were : health boost and undead also my version is 1.16.5

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
