### ISSUE TITLE
Flight doesn't allow rats to mine

### ISSUE THREAD

**Issue by Neposis** [Alex-the-666/Rats#766]
[rats-7.2.0-1.16.5]

First of all: I love love LOVE this mod, my gf is also addicted to becoming a rat queen.

Now the issue:
I do not know if this is a feature but currently, the flying upgrade doesn't allow the rat to mine which makes the pathfinding problem in the quarry awkward. (The pathfinding thing only occurs sometimes though)

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e

**Comment by Neposis** [comment]
You do not know how happy I am because of the update, thank you for your work
