### ISSUE TITLE
Rats mod completely breaking entire game in Ragnamod VI server

### ISSUE THREAD

**Issue by Toastiiieee** [Alex-the-666/Rats#767]
There's so many problems I don't even know where to start. I would attach a crash report but I guess I struggle to choose between the 30 reports I have (and nO that is nOt an exaggeration, I literally have 30 crashes from this mod) 
Basically, it's one of 3 things that crash the server: 
1) opening ANY rat gui 
2) entering Ratlantis through any means, not just the portal
3) placing, looking at, or breaking certain blocks from the mod, an easy example being the rats crafting table
we have literally had to quarantine any chunk with anything rats-related and cheat in things to actually progress since the modpack normally uses ratlantis to get to the twilight forest and so on. 
I've tried using commands, I've tried updating to rats 7.2.0, I've tried straight up ignoring the mod as a whole but it just crashes the server sometimes without me doing anything.

I'm losing my mind, I'm losing my friends, I'm losing my will to live. these rats have taken everything from me. I'm seeing my therapist tomorrow and it will only be about rats. **_please just end my suffering_**

**Comment by Inrixia** [comment]
+1
Our console is currently being spammed to the point of being near unusable with patching issues from rats among other issues.

**Comment by GizmoTheMoonPig** [comment]
you said you had a bunch of crashes caused by this mod, yet you didnt attach a single one. How do you expect me to help with so little info?
Regardless, 1.16 is no longer supported. I dont recommend using 7.2.0 anyway considering how buggy it is. I'd either update to 1.19 or just not use the mod in this pack
