### ISSUE TITLE
RATS in the rat cage glithes 1.16.5

### ISSUE THREAD

**Issue by zacaca123** [Alex-the-666/Rats#769]
well you see,  in 1.16.5 , l put all my rat in rat cage to breed and play fun then they don't even move , l set them wander in rat cage and sunddenly they just jumpping every time and not move anything , they just standing there and jumpping. they also don't interact with these rat decorate . that is a problem glithes . Can you fix this error

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
