### ISSUE TITLE
flying breaks every aspect of automation

### ISSUE THREAD

**Issue by kingpandaratfu** [Alex-the-666/Rats#770]
so i wanted to have bee rats that could mine and chop trees etc but when i gave them the upgrade and told them to do it their pathfinding broke please fix it so i can have the ultimate rat empire also add support for dynamic trees so that when a rat cuts one down it actually drops items

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
