### ISSUE TITLE
Incompatibility with Crossbowverhaul / Wheellocks

### ISSUE THREAD

**Issue by laptoppunk** [Alex-the-666/Rats#778]
Installing this mod breaks the view model display and reload animations added by [this resource pack](https://www.planetminecraft.com/texture-pack/flintlock-to-wheellock/), when used alongside [Crossbowverhaul](https://github.com/DerToaster98/Crossbowverhaul)

**To Reproduce**
1. Install a fresh 1.16.5 instance
2. Install [Crossbowverhaul](https://github.com/DerToaster98/Crossbowverhaul)
3. Acquire crossbow, [observe reload animation](https://streamable.com/2ryr3g)
4. Install Rats
5. Acquire crossbow, [observe reload animation](https://streamable.com/3shd2f)

**Expected behavior**
See step 3

**Comment by GizmoTheMoonPig** [comment]
Rats doesnt touch anything related to the crossbow, theres no way this mod could be messing with it. Can you replicate this only with Rats and Crossbowverhaul?

**Comment by GizmoTheMoonPig** [comment]
closing due to no response
