### ISSUE TITLE
The game crashed whilst rendering entity in world

### ISSUE THREAD

**Issue by ninjassassin911** [Alex-the-666/Rats#779]
Playing Ragnamod VI 1.16.5, Forge 36.2.34
Multiple Rats mod entities are crashing my world on startup and I cannot find a fix.
I love your mod but moroe importantly, I love this world and do not want to lose it with all my progression.

I have multiple crash logs for different Rats mod things:
https://pastebin.com/gdrkJ8zS

https://pastebin.com/zaECDhuJ

https://pastebin.com/KhgApBAn

**Comment by GizmoTheMoonPig** [comment]
the `NoClassDefFoundError`s should no longer be an issue in 1.19. Unfortunately 1.16 is not supported so I would just recommend removing the mod, considering youre not the only one experiencing issues with Ragnamod (although your report has been the most helpful)
