### ISSUE TITLE
Pet Shop structure doesn't clear some blocks correctly.

### ISSUE THREAD

**Issue by BrisingrAerowing** [Alex-the-666/Rats#78]
![2019-09-21_23 11 28](https://user-images.githubusercontent.com/250409/65381762-5f79da00-dcc5-11e9-9000-a29bad666400.png)

It also overwrote a couple other village buildings, though I'm not sure if that's fixable on your end (village generation is... quirky).

**Comment by BrisingrAerowing** [comment]
Also, nice reference to Wallace and Gromit in the advancements.

**Comment by viceroy369** [comment]
Also noticed this...seems like a bug, since larger structures from other mods clear the land properly.
