### ISSUE TITLE
A can't craft any itens

### ISSUE THREAD

**Issue by Mr-Szary** [Alex-the-666/Rats#780]
I can't craft any item in the mod, what can it be?

**Comment by GizmoTheMoonPig** [comment]
I literally cant do anything with this. What other mods do you have installed? Are you playing on a server? Do your other mods work fine? I need actual info to help with this

**Comment by Mr-Szary** [comment]
Hi, first thanks for answering, I have asked too in rats discord server, and they told me that the version 1.16.5 is very buggy, but thanks anyway
