### ISSUE TITLE
Rat unable to leave pod when given Total Recall enchantment from Domestic Innovation

### ISSUE THREAD

**Issue by azneal** [Alex-the-666/Rats#782]
Not sure exactly if this is a weird singular issue with domestic innovation but as I've so far only seen this issue with a Rat I will post it here.

As title says the rat went into the pod when reduced low health, right clicking the pod should release the rat but it gets stuck in a loop of opening for a milisecond then reverting.

**Comment by GizmoTheMoonPig** [comment]
tested this on 8.0.2 and it seems to work as intended? The rat got dispensed from the pod just fine when I tried it. Maybe I accidentally fixed this at some point? If you get it to happen in 8.0.2 let me know, if it works fine i'll go ahead and close the issue when I get the go ahead

**Comment by GizmoTheMoonPig** [comment]
closing due to lack of any response, and since I tested this and couldnt reproduce its probably no longer an issue.
