### ISSUE TITLE
Miner Upgrade Crafting Recipe

### ISSUE THREAD

**Issue by azneal** [Alex-the-666/Rats#783]
Not sure if this is intentional but the miner recipe currently still includes Iron Ore Block, instead of the new Raw Iron item which makes the upgrade far more difficult early on as Silk Touch is then required.

**Comment by GizmoTheMoonPig** [comment]
gonna note that the miner upgrades are not currently in the game as im completely overhauling them, but the recipe will be corrected when they come back now
