### ISSUE TITLE
[1.19.4] Taming Rat causes Client Crash

### ISSUE THREAD

**Issue by HalcyonSeas73** [Alex-the-666/Rats#792]
Taming a wild rat causes a client crash on single player.

Minecraft: 1.19.4
Forge: 45.0.50
Citadel: 2.3.3
Rats: 8.0.3

Log: https://paste.ee/p/92pjD

**Comment by HalcyonSeas73** [comment]
Following up, I've managed to track down a conflicting mod; [Elytra Slot](https://www.curseforge.com/minecraft/mc-mods/elytra-slot) and its library, [Caelus API](https://www.curseforge.com/minecraft/mc-mods/caelus).

Not sure how one would go about fixing this, but the mods seem unrelated to Rats.

**Comment by GizmoTheMoonPig** [comment]
Hey there! I have already fixed what was causing this crash in 15780291b3ce2d365c01dff905ce5bd1a1c98e7f. I will be posting a new build on curseforge in a few days, I just have a couple other issues to tackle first. Thanks for reporting!
