### ISSUE TITLE
1.19.4 - Rainbow Dye crashes dedicated server

### ISSUE THREAD

**Issue by kd8lvt** [Alex-the-666/Rats#793]
When applying the rainbow dye to a rat, the server attempts to access clientside classes.
Crash Log: [https://gist.github.com/kd8lvt/80b881a69da461a87d8ac21bd710afab](https://gist.github.com/kd8lvt/80b881a69da461a87d8ac21bd710afab)
Rats version: 8.0.3-1.19.4
Citadel version: 2.3.3-1.19.4
Forge version: 1.19.4-45.0.50

**Comment by GizmoTheMoonPig** [comment]
Yeah this was a stupid mistake on my end. I'll get it fixed as soon as I can. Thanks for letting me know about this <3
