### ISSUE TITLE
Potatoes 

### ISSUE THREAD

**Issue by discordinfiniteyeet** [Alex-the-666/Rats#800]
My rat with the planter, replanter, and platter upgrades and the rainbow essence won't touch my potatoes

**Comment by GizmoTheMoonPig** [comment]
The planter upgrade repurposes the harvest command to allow the rat to plant seeds they're holding and bonemeal them. This, in turn, replaces the default crop harvesting that rats can do without any upgrades needed. To fix your issue, all you have to do is remove the planter upgrade and they'll harvest and replant your potatoes just fine.
