### ISSUE TITLE
Player taking random damage in Rats 3.0.0

### ISSUE THREAD

**Issue by viceroy369** [Alex-the-666/Rats#81]
You will just be walking/running along when your character will suddenly start taking damage for no apparent reason as if being attacked by something invisible and then die with the message "player hit the ground too hard" or "player fell out of the world" even if you never jumped down more than 3 blocks.

This issue only seemed to appear after updating to Rats 3.0.0

My guess is this is related to issue #80 - rats is somehow interfering with player position registering.

**Comment by Carro1001** [comment]
Do you have electroblob's wizardry?

**Comment by viceroy369** [comment]
I do.

**Comment by viceroy369** [comment]
I can only reproduce this with both EB's wizardry and Rats.

**Comment by Carro1001** [comment]
Go to EB's general options and disable the fall damage related option, i don't remember the name properly but that's the cause of random fall damage

**Comment by viceroy369** [comment]
Thanks that worked! I'll still leave this issue open however, since I never experienced a conflict with EB's custom fall damage before this latest update of Rats.

**Comment by trickey445** [comment]
i hope this is patched
