### ISSUE TITLE
cant access rat inv and then crashing

### ISSUE THREAD

**Issue by Secondbreakfastpip** [Alex-the-666/Rats#811]
When looking at a rats inventory, putting it in a cage, and taking it out again, player is unable to access the rats inventory and any chest inventory. when the player then leaves the server, the server crashes.
[crash-2023-07-13_15.55.51-server.txt](https://github.com/AlexModGuy/Rats/files/12041776/crash-2023-07-13_15.55.51-server.txt)

**Comment by GizmoTheMoonPig** [comment]
this is an issue with bukkit, please report it to them.
