### ISSUE TITLE
Suggestion: Roguelike Adventures and Dungeons 2 compatibility 1.16.5

### ISSUE THREAD

**Issue by GuardianPahanin** [Alex-the-666/Rats#814]
Wanted to pose the question as I am not very knowledgeable with mod pack compatablitiy.

There was an issue here https://github.com/AlexModGuy/Rats/issues/486 that the rats weren't attacking the creature or player that the player was targeting when set to follow me or hunt monsters. This seemed to be due to the upgrades added to a rat, but the other rats with out upgrades were fine. 

In RAD2 mod pack this mod is still in MC 1.16.5 where the error originated, I was not sure if there was a fix for this version of mincraft or a way to fix it for this mod pack. It would be really nice as I am just how realizing this after a bunch of hours in.

thanks for any help.

**Comment by GizmoTheMoonPig** [comment]
I only work on the 1.20 version of the mod nowadays as my time is super limited with having a full-time job and multiple other projects to maintain, plus I don't enjoy working with older versions. Getting all of the issues in past versions backported would be a HUGE pain considering I basically rewrote the mod, and even if I had more free time it still wouldn't be feasible. I understand people like to stick to older versions for one reason or another but I can't please everyone. Hope you understand.

**Comment by GuardianPahanin** [comment]
Thanks for taking the time to clarify and comment, and your point is very understandable :)

Thanks!
