### ISSUE TITLE
[1.20.1] Crash on world startup

### ISSUE THREAD

**Issue by BugmanBugman** [Alex-the-666/Rats#816]
https://hastebin.com/share/xazotitacu.ruby

**Comment by Maxi90909** [comment]
I just got the same crash
Problem is the randomium mod.
I removed it and it fixed it.

**Comment by Maxi90909** [comment]
It seems the randomium mod is incompadible with Rats, because Of this crash.
By the way this is my crash report in case you are wondering-> https://pastebin.com/14j5HLGQ

**Comment by GizmoTheMoonPig** [comment]
fixed this in ff8b9cd09495b68f7175e840d0487ddd0898c912, I initially wasnt aware that the creative tab code was safe to call serverside which randomium does. The fix will be out next update.
