### ISSUE TITLE
Possible block lag with this mod

### ISSUE THREAD

**Issue by Sunconure11** [Alex-the-666/Rats#82]
Players have been reporting block lag without TPS droppage in my pack that’s tied to this mod. Removing rats seems to stop it, but it needs further investigation.

https://www.curseforge.com/minecraft/modpacks/official-bewitchment-pack-continuation

**Comment by Sunconure11** [comment]
Try using build 4.30 to test this

**Comment by docteurzoidberg** [comment]
seems i experience the same

**Comment by Boolyman** [comment]
same here
