### ISSUE TITLE
Rats ignoring/not eating cheese 

### ISSUE THREAD

**Issue by Bunniipop** [Alex-the-666/Rats#820]
I'm not sure if this is really an issue or if something had just changed from the previous versions but some rats are just completely ignoring the cheese, the first rat I had would constantly run by it no matter where I placed it, after exiting/opening my world 2-3 times the rat finally took the bait and I was able to tame it. Thought it was fine but once I tried to tame the second one, it once again was ignoring the cheese and running away. I'm playing mc 1.20.1 and rats 8.0.6.

**Comment by GizmoTheMoonPig** [comment]
I think the issue with them at the moment is that they're prioritizing avoiding the player instead of going after cheese. I'll look into this further
