### ISSUE TITLE
My game keeps crashing whenever I load up mc, I think it has something to do with the entity

### ISSUE THREAD

**Issue by RandomMinecraftPlayer** [Alex-the-666/Rats#825]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  ratscore (rats-3.2.14-1.12.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.33.1_Forge_1.12.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.6.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/5/23 5:18 PM
Description: Initializing game

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.rat.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.rat
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.github.alexthe666.rats.server.CommonProxy.registerSpawnable(CommonProxy.java:178)
	at com.github.alexthe666.rats.server.CommonProxy.registerEntities(CommonProxy.java:145)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_214_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
	at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.github.alexthe666.rats.server.CommonProxy.registerSpawnable(CommonProxy.java:178)
	at com.github.alexthe666.rats.server.CommonProxy.registerEntities(CommonProxy.java:145)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_214_CommonProxy_registerEntities_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2608929352 bytes (2488 MB) / 5374476288 bytes (5125 MB) up to 14316732416 bytes (13653 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15G -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                            | Version                                             | Source                                                  | Signature                                |
	|:----- |:----------------------------- |:--------------------------------------------------- |:------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                     | 1.12.2                                              | minecraft.jar                                           | None                                     |
	| LCH   | mcp                           | 9.42                                                | minecraft.jar                                           | None                                     |
	| LCH   | FML                           | 8.0.99.99                                           | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                         | 14.23.5.2860                                        | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | xaeroworldmap_core            | 1.12.2-1.0                                          | minecraft.jar                                           | None                                     |
	| LCH   | obfuscate                     | 0.4.2                                               | minecraft.jar                                           | None                                     |
	| LCH   | animalium                     | 0.3.8                                               | Animalium-0.3.8.jar                                     | None                                     |
	| LCH   | biomesoplenty                 | 7.0.1.2445                                          | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar           | None                                     |
	| LCH   | craftstudioapi                | 1.0.0                                               | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar      | None                                     |
	| LCH   | harvestcraft                  | 1.12.2zb                                            | Pam's HarvestCraft 1.12.2zg.jar                         | None                                     |
	| LCH   | animania                      | 2.0.3.28                                            | animania-1.12.2-base-2.0.3.28.jar                       | None                                     |
	| LCH   | jei                           | 4.16.1.301                                          | jei_1.12.2-4.16.1.301.jar                               | None                                     |
	| LCH   | betteranimals                 | 5.5.0                                               | betteranimals-1.12.2-5.5.0.jar                          | None                                     |
	| LCH   | quark                         | r1.6-179                                            | Quark-r1.6-179.jar                                      | None                                     |
	| LCH   | autoreglib                    | 1.3-32                                              | AutoRegLib-1.3-32.jar                                   | None                                     |
	| LCH   | betterquesting                | 3.5.329                                             | BetterQuesting-3.5.329.jar                              | None                                     |
	| LCH   | birdsfoods                    | 3.1 - [1.12]                                        | birdsfoods-1.12 - 3.1.jar                               | None                                     |
	| LCH   | bookworm                      | 1.12.2-2.5.2.1                                      | bookworm-1.12.2-2.5.2.1.jar                             | None                                     |
	| LCH   | cannedfoodanddrinks           | 1.0.0                                               | CANS-1.0.jar                                            | None                                     |
	| LCH   | fcl                           | 1.12.81                                             | FCL-1.12.81b.jar                                        | None                                     |
	| LCH   | scm                           | 1.1.00                                              | CDM-v1.12.2-1.1.00.jar                                  | None                                     |
	| LCH   | customnpcs                    | 1.12                                                | CustomNPCs_1.12.2-(05Jul20).jar                         | None                                     |
	| LCH   | ptrmodellib                   | 1.0.5                                               | PTRLib-1.0.5.jar                                        | None                                     |
	| LCH   | props                         | 2.6.3.7                                             | Decocraft-2.6.3.7_1.12.2.jar                            | None                                     |
	| LCH   | df-roads                      | 1.5.2-mc1.12.2                                      | df-roads-1.5.2-mc1.12.2.jar                             | None                                     |
	| LCH   | orelib                        | 3.6.0.1                                             | OreLib-1.12.2-3.6.0.1.jar                               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                     | 3.6.1.0                                             | DynamicSurroundings-1.12.2-3.6.1.0.jar                  | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dynamictransport              | 1.0                                                 | DynamicTransport-1.0.2-alpha.jar                        | None                                     |
	| LCH   | dynamictrees                  | 1.12.2-0.9.29                                       | DynamicTrees-1.12.2-0.9.29.jar                          | None                                     |
	| LCH   | dynamictreesbop               | 1.12.2-9999.9999.9999z                              | DynamicTreesBOP-1.12.2-1.5.2.jar                        | None                                     |
	| LCH   | ic2                           | 2.8.1001                                            | IC2Classic-1.12-1.5.8.jar                               | None                                     |
	| LCH   | dynamictreesic2               | 1.12.2-1.2.3                                        | DynamicTreesIC2-1.12.2-1.2.3.jar                        | None                                     |
	| LCH   | mysticalworld                 | 1.12.2-1.11.0                                       | mysticalworld-1.12.2-1.11.0.jar                         | None                                     |
	| LCH   | dynamictreesmysticalworld     | 1.12.2-1.0.1                                        | DynamicTreesMysticalWorld-1.12.2-1.0.1.jar              | None                                     |
	| LCH   | dynamictreesphc               | 2.0.6                                               | DynamicTreesPHC-1.12.2-2.0.6.jar                        | None                                     |
	| LCH   | dynamictreesquark             | 1.12.2-1.0.6                                        | DynamicTreesQuark-1.12.2-1.0.6.jar                      | None                                     |
	| LCH   | fastfood                      | 0.2.121859723                                       | FastFood-0.2.121859723.jar                              | None                                     |
	| LCH   | net/fexcraft/lib/frl          | 1.2                                                 | FCL-1.12.81b.jar                                        | None                                     |
	| LCH   | net/fexcraft/lib/tmt          | 1.15                                                | FCL-1.12.81b.jar                                        | None                                     |
	| LCH   | foodexpansion                 | 1.3                                                 | FoodExpansion1.3.3-1.12.2.jar                           | None                                     |
	| LCH   | harvestables                  | 1.2                                                 | harvestables-1.2.1.jar                                  | None                                     |
	| LCH   | hbm                           | Hbms Nuclear Tech - Hamster Reloaded - 1.12.2-1.6.1 | Hbms Nuclear Tech - Hamster Reloaded - 1.12.2-1.6.1.jar | None                                     |
	| LCH   | ic2-classic-spmod             | 0.0.0.0                                             | IC2Classic-1.12-1.5.8.jar                               | None                                     |
	| LCH   | mts                           | 22.11.0                                             | Immersive Vehicles-1.12.2-22.11.0.jar                   | None                                     |
	| LCH   | jaffa                         | 7.63.1                                              | JAFFA-7.63.1.jar                                        | None                                     |
	| LCH   | vehicle                       | 0.44.1                                              | vehicle-mod-0.44.1-1.12.2.jar                           | None                                     |
	| LCH   | jev                           | 2.0.0                                               | jev-1.12.2-2.0.0.jar                                    | None                                     |
	| LCH   | jehc                          | 1.7.2                                               | just-enough-harvestcraft-1.12.2-1.7.2.jar               | None                                     |
	| LCH   | mca                           | 6.1.0                                               | MCA-1.12.2-6.1.0-universal.jar                          | None                                     |
	| LCH   | modroadworksreborn            | 0.0.3                                               | modroadworksreborn-0.0.3.jar                            | None                                     |
	| LCH   | new_road                      | 1.0.0                                               | More Road V3.0.0.jar                                    | None                                     |
	| LCH   | railcraft                     | 12.0.0                                              | railcraft-12.0.0.jar                                    | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCH   | mtr                           | 3.0.0                                               | MTR-1.12.2-alpha-test-0.0.1.jar                         | None                                     |
	| LCH   | bq_npc_integration            | 3.4.34                                              | NPCIntegration-3.4.34.jar                               | None                                     |
	| LCH   | pamsbreadcraft                | 1.1.0                                               | Pam's+BreadCraft+1.12.2-1.1.2.jar                       | None                                     |
	| LCH   | pamscookables                 | 1.1                                                 | pamscookables-1.1.jar                                   | None                                     |
	| LCH   | patchouli                     | 1.0-23.6                                            | Patchouli-1.0-23.6.jar                                  | None                                     |
	| LCH   | potatooscustomstructureforhbm | 1.0.0                                               | Potatoo's HBM Structures_1.12.2-1.0.3.jar               | None                                     |
	| LCH   | llibrary                      | 1.7.20                                              | llibrary-1.7.20-1.12.2.jar                              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | rats                          | 3.2.14                                              | rats-3.2.14-1.12.2.jar                                  | None                                     |
	| LCH   | rcroads                       | 0.3.0                                               | RC Roads 0.3.0.jar                                      | None                                     |
	| LCH   | roadworks                     | 2.0.0 Beta                                          | Roadworks 2-1.12.2-1.0.jar                              | None                                     |
	| LCH   | jeid                          | 2.0.6                                               | RoughlyEnoughIDs-2.0.6.jar                              | None                                     |
	| LCH   | simpleharvest                 | 1.08                                                | simpleharvest-1.08.jar                                  | None                                     |
	| LCH   | unuparts                      | 6.0.3                                               | UNU Parts Pack [MTS] 1.12.2-22.10.0-6.0.3.jar           | None                                     |
	| LCH   | unucivil                      | 6.0.3                                               | UNU Civilian Pack [MTS] 1.12.2-22.10.0-6.0.3.jar        | None                                     |
	| LCH   | unumilitary                   | 5.0.0                                               | UNU Military Pack [MTS] 1.12.2-21.3.0-5.0.0.jar         | None                                     |
	| LCH   | rxcscitymod                   | 1.0.0                                               | v2.jar                                                  | None                                     |
	| LCH   | variedcommodities             | 1.12.2                                              | VariedCommodities_1.12.2-(31Mar23).jar                  | None                                     |
	| LCH   | worldedit                     | 6.1.10                                              | worldedit-forge-mc1.12.2-6.1.10-dist.jar                | None                                     |
	| LCH   | xaeroworldmap                 | 1.33.1                                              | XaerosWorldMap_1.33.1_Forge_1.12.jar                    | None                                     |
	| LCH   | xlfoodmod                     | 1.12.2-1.9.2                                        | XL-Food-Mod-1.12.2-1.9.2.jar                            | None                                     |
	| LCH   | zawa                          | 1.12.2-2.1.3                                        | zawa-1.12.2-2.1.3.jar                                   | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCH   | betteranimalsplus             | 9.0.1                                               | betteranimalsplus-1.12.2-9.0.1.jar                      | None                                     |
	| LCH   | immersiveengineering          | 0.12-98                                             | ImmersiveEngineering-0.12-98.jar                        | None                                     |
	| LCH   | mineralogy                    | 3.8.0                                               | Mineralogy-1.12.2-3.8.0.53.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | mysticallib                   | 1.12.2-1.13.0                                       | mysticallib-1.12.2-1.13.0.jar                           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ratscore (rats-3.2.14-1.12.2.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
XaeroWorldMapPlugin (XaerosWorldMap_1.33.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.EntityPlayerMPTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftServerTransformer
  xaero.map.core.transformer.MinecraftTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.6.jar)
  org.dimdev.jeid.JEIDTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 526.98' Renderer: 'NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 526.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 526.98
	OpenGlRenderer: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by GizmoTheMoonPig** [comment]
Unfortunately, I don't support 1.12 anymore, but it does in fact look like an issue with rats. I've personally never seen it happen, but I would definitely try to see if it's some sort of mod conflict.
