### ISSUE TITLE
propose

### ISSUE THREAD

**Issue by 1936268516** [Alex-the-666/Rats#829]
Can mice collect minerals from potted plants?Rate Upgrade: Quarry AI has issues and sometimes does not collect data
Will it fix the issue with version 1.16.5?

**Comment by GizmoTheMoonPig** [comment]
Not a single thing you said made any sense. 
Regardless, 1.16 is no longer supported

**Comment by 1936268516** [comment]
Survival played long enough for rats to not harvest crops

**Comment by 1936268516** [comment]
Forge-8.1.1-1.20.1
