### ISSUE TITLE
The Bottler Upgrade doesn't have a recipe in REI (Minecraft 1.20.1)

### ISSUE THREAD

**Issue by SublimeYadon** [Alex-the-666/Rats#830]
Real excited for the new update. First thing that caught my eye was the Bottle Upgrade, which would greatly simplify a problem I've been having on my world. Went to check it out and there's no recipe for it in REI. I think it's the only new upgrade with this problem, I checked the others and they all had viewable recipes. 

I'm playing on a modified version of the New Game - An Improved Experience modpack that I added Rats and some other mods to. I don't know if this is the source of the issue, however, as I loaded up Rats mod onto a quick little fresh pack to see if I could find the recipe and had the same problem.

Here's the modlist (edited for visability, Rats, REI, and Citadel bolded. Forge is v47.2.0):

>  additionallanterns-1.1.1-forge-mc1.20.jar
> additional_lights-1.20.1-2.1.7.jar
> AdHooks-1.20.1-10.1.0.0-build.0142.jar
> Adorn-5.0.0+1.20.1-forge.jar
> advancednetherite-forge-2.0.2-1.20.1.jar
> AdvancementPlaques-1.20.1-forge-1.4.10.jar
> AI-Improvements-1.20-0.5.2.jar
> alexsmobs-1.22.6.jar
> AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar
> appleskin-forge-mc1.20.1-2.5.0.jar
> appliedenergistics2-forge-15.0.12.jar
> Aquaculture-1.20.1-2.5.0.jar
> aqupdcaracal-1.20-2.3.1.jar
> architectury-9.1.12-forge.jar
> ArmorStatues-v8.0.3-1.20.1-Forge.jar
> artifacts-forge-9.1.0.jar
> AttributeFix-Forge-1.20.1-21.0.2.jar
> automessage-2.0.3-1.20.1_forge.jar
> awesomedungeon-forge-1.20.1-3.2.0.jar
> awesomedungeonend-forge-1.20.1-3.1.1.jar
> awesomedungeonnether-forge-1.20.1-3.1.1.jar
>  awesomedungeonocean-forge-1.20.1-3.3.0.jar
> bagus_lib-1.20.1-4.0.0.jar
> balm-forge-1.20.1-7.1.4.jar
> BambooEverything-forge-3.0.3+mc1.20.1.jar
> BetterAdvancements-1.20.1-0.3.2.161.jar
> BetterCompatibilityChecker-forge-4.0.8+mc1.20.1.jar
> BetterF3-7.0.1-Forge-1.20.1.jar
> BetterThirdPerson-Forge-1.20-1.9.0.jar
> BHMenu-Forge-1.20.1-2.4.1.jar
> biomemakeover-FORGE-1.20.1-1.10.3.jar
> BiomesOPlenty-1.20.1-18.0.0.592.jar
> BlockRunner-v8.0.0-1.20.1-Forge.jar
> blue_skies-1.20.1-1.3.29.jar
> BoatBreakFix-Universal-1.0.11.jar
> Bookshelf-Forge-1.20.1-20.0.5.jar
> BuildGuide-1.20-0.3.3.jar
> camera-1.20.1-1.0.5.jar
> carpeted-1.20-1.4.jar
> carryon-forge-1.20.1-2.1.0.1.jar
> catalogue-forge-1.20.1-1.8.0.jar
> cfm-forge-1.20.1-7.0.0-pre36.jar
> chat_heads-0.10.22-forge-1.20.jar
> Chimes-v2.0.1-1.20.1.jar
> Chunky-1.3.92.jar
> **citadel-2.4.4-1.20.1.jar**
> cloth-config-11.1.106-forge.jar
> Clumps-forge-1.20.1-12.0.0.3.jar
> collective-1.20.1-6.66.jar
> colorize-1.20-forge-1.6.0.jar
> colourfulearth-1.20.1-2.1.jar
> comforts-forge-6.3.3+1.20.1.jar
> Compressium-3.0.2-build.12+mc1.20.jar
> connectedglass-1.1.7-forge-mc1.20.jar
>  Controlling-forge-1.20.1-12.0.2.jar
> corail_woodcutter-1.20.1-3.0.3.jar
> cosmeticarmorreworked-1.20.1-v1a.jar
> Craftable Horse Armour  Saddle-1.20-1.10.jar
>craftingtweaks-forge-1.20-18.2.1.jar
> CraftTweaker-forge-1.20.1-14.0.17.jar
> create-1.20.1-0.5.1.d.jar
> create-stuff-additions1.20.1_v2.0.4a.jar
> createaddition-1.20.1-1.0.0b.jar
> createendertransmission-2.0.4-1.20.1.jar
> Create_Deco_Casing_3.0.0_1.20.1.jar
> CreativeCore_FORGE_v2.11.1_mc1.20.1.jar
> ctov-3.3.5a.jar
> curios-forge-5.3.4+1.20.1.jar
> curious_armor_stands-1.20-5.0.1.jar
> Cyclic-1.20.1-1.12.4.jar
> despawningeggshatch-1.20.1-4.1.jar
> DiagonalFences-v8.0.1-1.20.1-Forge.jar
> domesticationinnovation-1.7.0-1.20.jar
> doubledoors-1.20.1-5.0.jar
> DramaticDoors-QuiFabrge-1.20.1-3.0.3.jar
> durabilitytooltip-1.1.5-forge-mc1.20.jar
> DustrialDecor-1.3.4-1.20.jar
> dynamiclights-1.20.1.1.jar
> eatanomelette-1.2.1-1.20.1_forge.jar
> eatinganimation-1.20-5.0.0.jar
> emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar
> EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar
> entityculling-forge-1.6.2-mc1.20.1.jar
> Exclusive_Weapons_Armor_and_Tools-2.1.0-Forge.jar
> ExplorersCompass-1.20.1-1.3.3-forge.jar
> ExtraDetails for 1.20.1.jar
> Fallingleaves-1.20.1-2.1.0.jar
> FallingTree-1.20.1-4.3.0.jar
> FarmersDelight-1.20.1-1.2.3.jar
> FastWorkbench-1.20.1-8.0.2.jar
> ferritecore-6.0.0-forge.jar
> findme-3.1.0-forge.jar
> fish_of_thieves-mc1.20.1-v3.0.2-forge.jar
> flib-1.20.1-0.0.11.jar
> ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
> FpsReducer2-forge-1.20-2.5.jar
> fusion-1.0.5-forge-mc1.20.jar
> geckolib-forge-1.20.1-4.2.3.jar
> gml-4.0.4-all.jar
> goldenfood-2.0.1-1.20.1_forge.jar
> guardvillagers-1.20-1.6.1.jar
> handcrafted-forge-1.20.1-3.0.1.jar
> Highlighter-1.20.1-forge-1.1.7.jar
> hunters_return-1.20.1-11.0.1.jar
> Iceberg-1.20.1-forge-1.1.15.jar
> InsaneLib-1.11.1-mc1.20.1.jar
> inventoryessentials-forge-1.20.1-8.2.1.jar
> inventorysorter-1.20.1-23.0.1.jar
> inventorytotem-1.20.1-3.0.jar
> invhud.forge.1.20.1-3.4.18.jar
> ironfurnaces-1.20-3.9.0.jar
> iron_ender_chests-1.20-1.0.2.jar
> Jade-1.20.1-forge-11.5.1.jar
> journeymap-1.20.1-5.9.15-forge.jar
> JRFTL-1.20.1-1.6.0.jar
> JustEnoughProfessions-forge-1.20.1-3.0.1.jar
> kleeslabs-forge-1.20-15.0.0.jar
> konkrete_forge_1.6.1-2_MC_1.20.jar
> kotlinforforge-4.4.0-all.jar
> lapisreserve-1.0.8F.jar
> libraryferret-forge-1.20.1-4.0.0.jar
> light-overlay-8.0.0-forge.jar
> loadingbackgrounds-1.1.0-forge.jar
> loadmyresources_forge_1.0.4_MC_1.19.3.jar
> L_Enders_Cataclysm-1.35 -1.20.1.jar
> macawsbridgesbop-1.20-1.1.jar
> macawsroofsbop-1.20-1.0.jar
> mahoutsukai-1.20.1-v1.34.58.jar
> mavapi-1.1.3-mc1.20.1.jar
> mavm-1.2.4-mc1.20.jar
> mcw-bridges-2.1.1-mc1.20.1forge.jar
> mcw-fences-1.0.7-mc1.20.1forge.jar
> mcw-lights-1.0.6-mc1.20.1forge.jar
> mcw-paintings-1.0.4-1.20.1forge.jar
> mcw-paths-1.0.3forge-mc1.20.1.jar
>  mcw-roofs-2.2.4b-mc1.20.1forge.jar
> mcw-trapdoors-1.1.1-mc1.20.1forge.jar
> mcwfencesbop-1.20-1.0.jar
> mining_dimension-1.20.1-1.0.4.jar
> modernfix-forge-5.7.4+mc1.20.1.jar
> modonomicon-1.20.1-forge-1.39.0.jar
> moonlight-1.20-2.8.28-forge.jar
> morebeautifultorches-2.5.2-1.20.1_forge.jar
> morebowsandarrows-1.0.0.jar
> MoreVanillaArmor-1.20.1-5.1.2.jar
> MouseTweaks-forge-mc1.20-2.25.jar
> movingelevators-1.4.3c-forge-mc1.20.jar
> NaturesCompass-1.20.1-1.11.2-forge.jar
> Nature_Arise-0.4.3-1.20.1.jar
> netherdepthsupgrade-3.1.0-1.20.jar
> newshieldvariants-1.1.0-1.20.1_forge.jar
> newslabvariants-2.0.0-1.20.1_forge.jar
> notenoughanimations-forge-1.6.4-mc1.20.jar
> Notes-1.20.1-1.3.0-forge.jar
> oculus-mc1.20-1.6.4.jar
> Paintings-forge-1.20.1-11.0.0.0.jar
> Patchouli-1.20.1-81-FORGE.jar
> Phenomena-2.3.2c-1.20.jar
> Placebo-1.20.1-8.3.6.jar
> player-animation-lib-forge-1.0.2-rc1+1.20.jar
> PlayerRevive_FORGE_v2.0.17_mc1.20.1.jar
> polymorph-forge-0.49.0+1.20.1.jar
> PuzzlesLib-v8.0.24-1.20.1-Forge.jar
> **Rats-1.20.1-8.1.jar**
> rechiseled-1.1.2a-forge-mc1.20.jar
> rechiseledcreate-1.0.0a-forge-mc1.20.jar
> REIPluginCompatibilities-forge-12.0.88.jar
> repurposed_structures-7.1.6+1.20.1-forge.jar
> resourcefulconfig-forge-1.20.1-2.1.0.jar
> resourcefullib-forge-1.20.1-2.1.11.jar
> responsiveshields-2.2.jar
>  Rex's-AdditionalStructures-1.20.x-(v.4.2.1).jar
> right-click-harvest-3.2.3+1.20.1-forge.jar
> **RoughlyEnoughItems-12.0.665.jar**
> RoughlyEnoughProfessions-forge-1.20.1-2.0.1.jar
> rubidium-0.6.5.jar
> SBM-BoneTorch-1.20-0.0.2.jar
> Searchables-forge-1.20.1-1.0.2.jar
> shulkerbox-1.20.1-1.0.1.jar
> signtools.forge.1.20.1-1.0.3.jar
> simplehats-forge-1.20.1-0.2.2.jar
> sit-1.20-1.3.3.jar
> slabstoblocks-1.20.1-1-forge.jar
> sleeping_bags-1.20.1-1.0.3.jar
> sliceanddice-forge-3.1.1.jar
> snowundertrees-1.20-1.4.1.jar
> snowyspirit-1.20-2.2.5.jar
> snuffles-1.0.7.jar
> sophisticatedbackpacks-1.20.1-3.18.59.909.jar
> sophisticatedcore-1.20.1-0.5.89.425.jar
> sophisticatedstorage-1.20.1-0.8.51.605.jar
> spark-1.10.53-forge.jar
> stackablestewandsoup-1.0.1.jar
> stackrefill-1.20.1-4.0.jar
> structure_gel-1.20.1-2.14.0.jar
> Super-Oro-Block-4.1.0-Forge.jar
> supermartijn642configlib-1.1.8-forge-mc1.20.jar
> supermartijn642corelib-1.1.12a-forge-mc1.20.jar
> supplementaries-1.20-2.6.2.jar
> TerraBlender-forge-1.20.1-3.0.0.169.jar
> The_Undergarden-1.20.1-0.8.8.jar
> timestamp-chat-forge-2.4.0+1.19.1.jar
> tombstone-8.5.5-1.20.1.jar
> torchmaster-20.1.4.jar
> trade-cycling-forge-1.20.1-1.0.7.jar
> trashcans-1.0.18b-forge-mc1.20.jar
> trimeffects-1.0.1-forge.jar
> twilightforest-1.20.1-4.3.1850-universal.jar
> u_team_core-forge-1.20.1-5.1.4.269.jar
> vanillaplustools-1.20-1.0.jar
> villagernames-1.20.1-5.2.jar
> VisualWorkbench-v8.0.0-1.20.1-Forge.jar
> waystones-forge-1.20-14.0.2.jar
> woodenhopper-1.20.1-1.6.0.1.jar
> worldedit-mod-7.2.15.jar
> xptome-1.20.1-2.1.8.jar
> [1.20.1] SecurityCraft v1.9.7-beta2.jar

**Comment by GizmoTheMoonPig** [comment]
Crap, I may have forgotten to add a recipe for that upgrade. I'll push a fix soon hopefully
