### ISSUE TITLE
Crash when added to modpack, possibly an incompatability

### ISSUE THREAD

**Issue by SilverMantis** [Alex-the-666/Rats#831]
Hello! whenever I add the rats mod to my modpack (its on 1.20.1), the game crashes before loading in.

here is the crash report
[crash_report.txt](https://github.com/AlexModGuy/Rats/files/12837814/crash_report.txt)

**Comment by GizmoTheMoonPig** [comment]
Looks like an issue with whatever "figura" is. Would try removing that first

**Comment by SilverMantis** [comment]
ah ok, yea that isnt too important of a mod to my modpack I'll prob just try removing it

**Comment by SilverMantis** [comment]
just removed it and it crashed so I had to remove a few more mods

its worth it tho lol, they are fairly minor mods

Thanks for the help! I couldnt figure out which was causing the original crash with figura, also btw these are the mods that caused crash and are prob incompatible with the latest version of rats. Towers of the wild modded/additions, fish of thieves, figura and no chat reports

**Comment by DaddySpin** [comment]
> just removed it and it crashed so I had to remove a few more mods
> 
> its worth it tho lol, they are fairly minor mods
> 
> Thanks for the help! I couldnt figure out which was causing the original crash with figura, also btw these are the mods that caused crash and are prob incompatible with the latest version of rats. Towers of the wild modded/additions, fish of thieves, figura and no chat reports

Its Towers of the wild.
https://github.com/celsiusqc/totw_modded_mod/issues/6
