### ISSUE TITLE
[Bug] Ore "Doubling" upgrade Bug

### ISSUE THREAD

**Issue by NicKnack819** [Alex-the-666/Rats#841]
Certain ores will duplicate based on input amount if they have an odd drop condition... Like "RFTools" dimensional shard ore and the "Forbidden and Arcanus" Stella Arcanum block which explodes when mined to generate a Stellarite Piece

Mod Pack Discovered In
[Chosen's Modded Adventure 3.3
](https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure)

Mod Version
1.20.1-8.1.2

Minecraft Version
1.20.1

Forge Version
47.1.3

Proof
[Video](https://www.kapwing.com/videos/653d429492e9457a7355c676)

**Comment by GizmoTheMoonPig** [comment]
Ah, this is caused by a huge oversight in how I make ore nuggets. That sucks, I'm gonna have to fix that asap

**Comment by NicKnack819** [comment]
yeah its pretty bugged and ended up with a full Iron backpack with the Stella arcanum had to burn it
