### ISSUE TITLE
Carry on Issue

### ISSUE THREAD

**Issue by Kaiwawa** [Alex-the-666/Rats#842]
When I have CarryOn and Rats, I collect a entity and I'm not able to drop that entity.

Minecraft version: 1.20.1
Forge version: 47.1.3
Carry On version: Carryon-1.20.1-2.1.2.5
Rats version: Rats-1.20.1-8.1.2

**Comment by GizmoTheMoonPig** [comment]
This is technically an issue with Carry On, I explain it better here:  https://github.com/Tschipp/CarryOn/issues/565. Regardless, i'll have a workaround fix done for it in 8.1.3.
