### ISSUE TITLE
Rats aren't working

### ISSUE THREAD

**Issue by vatum20** [Alex-the-666/Rats#845]
In ModPack RAD 2, rats after being alive for several seconds, they just stops and do nothing. They won't eat cheese, nothing. If rat is tamed with creative cheese (because it was only way to tame him), he doesn't obey commands. If I select follow, he doesn't follow. Gather, Transport, Kill, nothing works. Not even wonder. They sometimes wonder but 90% of the time they stand on 1 block and don't move. Cheese staff isn't making them work either.

Link to video (make sure to enable captions):
https://www.youtube.com/watch?v=RYRddqG6MtM

**Comment by GizmoTheMoonPig** [comment]
unfortunately 1.16.5 is no longer supported, but if you have any mods that "improve" mob AI (such as performant) I would try removing those first
