### ISSUE TITLE
Ore Doubling won't eat ore when set to transfer items 1.20.1

### ISSUE THREAD

**Issue by Grimc408** [Alex-the-666/Rats#846]
I am trying to get a rat to automatically double the ore in one chest but it wont eat the ore when set to transfer items. It does double when set to stay here but that wont get the ore into their inventory automatically.

**Comment by GizmoTheMoonPig** [comment]
seems to be caused by the fact that the transport command doesnt allow for eating food. Probably have to special case the ore doubling upgrade or potentially add something to the upgrade item that allows upgrades to change that behavior
