### ISSUE TITLE
Rat Upgrade: Beast Mount crashes and bricks FTB Direwolf20 1.20 server

### ISSUE THREAD

**Issue by nicolaihornung** [Alex-the-666/Rats#862]
Applying Rat Upgrade: Beast Mount (Rat Upgrade: Natural Remedy is already equipped but I don't know if this is required for reproduction) leads to my server crashing and bricking the save. I set up a new test server and had my player recreate the situation and it seems to be reproducible. Sadly something about my backups seems to have been broken as there was only one from today and that one is also crashing upon loading into the server so if there's a way to fix the world after this happens that would also be marvelous.

This is happening on a FTB Direwolf20 1.20 version 1.12.1 server I self-host on docker using https://github.com/itzg/docker-minecraft-server.

I attached the server container log file as well as the crash report.

[crash_log.txt](https://github.com/AlexModGuy/Rats/files/14550660/crash_log.txt)
[crash-2024-03-10_15.45.52-server.txt](https://github.com/AlexModGuy/Rats/files/14550661/crash-2024-03-10_15.45.52-server.txt)

**Comment by GizmoTheMoonPig** [comment]
This is an issue with Canary loading classes it shouldnt ever touch, try removing the mod. It causes countless issues with mods anyway so I highly recommend not using it
