### ISSUE TITLE
Can't go through a nether portal while having a rat/rats on shoulders

### ISSUE THREAD

**Issue by Legoego19** [Alex-the-666/Rats#863]
Minecraft-1.20.1
Forge-47.2.0
Rats-1.20.1-8.1.2
Citadel-2.5.4-1.20.1
Balm-forge-1.20.1-7.2.2

When you pick up a rat on your head or more rats and try to go through a nether portal(or any moded portal) you simply stand in it and you dont teleport there is no spining animation of teleportation either.

**Comment by GizmoTheMoonPig** [comment]
this is intentional as its a vanilla mechanic, I cant change this. I would just use rat sacks to transport your rats around through dimensions
