### ISSUE TITLE
Rats Recipe don't show on JEI

### ISSUE THREAD

**Issue by Klouver-github** [Alex-the-666/Rats#865]
Rats on 1.20.1 hasn't been update in a bit but I can't seem to find recipe on JEI but can find it in creative tab https://paste.gg/p/anonymous/a5b4d3d3088a46358b23ca0cc70a8d67
![2024-03-24_06 06 33](https://github.com/AlexModGuy/Rats/assets/62172911/b1bf227f-0faa-45d7-99f6-a680b22a655a)

**Comment by GizmoTheMoonPig** [comment]
Theres another mod messing with the stack sizes of items in the creative inventory, causing our stuff to not display in JEI. I have no idea who is causing this but its not our fault
