### ISSUE TITLE
Rats are unable to collect fluids for transport

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Alex-the-666/Rats#873]
As the description entails- currently rats are completely unable to transport fluids. I found this out the hard way in a survival world I have been doing with my partner and was severely disappointed in finding this issue.

From observation, (and uh, well hearing it.) there are some cases its like the rat can't function on filled tanks, but does attempt to bucket tanks... when they are empty resulting in just loud bucket noises. If the tank is filled, they will simply stand there and do absolutely nothing.

I set up a minimal pack using only Thermal series mods and Create (I figure if it doesn't work with them it doesn't work period?) to see if it isn't the modpack. Bittersweetly, the issue is still there but at least I _think_ that rules out any compatibility issue.

Have a picture of a unionized rat.
![image](https://github.com/AlexModGuy/Rats/assets/13931211/8e6ba042-ee4e-4185-9140-7e590ff81ad3)

And here is the log from the session the picture was taken in: [latest.log](https://github.com/AlexModGuy/Rats/files/15220003/latest.log)

**Comment by Reginald-Halifrax** [comment]
On a semi-related note (I can put this up as a new issue if you prefer):

Energy transfer rats who are delivering to a full energy cell (or removed before delivery) gain the ability to infinitely charge any item currently in their hand while they themselves never lose charge.

Pictured: a rat charging a flux capacitor at 10rf/t for free.
![image](https://github.com/AlexModGuy/Rats/assets/13931211/b3450d7d-4c79-4a53-8d2b-0bc4785f4fc3)

**Comment by GizmoTheMoonPig** [comment]
both issues will be addressed and fixed in 8.1.3. I plan to do a release sometime this week or next week. Thanks for reporting!
