### ISSUE TITLE
Rat appearances not loading

### ISSUE THREAD

**Issue by DalHowHug** [Alex-the-666/Rats#874]
When an upgrade that changes the appearance of the rat is applied the game doesn't render it properly.  The mod pack is Direwolf 1.20 and the info mod that the game has actually renders it properly
![2024-05-14_22 00 38](https://github.com/AlexModGuy/Rats/assets/87918919/ce0f29ed-6ce0-4f98-8fe9-f7b12072c7d3)

**Comment by DalHowHug** [comment]
Don't know how but its magically fixed

**Comment by etherealgears** [comment]
I still have this issue on 1.20.1 (Forge ver. 47.3.5, Rats ver. 1.20.1.8.1.2). If I apply an upgrade to a rat, its appearance doesn't change. Then randomly one rat will change appearance, but the rest that have the same upgrade still don't change their appearance. Happens with the rainbow dye thing too.
