### ISSUE TITLE
Multishot crossbows all players to duplicate rats using rat arrows

### ISSUE THREAD

**Issue by RuneKeeper666** [Alex-the-666/Rats#875]
If you get a multishot crossbow in Minecraft and shoot a rat arrow out of it you get 3 rats from the arrow instead of just 1 allowing you to duplicate items, upgrades, and rats.

**Comment by GizmoTheMoonPig** [comment]
this will be fixed once 8.1.3 comes out on CurseForge, I pushed a fix a while ago for it
