### ISSUE TITLE
Trying to remove Pet Shop Villager trade with Crafttweaker does not work

### ISSUE THREAD

**Issue by DPerez2881** [Alex-the-666/Rats#878]
_For context, I am trying to balance the Rats mod to be less combat-oriented for a modpack I am working on with some friends._

I wrote a custom .zs script file for CraftTweaker that should have removed the trade with a level 4 pet shop owner that takes emeralds and gives a rat armor upgrade. The code compiled successfully- no errors, but it did not remove the trade. Even reached out for help with my script, and found that the trade itself is of a custom type, and thus it is not removable with CraftTweaker.

Would love advice for a workaround to this in the meantime, but either way, just wanted to make the issue known.

**Comment by GizmoTheMoonPig** [comment]
I'll have to look into this. Its been a hot minute since I did anything with the trades but i'll see if I can make them compatible with scripts like that

**Comment by GizmoTheMoonPig** [comment]
Ive pushed a "fix" for this in 8.1.3. I dont know how crafttweaker works, nor do I really have the energy to try to learn, so once the update is out please let me know if its functional now. If not i'll look into it again
