### ISSUE TITLE
Armor rats receive from helmets and upgrades is tripled.

### ISSUE THREAD

**Issue by PSISeven** [Alex-the-666/Rats#882]
For example, equipping a rat with a leather helmet gives it three armor points (1.5 icons), whereas it should only give one armor point (0.5 icons). The armor rat upgrade, which should give 10 armor points, gives 30. #

**Comment by GizmoTheMoonPig** [comment]
this is apparently intentional, its been this way since the mod was created. I can make it configurable if you want me to though

**Comment by PSISeven** [comment]
I feel like it should be configurable. I personally think it feels unbalanced.
