### ISSUE TITLE
Rats & PMMO Incompatibility

### ISSUE THREAD

**Issue by Waterspark63** [Alex-the-666/Rats#883]
A Player on the server had gotten tamed rats, and got up to having a fisherman rat. When the rat fishes, on some occasions the item fished event returns no loot, and PMMO tries to retrieve the loot from fishing, causing the entire server to crash.

Mod Versions
PMMO: 1.20.1-1.3.22
Rats: 1.20.1-8.1.2
LexForge: 47.2.30

PMMO Side Report: https://github.com/Caltinor/Project-MMO-2.0/issues/563

Pmmo will be fixing the empty loot return with a check on that side, but is there a reason for rats to fire a item fished event with no returns? 

Latest.Log
[latest.log](https://github.com/user-attachments/files/
[crash-2024-06-29_12.26.16-server.txt]

Crash Report:
(https://github.com/user-attachments/files/16041915/crash-2024-06-29_12.26.16-server.txt)
16041914/latest.log)

**Comment by GizmoTheMoonPig** [comment]
Interesting, the table shouldnt be empty as im directly using the vanilla loot table to get the loot (https://github.com/AlexModGuy/Rats/blob/1.20/src/main/java/com/github/alexthe666/rats/server/entity/ai/goal/harvest/RatFishermanGoal.java#L142)
I'll add some extra handling if the table is empty for some reason. Thanks for letting me know about this
