### ISSUE TITLE
Cannot enable Ratlantis content on a previously created 1.20.1 world - aside from the achievements?

### ISSUE THREAD

**Issue by boltzmannuniverse** [Alex-the-666/Rats#886]
The mod itself claims that the Ratlantis datapack may be enabled retroactively, but this does not seem to work. However, for some reason, the achievements related to the datapack appear when I attempt to enable the mod via commands, while the rest of the content does not appear. Is there any way to resolve this issue and activate the Ratlantis-related content short of just creating a new world with the datapack enabled? What could be causing the achievements to appear when nothing else will? Note that this occurred within a custom modpack environment, so it could potentially be caused by an interaction between mods and not the Rats mod by itself.

**Comment by RuneAlaric** [comment]
If you want a workaround I found, generate a new SP world with the datapack enabled, then copy over the dimension data to whatever world you're in's save. It was how I got ratlantis to work on an established server.

**Comment by GizmoTheMoonPig** [comment]
If youre playing in 1.20.1 go into the common config and set `Ratlantis Enabled By Default` to true. Itll enable the pack in your world. I couldnt find a way to get it to work with the `/datapack enable` command so this works for now

**Comment by nolancparker-ops** [comment]
im trying right now to install the datapack in my world without resetting it what is the datapack for ratlantis link or where i can find it (also what is a common config)
