### ISSUE TITLE
Creative crashes the game on 1.20.1

### ISSUE THREAD

**Issue by StarZFox** [Alex-the-666/Rats#888]
I tried playing 1.20.1 in a modded server me and my friends own, unfortunately when i load it up in creative i cannot enter the creative menu and am met with this as the error 

Thread: Render thread
Suspected Mod: 
	Rats (rats), Version: 1.20.1-8.1.1
		Issue tracker URL: https://github.com/Alex-the-666/Rats/issues
		at TRANSFORMER/rats@1.20.1-8.1.1/com.github.alexthe666.rats.registry.RatsCreativeTabRegistry.registerColoredItems(RatsCreativeTabRegistry.java:367)
		
		If anyone knows how to fix this, please help

**Comment by MajinNina** [comment]
I am having the same problem as well 
[crash-2024-09-03_21.25.55-client rat.txt](https://github.com/user-attachments/files/16882986/crash-2024-09-03_21.25.55-client.rat.txt)

**Comment by GizmoTheMoonPig** [comment]
I dont modify stack sizes in the creative inventory, this is another mod causing the problem. It looks like something called "Just Utilities" might be doing it? They arent open source so I cant easily check what their mixin is doing. Try removing that and let me know. 
To the person who made the bug report please provide an actual crashlog like this other person did. I cant do anything with what you posted here

**Comment by Not-February** [comment]
[Dye Depot](https://www.curseforge.com/minecraft/mc-mods/dye-depot) is causing this. I've reproduced the crash with nothing but Rats and Dye Depot installed.

This makes quite a bit of sense when you consider that the crash references Rats' colored items.

[crash-2024-11-13_00.07.40-client.txt](https://github.com/user-attachments/files/17728695/crash-2024-11-13_00.07.40-client.txt)

**Comment by GizmoTheMoonPig** [comment]
ok, i can see why it is. That mod is an absolute hack when it comes to adding their own colors and they break like every mod that uses the DyeColor enum. I'll add a safeguard for this but it really shouldnt be something I need to fix
