### ISSUE TITLE
Server Crash: Client-side class loaded on dedicated server

### ISSUE THREAD

**Issue by Decryptu** [Alex-the-666/Rats#889]
## Description
The server crashed due to an attempt to load a client-side class on a dedicated server. This occurred while processing a TamedRat entity from the Rats mod.

## Steps to Reproduce
1. Have a tamed rat in the game.
2. Apply the golem mount upgrade to the rat in a small place.
3. Exit the menu after applying the upgrade.
4. The server crashes instantly.

## Environment
- Minecraft Version: 1.20.1
- Forge Version: 47.3.5
- Rats Mod Version: 1.20.1-8.1.2
- Server Type: Dedicated Server

## Error Message
```
java.lang.RuntimeException: Attempted to load class com/github/alexthe666/citadel/client/model/AdvancedModelBox for invalid dist DEDICATED_SERVER
```

Crash report:

[crash-2024-08-08_14.19.45-server.txt](https://github.com/user-attachments/files/16549592/crash-2024-08-08_14.19.45-server.txt)

**Comment by pucgenie** [comment]
Are you using Canary mod (contained in at least some Feed-the-Beast modpacks)? Then use this workaround from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5525 : Remove Canary mod from server's mods/ folder.

**Comment by Decryptu** [comment]
indeed, `canary-mc1.20.1-0.3.3.jar` is in the server mods folder, I'll try that later

**Comment by GizmoTheMoonPig** [comment]
this is caused by canary, nothing I can really do about it. I recommend avoiding the mod as it causes many issues with rats
