### ISSUE TITLE
I provided Turkish language support.

### ISSUE THREAD

**Issue by gereksizHesap** [Alex-the-666/Rats#891]
Hello, I noticed that there was no Turkish language support while using your game mode, so I wanted to offer my assistance.

[tr_tr.json](https://github.com/user-attachments/files/16763967/tr_tr.json)

**Comment by GizmoTheMoonPig** [comment]
Thanks for the contribution! In the future I would appreciate if this was done as a Pull Request instead so I dont have to manually download the file and add it to the mod, but itll be in 8.1.3 :)
