### ISSUE TITLE
Rats targeting and mob filters 1.20.1

### ISSUE THREAD

**Issue by GothCartel** [Alex-the-666/Rats#896]
The tamed rats on our server are behaving belligerently.
Mob filters are going blank as soon as you exit the GUI and when placed into  a rat the rat will attack the first thing they see including players and player tamed mobs.

Version 1.20.1-8.1.2

Forge 47.3.0

**Comment by GizmoTheMoonPig** [comment]
this will be fixed in 8.1.3 once I release it to CurseForge. I fixed this issue months ago in dev but never got around to releasing a build as life has kept me very busy this year
