### ISSUE TITLE
the mobGriefing effect needs indication

### ISSUE THREAD

**Issue by tsoewoe** [Alex-the-666/Rats#898]
i just spent a good hour trying to figure out what mod incompatibility could be causing the rat mod to break only to find out on here that it wasnt broken but that rats deliberately do not harvest if modgriefing is false, please indicate this somewhere in the game.

**Comment by GizmoTheMoonPig** [comment]
I do! I literally print a message in chat when the world is loaded with mob griefing disabled. I don't know what else you want

**Comment by tsoewoe** [comment]
ah - might be because am on the 1.20.1 version of the mod
