### ISSUE TITLE
[Bug] Chef rats only return one item crafted

### ISSUE THREAD

**Issue by DWX12** [Alex-the-666/Rats#9]
Rats with the cooking upgrade will only return a single special cooked item when given or carrying more than one vegetable item.

1. Give chef rat greater than one vegetable item
2. Rat cooks and holds one special cooked item deleting the rest of the stack of vegetables

**Comment by Alex-the-666** [comment]
its not deleted - they drop it on the ground. if you put them above a chest or hopper, they will deposit it to that.
