### ISSUE TITLE
[Suggestion] Expose the generated Ratlantis data pack specific contents for pack developers

### ISSUE THREAD

**Issue by Not-February** [Alex-the-666/Rats#900]
I'm currently using Rats 1.20.1-8.1.3, for reference.

It is currently rather difficult to alter the loot tables and recipes related specifically to Ratlantis without the use of third-party tools because of the way it generates itself on world load when enabled through configs.

I know it is technically possible to alter them by looking up the recipe/loot table IDs in a recipe viewer with loot table support like JEI or EMI, but not having the actual files to use as a reference makes the experience far more complicated than it reasonably needs to be and particularly harrowing where more complicated loot tables are involved if all I want to do is replace one item from the loot table with a functionally equivalent one from another mod(cheese, in this case).

Would it be unreasonable to ask for the Ratlantis-specific data files to be showcased or exposed somewhere so that pack developers can more easily add/tweak them as needed?

Some of these recipes/loot tables are already accessible with the source code on Github or in the mod's files, but for example the loot associated with the Flying Dutchrat and the recipes for processing cheese ore aren't. Having it all in one place to reference would be super helpful.

**Comment by GizmoTheMoonPig** [comment]
They are already, everything that ratlantis enables is all located here: https://github.com/AlexModGuy/Rats/tree/1.20/src/generated/resources/data/minecraft/datapacks/ratlantis/data

The datapack is not generated on world load, it is simply just a builtin datapack that is enabled based on if the world wants it to be or not. Simple as that

**Comment by Not-February** [comment]
I'm... genuinely unsure how I missed that, I guess I wasn't expecting it to be in the minecraft namespace. Thanks for pointing me in the right direction!
