### ISSUE TITLE
Rats not tameable in survival, not spawning from garbage heaps.

### ISSUE THREAD

**Issue by maxell45146** [Alex-the-666/Rats#93]
From the comments on the mod page it looks like others are having the same issue I was seeing. Giving a whole stack of cheese to a rat has no effect. Going into creative rats are able to be tamed like normal. 

Collected garbage heap blocks from a village, created a dark spawning area, no spawns. 
I was able to find natural spawns but ended up discovering the first issue.

**Comment by nephatrine** [comment]
I'm able to tame them in survival without issue. I think the comments on the mod page are from an older version.
