### ISSUE TITLE
White/blacklist unaccessible once combined

### ISSUE THREAD

**Issue by Jomeaga** [Alex-the-666/Rats#94]
Currently if you want to have a white/black list upgrade and say a platter you need to set the white/blacklist before combining as you can no longer interact with that functionality from the Combined Upgrade. The combined upgrade with a white/blacklist will still respect what you set, but you cannot edit it further.

If you could add the ability to edit the white/blacklist in a combined upgrade that would make it much more useful in my opinion.

**Comment by ratkinsonuk** [comment]
Same problem using Rustic Waters modpack
