### ISSUE TITLE
Rats and pipers don't spawn by default

### ISSUE THREAD

**Issue by yqmtat** [Alex-the-666/Rats#96]
Rats and pipers don't spawn by default.
No matter how I edit the config file, rats and pipers still won't spawn, tested in roofed forest biome, superflat world.
But rats spawn in the pet shop with world generation , weird.

**Comment by yqmtat** [comment]
but the second time I change:
    # True if Pied Pipers are to spawn naturally [default: true]
    # True if rats are to spawn naturally [default: true]
from false to true, they spawn.

**Comment by Alex-the-666** [comment]
delete ur config next time
